### ISSUE TITLE
Variable-length argument lists for PropertyMappingConfiguration methods

### ISSUE THREAD

**Issue by jdoubleu** [neos/flow-development-collection#1012]
Yet the [`allowProperties()`](https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Property/PropertyMappingConfiguration.php#L153), [`skipProperties()`](https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Property/PropertyMappingConfiguration.php#L168) and [`allowAllPropertiesExcept()`](https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Property/PropertyMappingConfiguration.php#L185) methods of the [`PropertyMappingConfiguration`](https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Property/PropertyMappingConfiguration.php) class don't have arguments defined but use the `func_get_args()` function to retrieve all arguments from this function's call.

PHP5.6+ supports [variable-length argument lists'](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list).

This argument list might also be strongly typed (e.g. with `string` for property names).

*Example:*
```PHP
public function allowProperties(string ...$propertyNames)
{
    foreach ($propertyNames as $propertyName) {
        $this->propertiesToBeMapped[$propertyName] = $propertyName;
    }
    return $this;
}
```

This would improve the API docs, the readability and the IDE support.

Is there a good reason why this isn't implemented yet? Or should it be part of https://github.com/neos/flow-development-collection/pull/999?

May I create a PR?

**Comment by kitsunet** [comment]
As we switched our minimum required version from 5.3 to 7.0 with the last major a few months ago I am sure there are many places where we could improve like that. Please open a PR every of those improvements is welcome :)

**Comment by albe** [comment]
What Christian said :)

**Comment by zaveryukha** [comment]
I think this issue can be closed?
PR #1035 merged.
