### ISSUE TITLE
Using a proxy with cURL leads to misbehaving in splitting header and body

### ISSUE THREAD

**Issue by eduardklusch-decix** [neos/flow-development-collection#1044]
### Description

When using a system-wide proxy, TYPO3\Flow\Http fails to correctly split HTTP headers and content. This happens because there is a loop parsing every single response line and stops at the first empty line it finds which usually splits header from content:

File: Response.php, at line 144
`foreach ($lines as $line) {
if ($parsingHeader) {
if (trim($line) === '') {
$parsingHeader = false;
continue;
} ... } ... } ...
`

In case a system wide proxy is set (ex.: env var http_proxy/HTTPS_PROXY in web server or php-fpm config), there are two header blocks in a cURL response while the first block represents the direct answer from proxy and the second one the forwarded block the proxy server received from request target.

### Steps to Reproduce

1. Configure http(s) proxy to use by setting http_proxy and/or HTTPS_PROXY env var in web server config or php-fpm config, depending on what is used
2. Create a HTTP network request by using TYPO3\Flow\Http framework package
3. Call `$response->getContent()` function which then contains the forwarded headers in the first lines

#### Expected behavior

`$response->getContent()` function should only return the request body. The first, usually unnecessary header lines (directly from proxy connection) should be truncated and not parsed as header lines instead of actually needed response headers from target server.

#### Actual behavior

`$response->getContent()` function returns the forwarded HTTP header lines the proxy received from request target before the actual response content starts.

### Affected Versions

Neos: 2.3.14

Flow: 3.3.15

**Comment by kdambekalns** [comment]
See #849 and #570…

**Comment by albe** [comment]
Should be fixed with the above merged PR. So closing this. If anything still comes up, feel free to reopen.
