### ISSUE TITLE
Allow "remote" logout for other accounts' sessions

### ISSUE THREAD

**Issue by maltemuth** [neos/flow-development-collection#1051]
### Description

Currently, there is no clean way to remove sessions that belong to another account. Deactivating an account (e.g. by setting a past expirationDate) will leave the sessions intact.

A way around this is to mimic the behavior of the AuthenticationProviderManager when creating sessions:

`$sessionManager->destroySessionsByTag( 'Neos-Flow-Security-Account-' . md5($account->getAccountIdentifier()) );`

which will effectively "log out" the given `$account`.

#### Wanted Behavior

Some API that does not involve calculating / guessing session tags, perhaps `$sessionManager->destroySessionsByAccount($account)`.

### Affected Versions

Flow 4.1.5, maybe earlier.

**Comment by albe** [comment]
Thanks for creating the issue! Definitely worth having

**Comment by maltemuth** [comment]
After reading the code some more, I found the following:

The mentioned line relies on the fact that sessions for a given `$account` are tagged with `'Neos-Flow-Security-Account-' . md5($account->getAccountIdentifier())`; this appears in
1) The `AuthenticationProviderManager` when creating a session
2) The `AccountRepository` when removing an account (also logging out all sessions for that account)
3) Perhaps other places I haven't found

Right now, there's no "single source of truth" for the fact that sessions are being tagged that way, and adding this feature will most definitely add a third place, so I think it would be wise to remove this implicit knowledge now and also add a service method that returns the expected session tag for a given account.

I'm really unsure about the right class to add these methods to:
a) The `AuthenticationProviderManager` does not have `Account` anywhere in its Interface yet (neither does the `AuthenticationManagerInterface`, but both methods would have `Account` in their signature.
b) The `SessionManager` does not know about accounts at all.

It seems to me that the only place in the codebase that knows about Sessions _and_ Accounts is the `AuthenticationProviderManager`, whose responsibility is the authentication of tokens, which does not seem to match this feature (log out accounts remotely).

So I'm looking for feedback: Where should these methods go? a or b? Or even a new class? What would that be called?

**Comment by kitsunet** [comment]
It rightfully belongs to neither Security nor Session but should be in a new joined package/place. If anything then security probably knows more and I am not sure if security even works remotely without knowledge of Sessions, which I doubt. So it could be in security.

**Comment by maltemuth** [comment]
> not sure if security even works remotely without knowledge of Sessions

It doesn't (as far as I can see). The only thing needed to "cleanly" introduce the concept of a remote (non-current) session is, I think, the formalization of the session-account relation.

Maybe something like
```php
class AccountSessionList {
  public function __construct (Account $account) {
  …
  }

  public function destroyAll() {
  …
  }

  public function getSessionTag() {
  …
  }
}
```

**Comment by albe** [comment]
Well, the API to destroy a session should belong to the SessionManager ofc. It just shouldn't know about Accounts.

Optimally, Authentication should work without knowing about sessions, but only about some "TokenStorage" - currently this is the `Security Context`. The context is also the place that connects Accounts and Sessions. It merges Tokens from the AuthenticationManager and the current session. It also maps Accounts to Roles and provides the currently authenticated Account. So I would put the logic for tagging and destroying sessions (by current or arbitrary Account) there.
