### ISSUE TITLE
Controller Arguments Action mapping error

### ISSUE THREAD

**Issue by limchivy** [neos/flow-development-collection#1062]
### Description

Look at this example method:
```
/**
 * @param Person $person
 */
public function showAction(Person $person) { ... }
```

I created the simple function with the required argument `$person`, then I configure the error exception handler in the `Settings.ymal` of all 401, 404, 500 as below:
```
TYPO3:
  Flow:
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            matchingStatusCodes: [404]
            ....
          errorExceptions:
            matchingStatusCodes: [500]
            ...
```
Everything looks fine of the error page if there is a wrong typing uri. But it seems an error if the uri param has empty value. eg. `http://...domain...?person=` or `http://...domain...?person`

### Steps to Reproduce

1. Browse url with empty value of `person` param as above example
2. Then we see error as blow instead of the error page what we had configure
```
Uncaught Exception in Flow
Argument 1 passed to ...\Controller\PersonController::showAction() must be an instance of ...\Domain\Model\Persion, null given
TypeError thrown in file ...
```

#### Expected behavior

It would be always shown the error page which we had configured.

### Affected Versions

Neos: n/a

Flow: any

**Comment by kitsunet** [comment]
Ok thanks, that's very helpful :)
I will have a look at the code and PR!

**Comment by kitsunet** [comment]
Ok, sorry for taking so long @limchivy I would suggest the better way to get the right response in this case is a custom route with a route part handler that only matches IF the given argument actually is an ID and not empty. That should then result in the route not matching in turn getting you a 404. The proposed change seems to invasive and the effects might be problematic for other edge cases.

**Comment by albe** [comment]
Closing as wontfix. Feel free to bring the discussion up again if this is still debatable.
