### ISSUE TITLE
composer create-project use abandoned packages

### ISSUE THREAD

**Issue by jkhaled** [neos/flow-development-collection#1078]
### Description

[when creating project with composer create-project it use abandoned packages]

### Steps to Reproduce

1. [go to the flow framework installation page  with [install](https://github.com/neos/flow/blob/1350f25facea561f809527a3baf62c7b1e08ee32/Documentation/TheDefinitiveGuide/PartII/Installation.rst)  ]
2. I followed the steps of project creation using composer create-project
3. [I run the cmd `composer create-project --keep-vcs neos/flow-base-distribution tutorial 3.0.0]`

#### Expected behavior
  
create project with last version of flow framework library

#### Actual behavior

I got this message that said the packages used are abondoned 

> Package typo3/flow is abandoned, you should avoid using it. Use neos/flow instead.
Package typo3/eel is abandoned, you should avoid using it. Use neos/eel instead.
Package flowpack/behat is abandoned, you should avoid using it. Use neos/behat instead.
Package typo3/welcome is abandoned, you should avoid using it. Use neos/welcome instead.
Package typo3/kickstart is abandoned, you should avoid using it. Use neos/kickstarter instead.

### Affected Versions

Neos:

> typo3/buildessentials             3.0.5              TYPO3 Flow Build Toolchain Essentials
typo3/eel                         3.0.15             The Embedded Expression Language (Eel) i...
typo3/flow                        3.0.15             Flow Application Framework
typo3/fluid                       3.0.15             Next-Generation Templating Framework for...
typo3/kickstart                   3.0.15             A simple generator for controller and vi...
typo3/welcome

Flow:

You can get this information by running `composer show`.

**Comment by bwaidelich** [comment]
@jkhaled Thank you for this report.
Version 3.0 of Flow still uses the `typo3/*` packages that have been moved to `neos/*` for the next major version (the currently latest stable version of Flow is 4.2).
You can safely ignore those warnings if you really intended to install 3.0

I'll leave this ticket open though as a reminder to update the documentation accordingly
