### ISSUE TITLE
Wrong source data type for boolean in string converter

### ISSUE THREAD

**Issue by dennisirmscher** [neos/flow-development-collection#1103]
### Description

Wrong source data type for boolean in string converter

### Steps to Reproduce

1. E.g. try to export site content containing boolean values

#### Expected behavior

A site export...

#### Actual behavior

> Exception while property mapping for target type "string", at property path "": No converter found which can be used to convert from "boolean" to "string".

### Error in

https://github.com/neos/flow/blob/master/Classes/Property/TypeConverter/StringConverter.php#L79

Should be "boolean", not "bool"

### Affected Versions

Flow: 4.\*.\*

**Comment by bwaidelich** [comment]
FYI This has to be fixed in Flow: https://github.com/neos/flow-development-collection/issues/1106

**Comment by bwaidelich** [comment]
Closing this one in favor of #1106 and https://github.com/neos/neos-development-collection/issues/1732
