### ISSUE TITLE
RestController should not mutate Request object when resolving action name

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#1123]
Currently, the `RestController` overwrites the controller action name of the current active Request object according to the HTTP methods. This leads to URIs being generated in the UriBuilder that do not match the expected short form, e.g.:

`POST /api/foo` would lead to the UriBuilder trying to create an URI like `/api/foo/create`. If routes are not configured accordingly, then this will even fail.

The solution is, to not mutate the current `Request` object when routing the HTTP method to an action.

/cc @stephanschuler

**Comment by kitsunet** [comment]
It changes the HTTP request? Yes, lets change that ASAP please
