### ISSUE TITLE
Available Locale Detection is finding too many invalid locales

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#1232]
### Description

The scanning for available Locales, which is scanning Folders inside `Resources/*` for filenames that contain a locale-like prefix before the file extension, is currently also taking a lot of invalid locales into account. Therefore things like "cli", "peg", "min", "css" and others are considered "available" Locales (for example when scanning minified css/js files inside Public Resources).

### Affected Versions

Flow: all

### Strategies to solve the issue:

We could further restrict scanning of folders for next major version (see also https://github.com/neos/flow-development-collection/pull/385) so that really only the Translation folders are scanned by default. This would be easy to implement, but needs some documentation.

Or we allow to somehow also specify, which packages are scanned at all, so that for example only the application package can be scanned and hence the avilable locales be controlled very directly. This would require to change the `includePaths` and/or `excludePatterns` options for the `i18n.scan` setting.

**Comment by kitsunet** [comment]
TBH, I would scrap this scanning and make it something you configure?

**Comment by albe** [comment]
I do think it has some value when scanning translation files of the application package, so you don't have to manually configure a list of locales you support, but instead just drop another translation file in.

But a configuration option to define a list of "available" Locales sounds reasonable.

**Comment by cwenzelg** [comment]
we are also currently working on translations. i would love the idea to only define the list of available locals via a configuration as we have some langue files already there but they are still work in progress and not considered "available" yet.

**Comment by albe** [comment]
Okay, so it's now (as of the upcoming 5.0) possible to set an explicit list of available Locales via configuration, which will prevent the scanning from happening. Also, the scanning will now only go through `Public` and `Private/Translations` folders by default. We are thereby now free to deprecate the scanning if we decide to, since there is an alternative.

For now, I see this issue as resolved, so closing this.
