### ISSUE TITLE
Setting the target type of a controller argument should be possible during runtime

### ISSUE THREAD

**Issue by bweinzierl** [neos/flow-development-collection#1263]
### Description

You currently cannot set the target type of a controller argument. This is only possible by annotation or with the __type parameter. Both are not usable when i want to calculate the target type during runtime.
Even if i try to add a __type parameter to the arguments in ->initializeAction this only works partly because the validation is not used (as it is already initialized before ->initializeAction)

#### Expected behavior

There should be a method "setDataType" in Neos\Flow\Mvc\Controller\Argument to set the DataType from the initializeAction method.

#### Actual behavior

This is just not possible as i see it

### Affected Versions

current stable

**Comment by albe** [comment]
`setTargetTypeForSubProperty` is able to set the target type of any however deeply nested property via dot-notation, so it can also be used to set the type for a direct property. 
It's just a convenience function for

```
$configuration->forProperty($propertyPath)->setTypeConverterOption(PersistentObjectConverter::class, PersistentObjectConverter::CONFIGURATION_TARGET_TYPE, $targetType);
```

Similar, if you want to set the target type of one controller argument programmatically (inside `initialize*Action`), you should be able to do

```
$this->getArgument($argumentName)->getPropertyMappingConfiguration()->setTypeConverterOption(PersistentObjectConverter::class, PersistentObjectConverter::CONFIGURATION_TARGET_TYPE, $targetType);
```

So what exactly are you trying to achieve, that is not possible right now?

**Comment by bweinzierl** [comment]
I think i was a bit unclear in my issue description. I will modify it.

I am looking to change the DataType of a argument (not a property of that argument) during runtime in the initializeXyzAction().
In an earlier version of flow (v2.3) there once was a method TYPO3\Flow\Mvc\Controller\Argument::setDataType() that seems to have done that but it is not there in the current version of flow.

**Comment by albe** [comment]
Indeed, that method has been removed after 3.3, where it got deprecated:

https://github.com/neos/flow-development-collection/commit/7147522852bbd425f3a12e6d1c7685718898b75b#diff-e6aa0947a6ed657f5fefb91c32f045e5

Maybe @kitsunet can explain a bit or has an alternative solution.

**Comment by albe** [comment]
Related to #1906 

Closing for now since I think this is solvable with the above mentioned TypeConverterOption (and dynamic validation is dealt with in the before mentioned PR). If there is still something missing, feel free to reopen.
