### ISSUE TITLE
Match RouteParts with ObjectType 

### ISSUE THREAD

**Issue by rolandschuetz** [neos/flow-development-collection#1274]
### Description

Match RouteParts with ObjectType

### Steps to Reproduce

1. Create a Route like shown in Manual
```
-
  name: 'Single product route'
  uriPattern: 'products/{product}'
  defaults:
    '@package':     'My.Demo'
    '@controller':  'Product'
    '@action':      'show'
  routeParts:
    product:
      objectType: 'My\Demo\Domain\Model\Product'
```
2. Call an Uri
3. Watch 404 not Found

#### Expected behavior

Resolve an correct Uri

#### Actual behavior

Get 404, when URI wasn't created throw an Viewhelper or something else first.
(no entry on ObjectPathMappingRepository)
If no Entry is found on Mappingtable, an Mapping should be created!
### Affected Versions

Flow: 4.2.4

Documented by @nixahnung at [Neos Issues #1750](https://github.com/neos/neos-development-collection/issues/1750)

**Comment by sorenmalling** [comment]
What URI are you actually requesting? 

What Flow expects, is the UUID of a `My\Demo\Domain\Model\Product` object and try and find that.

**Comment by sorenmalling** [comment]
@rolandschuetz Can you please elaborate on this issue?

**Comment by rolandschuetz** [comment]
@sorenmalling Thats not my issue, I just moved it to the correct place.

@nixahnung Can you please elaborate

**Comment by sorenmalling** [comment]
@albe I suggest to close this issue do to no response and missing details in the issue.

The described functionality is known to me as being THE functionality and so is the issue solved :)
