### ISSUE TITLE
ComponentContext should be made available everywhere

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#1304]
This context should be the single API for retrieving the "current" request and response objects inside an web request context.

Also, the `ComponentContext` should probably be renamed to `HttpContext`

See also #550

**Comment by albe** [comment]
Question: How should the `HttpContext` be made available?

**Comment by albe** [comment]
Simplest solution would be making it injectable, but that would only work after the RequestHandler has started (but still before it is "booted") and only for HTTP requests, so the injection would be somewhat fragile.

Another solution would be to just make the `RequestHandler` injectable, as that is created very early in the bootstrap process (see `Bootstrap::run()`), but would mean another level of indirection.

**Comment by kitsunet** [comment]
but hten you might as well go the route we have right now. Get Bootstrap injected -> `$this->bootstrap->getActiveRequestHandler();` -> check if http request handler etc. etc.

I don't see how we can make this automatic and ensure it's actually right. Seems like the same conundrum as with the baseUris.

**Comment by albe** [comment]
Well, at least we would get rid of one layer of indirection... but yeah, still far from optimal.

**Comment by albe** [comment]
Related to #1889 - I think we don't even need a `Component/HttpContext` in the long run at all. It was a convenience artefact of passing mutable req/res classes around.

However, we still need some means to access the `current request/response` from places outside the controller (and even there we only have indirect access to the http request via the ActionRequest - which is good though). Now those need to be few clearly defined places - like the security stack.
Anyway, autowired injection is out of the question then. Request/Response should only directly be passed on to be immediately used and passed further/returned.
 
The first place I'd like to get rid of the `ComponentContext` is in the new `ActionResponse::mergeIntoComponentContext($context)` method, which should be trivial.

**Comment by albe** [comment]
I added the `ComponentContext` to early instances in https://github.com/neos/flow-development-collection/pull/1928/files#diff-c9a34331dc86f0b1a7fe83d9e9473725R97 - this should work most of the time (unless you have custom code that runs in the index/bootstrap). However, we still need to get rid of this thing anyway.

**Comment by albe** [comment]
closing as of #1928 and since this will be removed anyway
