### ISSUE TITLE
Flow 5: Usage of the RedisBackend as session store leads to error during garbage collection

### ISSUE THREAD

**Issue by tt761151** [neos/flow-development-collection#1311]
When using the `RedisBackend` cache Backend for as session store, the current implementation of the `\Iterable` interface  of `\Neos\Cache\Backend\RedisBackend` leads to an error during the session garbage collection (or anything that traverses the cache). 

I currently don't have the exception at hand, but it is related to the return type specified for implementation of the `key()` function.

The return type is defined as string, but Redis returns false on a non existing index. The `valid()` function uses the return of this `key()` function and checks if it is false, but gets the string cast element returned, which then leads to the iterator trying to retrieve the non existent element.

PHP: 7.1.17
Flow: 5.0.2

**Comment by johannessteu** [comment]
I also git some weired cacheing issues with Fusin_Contetn_Cache in Redis. Should be related. "Feels" like the cache invalidation does not work correctly.

I guess the return type is just wrong. The method could return false as well as an string
https://github.com/neos/flow-development-collection/blob/master/Neos.Cache/Classes/Backend/RedisBackend.php#L249

We had some similar issues on another release where return types were added >.>

**Comment by tt761151** [comment]
On our project I also did the same, remove the return type declaration for RedisBackend->key(), as a hotfix.
