### ISSUE TITLE
Method checkValueObjectRequirements should ignore setters for transient properties

### ISSUE THREAD

**Issue by P34CH** [neos/flow-development-collection#1316]
In the current implementation of the method `checkValueObjectRequirements` of class `\Neos\Flow\Reflection\ReflectionService` a value object is only considered valid, if it has no setter methods.

In my opinion, setter methods for transient properties of a value object should be allowed.

Example use case: Imagine a value object where runtime-information (e.g. access rights) are stored in a transient property of this value object.

https://github.com/neos/flow-development-collection/blob/c045d778bf5e58e164a37a0d40ca2f08ddae553a/Neos.Flow/Classes/Reflection/ReflectionService.php#L1741

**Comment by bwaidelich** [comment]
Thank you for this bug report.

> In my opinion, setter methods for transient properties of a value object should be allowed [...]
> Imagine a value object where runtime-information (e.g. access rights) are stored in a transient property of this value object

If the Value Object stores runtime information, why do you need a setter for it?
We consider VOs to be immutable, so they must not be changed from "the outside"

**Comment by p34ch** [comment]
Thanks Bastian for your reply!

In our current use case we created a Trait which adds an additional property called `_permissions` of type array to domain model objects (entities / value objects). The values for these properties are to be calculated at runtime depending on the object data and the currently active account/party.

Of course it would be possible to declare the property itself as public for directly setting the objects _permissions values. That approach would not correspond to the general "use getters/setters for all your domain model properties" policy. Thus, prohibiting setters for transient value object properties could lead to bad coding habits...

By the way: Does using transient properties in your point of view make any sense at all? If one is not allowed to change the state of a value object from the outside - how can transient properties in such domain model objects be populated and mutated to reflect runtime environment?

**Comment by bwaidelich** [comment]
> Of course it would be possible to declare the property itself as public for directly setting the objects _permissions values

You can access the Trait fields even if they are private:

```php
<?php
trait PermissionsTrait {
    private $_permissions = [];
}

final class SomeValueObject {
    use PermissionsTrait;

    public function __construct()
    {
        $this->_permissions['foo'] = 'bar';
    }
}
```

> Does using transient properties in your point of view make any sense at all?

Hard to tell, those discussions are better held on our [public channels](https://www.neos.io/community/social-media.html)

**Comment by P34CH** [comment]
> You can access the Trait fields even if they are private:

That's correct obviously! The problem is now, that the permissions are evaluated in a dedicated service which analyzes the value objects property values as well as various entity (and other) privileges. Therefore, the values for the _permissions array needs to be set from the outside.

We worked around this issue by naming our "setter"-methods for different properties in the _permissions array in the form of `[allow|deny]Object[Create|Update|Delete]()`. Therefore, this issue is no longer really relevant for our project. I just wanted to point out a potential weakness of the quite strict "no setters allowed" check. I'll leave it up to you, whether it's worth continuing this discussion on other channels.

**Comment by bwaidelich** [comment]
OK, thanks for clarifying this!
I'll close this issue for now. But I think it's a good reference, and if anyone comes across this and has a good idea on how to improve it, feel free to re-open
