### ISSUE TITLE
Wrong documentation of FlowQuery-slice-operation

### ISSUE THREAD

**Issue by dennisirmscher** [neos/flow-development-collection#1322]
### Description

According to the [documentation](https://github.com/neos/neos-development-collection/blob/4.0/Neos.Neos/Documentation/References/FlowQueryOperationReference.rst) the slice-operation expects an offset and a length, similar to _array_slice_ in PHP.

In the [implementation](https://github.com/neos/flow-development-collection/blob/5.0/Neos.Eel/Classes/FlowQuery/Operations/SliceOperation.php#L46) though the second argument is expected to be the end position within the array rather than the length of results. This is similar to the _Array.slice_ Eel helper.

In order to keep compatibility I would suggest to update the documentation.

### Affected Versions

I did not find the earliest version of the documentation, but the implementation was like this since the very first release of Flow.

**Comment by bwaidelich** [comment]
Hi @dennisirmscher and thank you for the bug report!

> In the implementation though the second argument is expected to be the end position within the array rather than the length of results

Good catch and I agree that we should fix the docs rather than the implementation for backwards compatibility reasons.

Would you be willing to create a corresponding Pull Request?

**Comment by bwaidelich** [comment]
@dennisirmscher _ping_ ;)

**Comment by dennisirmscher** [comment]
@bwaidelich I'm so sorry, I'm currently in the final stage of a project and really short on time. But I will send a MR asap. I think next week at the latest, when I'm finally on vacation :)

**Comment by kitsunet** [comment]
No worries <3

**Comment by bwaidelich** [comment]
No worries at _all_ - just a friendly reminder. And let us know if we can help with the PR!

**Comment by dennisirmscher** [comment]
So, it took me another week to update just one sentence. I'm really sorry for the delay, but finally I created a PR: https://github.com/neos/neos-development-collection/pull/2113

I wasn't sure about the target branch though. According to the roadmap it should get updated in 2.3, too, but the file structure is completely different there. How do you handle this? I'll update the PR of cause if necessary. Thank you in advance for helping me out! :)

**Comment by daniellienert** [comment]
Hey @dennisirmscher, 

thanks for the PR! Well, as you offer it, it would be indeed great if you fix that in the 2.3 branch. The upmerge from 2.3 to 3.0 is indeed painful sometimes but doable ;)

**Comment by dennisirmscher** [comment]
Hey @daniellienert,

all right. As changing the base branch really messes up everything I created a new PR for Neos 2.3: https://github.com/neos/neos-development-collection/pull/2117

Can I somehow be of help with the upmerge?

**Comment by albe** [comment]
I guess this can be closed since the according PR has been merged in the meantime. Thanks again!

**Comment by albe** [comment]
Well, but somehow it looks like it felt pray to the EOL of the 2.3 branch and didn't get upmerged. Do a upmerge once or manually port this change to 3.3?
