### ISSUE TITLE
Reflection of arguments annotated as `|null`

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#1361]
Currently, the ReflectionService does not deal properly with arguments to methods (and properties?) that are annotated as "nullable" via the `|null` pattern.

This leads to following effects:

- for an argument, that is not also typehinted nullable via `= null` default value, the `ALLOW_NULL` reflection property is not set

- such arguments are not properly type expanded and end up as `SomeClass|null` in the reflection data instead of `Acme\Foo\Bar\SomeClass|null` (this in turn prevents proper type conversion from happening - see also #1358)

**Comment by bwaidelich** [comment]
Fixed with #1358 - Thanks!
