### ISSUE TITLE
Symfony\Component\Console\Exception\RuntimeException after update to Flow 5.0.7

### ISSUE THREAD

**Issue by DavidSporer** [neos/flow-development-collection#1382]
### Description

We're using a lot of job queues in our project. After the update to Flow 5.0.7 the below Exception occurs.
We're using the jobqueue-doctrine package. There have been no changes to either the jobqueue package itself nor the jobqueue-doctrine package recently as far as I saw so I guess it must be something that has been introduced in one of the recent flow updates.
`
Symfony\Component\Console\Exception\RuntimeException: Aborted
#20 /application/Packages/Libraries/symfony/console/Helper/QuestionHelper.php(118): doAsk
#19 /application/Packages/Libraries/symfony/console/Helper/QuestionHelper.php(63): ask
#18 /application/Data/Temporary/Production/SubContextBeach/SubContextCluster/Cache/Code/Flow_Object_Classes/Neos_Flow_Cli_ConsoleOutput.php(186): ask
#17 /application/Data/Temporary/Production/SubContextBeach/SubContextCluster/Cache/Code/Flow_Object_Classes/Neos_Flow_Cli_CommandController.php(196): mapRequestArgumentsToControllerArguments
#16 /application/Data/Temporary/Production/SubContextBeach/SubContextCluster/Cache/Code/Flow_Object_Classes/Neos_Flow_Cli_CommandController.php(127): processRequest
#15 /application/Data/Temporary/Production/SubContextBeach/SubContextCluster/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Dispatcher.php(154): initiateDispatchLoop
#14 /application/Data/Temporary/Production/SubContextBeach/SubContextCluster/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Dispatcher.php(86): dispatch
#13 /application/Packages/Framework/Neos.Flow/Classes/Cli/CommandRequestHandler.php(108): Neos\Flow\Cli\{closure}
#12 /application/Data/Temporary/Production/SubContextBeach/SubContextCluster/Cache/Code/Flow_Object_Classes/Neos_Flow_Security_Context.php(242): __invoke
#11 /application/Data/Temporary/Production/SubContextBeach/SubContextCluster/Cache/Code/Flow_Object_Classes/Neos_Flow_Security_Context.php(242): withoutAuthorizationChecks
#10 /application/Data/Temporary/Production/SubContextBeach/SubContextCluster/Cache/Code/Flow_Object_Classes/Neos_Flow_Security_Context.php(1162): withoutAuthorizationChecks
#9 /application/Data/Temporary/Production/SubContextBeach/SubContextCluster/Cache/Code/Flow_Object_Classes/Neos_Flow_Security_Context.php(0): call_user_func_array
#8 /application/Packages/Framework/Neos.Flow/Classes/Aop/AdvicesTrait.php(56): Flow_Aop_Proxy_invokeJoinPoint
#7 /application/Packages/Framework/Neos.Flow/Classes/Aop/Advice/AdviceChain.php(59): proceed
#6 /application/Data/Temporary/Production/SubContextBeach/SubContextCluster/Cache/Code/Flow_Object_Classes/Neos_Flow_Session_Aspect_LazyLoadingAspect.php(117): callMethodOnOriginalSessionObject
#5 /application/Packages/Framework/Neos.Flow/Classes/Aop/Advice/AroundAdvice.php(35): invoke
#4 /application/Packages/Framework/Neos.Flow/Classes/Aop/Advice/AdviceChain.php(57): proceed
#3 /application/Data/Temporary/Production/SubContextBeach/SubContextCluster/Cache/Code/Flow_Object_Classes/Neos_Flow_Security_Context.php(1176): withoutAuthorizationChecks
#2 /application/Packages/Framework/Neos.Flow/Classes/Cli/CommandRequestHandler.php(109): handleRequest
#1 /application/Packages/Framework/Neos.Flow/Classes/Core/Bootstrap.php(110): run
#0 /application/Packages/Framework/Neos.Flow/Scripts/flow.php(61): null
`

### Steps to Reproduce

1. Configure a job queue and run it
2. If you're executing ./flow job:work queuename as a service, the job fails, if you're running it interactively from the cli it stays in reserved state

#### Expected behavior

I simply expect the job queue to go through.

#### Actual behavior

The jobs either fail or stay in reserved state. The exception looks to me as if something tries to get input from the command line.

### Affected Versions

Flow:
It works with Flow 5.0.6
It both fails with Flow 5.0.7 and 5.1.1.

**Comment by DavidSporer** [comment]
Hi,

I've set up a small project that allows one to reproduce the behaviour: https://github.com/DavidSporer/flow-jobqueue-bug
The readme of the repository describes what to do.

Let me know if I can add more info.

**Comment by kdambekalns** [comment]
This might be related to https://github.com/neos/flow-development-collection/pull/1355
