### ISSUE TITLE
How to log exceptions after PSR logger refactoring?

### ISSUE THREAD

**Issue by hlubek** [neos/flow-development-collection#1411]
### Description

There seems to be no way of logging exceptions when using a PSR based logger. The "default" logger is deprecated (as well as the `SystemLoggerInterface`). A PSR LoggerInterface based logger implementing the `ThrowableStorageInterface` doesn't get an instance that is capable of performing `logThrowable`.

### Steps to Reproduce

1. Create a new logger interface

```
interface MyLoggerInterface extends \Psr\Log\LoggerInterface, \Neos\Flow\Log\ThrowableStorageInterface {}
```

2. Define an instance of that logger in `Objects.yaml` by using the `PsrLoggerFactoryInterface`
3. Try to log an exception with `logThrowable`

#### Expected behavior

The exception should be logged and recorded using the configured `ThrowableStorage` (as a file).
There should be some _documented_ way of logging exceptions and how to use non-deprecated logging mechanisms for doing that.

#### Actual behavior

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Neos\Flow\Log\Psr\Logger' does not have a method 'logThrowable'
```

### Affected Versions

Flow: 5.0.*

**Comment by kitsunet** [comment]
https://discuss.neos.io/t/logging-exceptions-and-the-psr-logger/3605

**Comment by hlubek** [comment]
Thanks for the hint. That's okay for me to inject two separate objects for that specific case.
