### ISSUE TITLE
File uploads with "/" in name doen't work

### ISSUE THREAD

**Issue by futape** [neos/flow-development-collection#1467]
### Description

When uploading a file using an HTML `input` element with a `name` attribute containing a HTML array containing "/"s, the `$_FILES` array isn't untangles properly in the HTTP `Request`.

### Steps to Reproduce

1. Add an element `<input type="file" name="foo[bar/baz]">`
2. Upload a file
3. The `Neos\Flow\Http\Request::$uploadedFiles` property containg an empty array

#### Expected behavior

The array should look like this:

```
array(1)
 'foo' (9) => array(1)
   'bar/baz' (8) => Neos\Flow\Http\FlowUploadedFile
     originallySubmittedResource => NULL
     collectionName => NULL
     clientFilename => 'kirill-bubochkin-570219-unsplash.jpg' (36)
     clientMediaType => 'image/jpeg' (10)
     error => integer 0
     file => '/tmp/phpDBhfeI' (14)
     moved => false
     size => integer 1248317
     stream => NULL
```

#### Actual behavior

The array is empty since the `$_FILES` array isn't untangled properly.

### Affected Versions

Neos: -

Flow: 5.1.5

**Comment by daniellienert** [comment]
Fixed with #1469
