### ISSUE TITLE
Setupable PDO cache backend is broken

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#1513]
### Description

PdoBackend cannot be used when it's status is requested/used.

### Steps to Reproduce

1. Configure a cache to use the PdoBackend
2. Run `flow:cache:setupall` or `flow:cache:list` or `flow:cache:show`

#### Expected behavior

Cahces are set up, listed or have their details shown

#### Actual behavior

```
Unknown column type "flow_json_array" requested.
Any Doctrine type that you use has to be registered with
\Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known
types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs
during database introspection then you might have forgotten to register
all database types for a Doctrine Type. Use
AbstractPlatform#registerDoctrineTypeMapping() or have your custom types
implement Type#getMappedDatabaseTypes(). If the type name is empty you
might have a problem with the cache or forgot some mapping information.

  Type: Doctrine\DBAL\DBALException
  File: Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php
  Line: 283
```

### Affected Versions

Flow: 5.2.0 and up

**Comment by kdambekalns** [comment]
The `Unknown column type "flow_json_array" requested` error is the result of `PdoBackend.getStatus()` trying to build a schema using `$connection->getSchemaManager()->createSchema()`.

The error does only show, if `doctrine:migrate` has already been run, obviously, otherwise no columns using `flow_json_array` exist.

**Comment by kdambekalns** [comment]
The fix would be to register the types (we usually do that in `EntityManagerConfiguration.enhanceEntityManager()` using signal/slot in Flow) before trying to build the schema.

**Comment by bwaidelich** [comment]
Thanks for reporting this and sorry for the broken behavior there.. Isn't there a way to create a schema without doctrine having to check the custom types?

and.. probably it wasn't a good idea to silently add this implicit dependency to doctrine to the `neos/cache` package to begin with..
Maybe just check if the tables exist via PDO? I could take care of dismantling it like that, if you agree

**Comment by kdambekalns** [comment]
Well, not using Doctrine would be the best way, I guess. The cache package should be independent / slim, after all…

**Comment by bwaidelich** [comment]
@kdambekalns sorry, that took me a while but there you go: https://github.com/neos/flow-development-collection/pull/1690
