### ISSUE TITLE
Security openssl_public encrypt ... padding attack

### ISSUE THREAD

**Issue by kaystrobach** [neos/flow-development-collection#1566]
### Description
![grafik](https://user-images.githubusercontent.com/1185776/56942742-8a983d00-6b1c-11e9-8523-9ae544dbade3.png)

![grafik](https://user-images.githubusercontent.com/1185776/56942776-ab609280-6b1c-11e9-9e4d-3bf655e60d0c.png)

### Steps to Reproduce

https://threatpoint.checkpoint.com/ThreatPortal/threat?threatId=CVE_2016_2107&threatType=protection

#### Expected behavior

use `OPENSSL_PKCS1_OAEP_PADDING` as 4th parameter to harden against the attack

#### Actual behavior

not protecrted

### Affected Versions

Neos:

Flow: master, 5.x, 4.x, 3.x, 2.x

You can get this information by running `composer show`.

**Comment by kdambekalns** [comment]
This affects only very specific OpenSSL versions, but since the fix is easy, why not add it. 2.x is out of service, though.

**Comment by kaystrobach** [comment]
so you accept PRs for 3.3, 4.3, 5.3 and master?

**Comment by kdambekalns** [comment]
Just one for 3.3, upmerges will do the rest.

**Comment by kdambekalns** [comment]
I am running the tests for the needed change currently…

**Comment by kaystrobach** [comment]
thank you for taking care.

**Comment by kdambekalns** [comment]
Question: does decryption of data encrypted without the flag work with the flag added?

**Comment by kaystrobach** [comment]
good question, have not checked that.

* https://github.com/thephpleague/oauth2-server/issues/479
* https://paragonie.com/blog/2016/12/everything-you-know-about-public-key-encryption-in-php-is-wrong

**Comment by kaystrobach** [comment]
But it seems to work from the description.

**Comment by kdambekalns** [comment]
No, it doesn't. Which means we cannot change the default at will. A setting it is…

**Comment by albe** [comment]
Too bad :( Thanks for taking care Karsten! Now we also need to somehow provide people with a good measure on how to migrate from the old default to a more secure setting... see my comment on your commit for a possible idea
