### ISSUE TITLE
libxml is missing in composer.json

### ISSUE THREAD

**Issue by kaystrobach** [neos/flow-development-collection#1604]
### Description

composer.json should declare all dependencies to php extensions

### Steps to Reproduce

1. \Neos\Flow\I18n\AbstractXmlParser needs libxml

#### Expected behavior

* composer.json specifies, that libxml is needed

#### Actual behavior

* not specified

### Affected Versions

Flow: 3.x, 4.x, 5.x, master

**Comment by albe** [comment]
Duplicates #1356 - fixed for 4.3.16+ as of https://github.com/neos/flow-development-collection/commit/6f18fa50794af5a7f38927ca546e9bb8ba03c285#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
