### ISSUE TITLE
Don't store sessionless tokens in the session

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#1666]
### Description

Upon shutdown Flow stores all active authentication tokens in the session currently.
This includes tokens that implement the `SessionlessTokenInterface` - but those should be excluded of course as they have to be re-created/-authenticated for each request.

### Steps to Reproduce

1. Configure a [sessionless authentication](https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Security.html#sessionless-authentication-tokens)
2. Authenticate

#### Expected behavior

If a session was started for some reason (for example due to #1614) it should not contain the serialized tokens that implement `SessionlessTokenInterface`

#### Actual behavior

The session contains all active tokens

### Affected Versions

Flow:

2.1+

**Comment by albe** [comment]
See #1662 and #1663

**Comment by albe** [comment]
Fixed for 4.3+ with the above PRs. Closing :)

**Comment by bwaidelich** [comment]
Awesome, thanks for taking care!
