### ISSUE TITLE
Class Doctrine\Common\Persistence\ObjectManager does not exist

### ISSUE THREAD

**Issue by daniellienert** [neos/flow-development-collection#1728]
### Description

On current master is seems not possible to get the doctrine objectmanager injected. You get:

```
The object "Doctrine\Common\Persistence\ObjectManager" which was specified as a property in the object configuration of object "Flowpack\JobQueue\Doctrine\Queue\DoctrineQueue" (automatically registered class) does not exist.
```

### Steps to Reproduce

On a fresh installed flow-development-collection
Change `"neos/flow-development-collection": "dev-master as 6.0",` in your composer.json
Do a `composer require flowpack/jobqueue-doctrine dev-master`
Run `./flow`

Flow: dev-master

**Comment by daniellienert** [comment]
What I checked so far:
- The Interface exists, namespace is correct
- Injecting a concrete implementation instead of the interface does not work
- Set a dependency to doctrine in flowpack/jobqueue-doctrine doesn't help

**Comment by albe** [comment]
See https://github.com/neos/flow-development-collection/pull/1551

You need to inject `\Doctrine\ORM\EntityManagerInterface` instead.
