### ISSUE TITLE
ServerRequestFactory claims unknown version

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#1783]
### Description

Why not use the version we emit as header as well? And why the typo?

https://github.com/neos/flow-development-collection/blob/d843b83633e956c326451bbd40bda79ae58dc917/Neos.Http.Factories/Classes/ServerRequestFactory.php#L46

### Affected Versions

Flow: 6.0.0

**Comment by kdambekalns** [comment]
`PoweredByComponent::prepareApplicationToken` could be useful here…

**Comment by albe** [comment]
Regarding the questions:
- because we can't inject the header version easily as a default argument value ;)
- because happens

I'd suggest just using `'Flow/' . FLOW_VERSION_BRANCH` as default in the constructor if the given userAgent is empty

**Comment by kdambekalns** [comment]
Regarding the default… we had that long discussion about "information disclosure" that lead to `PoweredByComponent::prepareApplicationToken` coming into existence… 🤷‍♂️

**Comment by albe** [comment]
Yes, but that was for outgoing responses on every single request, hence disclosure. This is for *incoming* Requests, so only really used in functional tests probably

**Comment by kdambekalns** [comment]
Ok, well… I saw that in connection with code that creates a request to send to a 3rd party service.
