### ISSUE TITLE
FlashMessages are not displayed with redirect

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#1807]
## Description

When I `$this->addFlashMessage('foo');` and then `$this->redirect('otherAction');` in Flow 6, there is no flash message anymore.

Apparently, redirecting and setting a cookie at the same time, is buggy at least in Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=150066
And hard to reproduce in a way that the Chromium team can fix it:
https://bugs.chromium.org/p/chromium/issues/detail?id=696204#c72 

Technically, that was possible to happen before, so probably we just changed semantics on when a session is started and hence setting a flash message is the first place much more often.

Changing the FlashMessage storage to `SessionStorage` instead of `CookieStorage` doesn't really solve the issue according to feedback.

What we need is more information on the environments where this happens, if it happens every time independent of http/https or has some conditions.

### Affected Versions

Flow: 6.0

**Comment by bwaidelich** [comment]
I doubt that this happens due to a browser bug.
I just tested the following script Chrome and it worked for me:
```php
<?php
$flashMessage = $_COOKIE['flashmessage'] ?? null;
if ($flashMessage === null) {
    setcookie('flashmessage', 'Some Flash Message');
    header('Location: http://localhost:8000', true, 303);
    exit;
}
echo $flashMessage;
```

It would be helpful to see what headers are actually sent with the redirected response

**Comment by albe** [comment]
Yeah, that fits with the assessment of the chrome dev, that it is not easily reproducible. And pretty sure something in Flow 6 causes this to occur out of a sudden.

**Comment by albe** [comment]
After some digging thanks to Mark Kuiphuis, there are two issues at play:
- the flash message http component is not configured by default (the configuration got lost in rebasing)
- the cookie storage (which is default right now) for some reason voids the session cookie, so it only works if the component comes 'before setSessionCookie', which is not intended

I will take care and provide a bugfix PR that:
- adds the missing component configuration
- sets the default flash message storage to `SessionStorage`, which is closer to previous behaviour - we can switch the default back in a later Flow version when cookie storage edge cases have been cleaned up

**Comment by albe** [comment]
Closing as of #1811

**Comment by SC-cmarquardt** [comment]
Hi @albe ,

for me your fix does not solve the problem.
If I redirect during login or logout all flash messages are lost.
Have you any idea how to debug / backtrace this issue?

Kind regards,
Christopher

**Comment by albe** [comment]
Sorry to hear, I really hoped this was "solved", but seems it isn't :( We also have a similar issue and maybe (just maybe) this is somehow related:
https://discuss.neos.io/t/flash-message-doesnt-get-rendered-in-plugin/4796

Unfortunately, this is yet to be uncovered on what the issue really is. My suggestion to further investigate is:
- verify that the `Set-Cookie` header is sent with the redirect and a matching `Cookie` header is sent with the following request
- if it is missing in the request, this must be the Chrome bug above (I doubt it is)
- if it is sent, hook into the FlashMessageContainer `flush` method and check if it is invoked more than once (and possibly from where, i.e. check stack trace) - it's the only place where those flash messages get removed (unless the session/cookie just isn't reconstituted correctly)

**Comment by SC-cmarquardt** [comment]
Hi @albe,

if I have a logged-in user everything works fine. Problem exists if I try to write a FlashMessage on logout or on authentication error and perform a redirect.
In these situations I don't see a cookie header.

**Comment by astehlik** [comment]
Hi there. 

I stumbled over this issue today as well.

As far as I can see the problem occurs when you do not have an active session and try to use the flash messenger.

The HTTP chain is configured to first execute `Neos\Flow\Session\Http\SessionResponseComponent` and after that `Neos\Flow\Mvc\FlashMessage\FlashMessageComponent`.

The `SessionResponseComponent` checks if a session is started (which is not the case yet). After that the flash messenger stores its messages in the session but it is too late. No session will be started now.

IMO the order of the HTTP components needs to be switched around. First the flash messenger needs to store the messages, then the session component needs to check if the session was started.

This is what I put in my Settings.yaml as a workaround (that seems to work):

```yaml
Neos:
  Flow:
    http:
      chain:
        'postprocess':
          chain:
            'flashMessages':
              # Replace "after" with "before" to make sure flash messages get persisted in the session.
              position: 'before setSessionCookie'

```

**Comment by albe** [comment]
OMG, you'd think that's as obvious as it gets and we totally missed this all the time! Thanks so much!
That *could* also explain why the issue occurs most of the time together with a logout - the session is destroyed and the flash message component would start a new one, but the cookie for the new session is never sent. Hence the flashMessages aren't restored on the following request.

I'll provide a fix PR and would like to have some confirmation then.

**Comment by albe** [comment]
The fix is in the latest Flow release: https://discuss.neos.io/t/flow-bugfix-releases-5-3-16-6-0-13-6-1-7-6-2-2/5045
So 6.0.13, 6.1.7 and 6.2.2 should be okay now.
Let me know if this can be closed or if there are still some issues.

**Comment by albe** [comment]
Closing this for the time being. If anything in this regard comes up once again, you know - reopen this and we'll take yet another look. 🤞
