### ISSUE TITLE
SessionId gets renewed if SessionlessToken is authenticated

### ISSUE THREAD

**Issue by fcool** [neos/flow-development-collection#1815]
### Description

After the refactoring of #1407 not all tokens are stored in the SecurityContext, but in the Session. But only those, which do not implement SessionlessTokenInterface (which had been stored in the session before, if a session had been started).
As the tokens are not longer persisted, the provider has no chance, but to authenticate the token with every request (which sounds fine and expectable for me).
But if a session is started, the authentication of a session less token leads to renewal of the session id. Now in every request - which leads to rough times for concurrent requests.

I see two possible solutions: Store the token in the session as before, if a session exists anyway, or to change the renewal not to trigger for session less tokens, which is probably "nicer"

### Steps to Reproduce

1. Do something to get a session startet
2. Authenticate with a sessionless token `UsernamePasswordHttpBasic` for example
3. Observe the session id and recognize its changing with each request.

### Affected Versions

Flow: >= 5.2.0

**Comment by fcool** [comment]
A possible solution could be #1816

**Comment by sorenmalling** [comment]
@fcool 

The change in #1816 was merged - is this ticket still relevant, or solved by that merge?

**Comment by fcool** [comment]
This therefore officially solved!
