### ISSUE TITLE
Allow registering configuration processing types 

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#1824]
### Description

As of now, the Configuration processing types are hardcoded into the `ConfigurationManager`. This is great as of now. This task/feature is about creating the possibility to register processing types via `Package.php` in the same was we can register a new Configuration type (ex. `Views` from Neos.Flow)

### What is possible today

Inside `Package.php` of a package, we can register a new configuration type

```
$configurationManager->registerConfigurationType('Policy');
```

The second parameter allows for setting a `$configurationProcessingType`. These are limited to pre-defined processing types inside the `loadConfiguration` method of ConfigurationManager.

### What we could do

To be able to introduce other configuration types and processingTypes or for separating ex. `Policy.yaml` handling to it's own Security package, we could introduce a API that would allow for

```
$configurationProcessingType = 'PolicyProcessing'; # To keep the current naming of the processing
$configurationManager->registerConfigurationProcessingType($configurationProcessingType, [a somehow implementation]);
```

The **[a somehow implementation]** would be based on a `ConfigurationProcessing` interface with a `process` method.

and then we can use the second parameter of `registerConfigurationType()` like so

```
$configurationManager->registerConfigurationType('Policy', 'PolicyProcessing');
```

#### Actual behavior

Today it's not possible to extend the configuration processing types to more that the current

### Affected Versions

Flow: All

**Comment by mhsdesign** [comment]
Hi ;) Has this been added via: https://github.com/neos/flow-development-collection/pull/2449 ?

**Comment by bwaidelich** [comment]
> Hi ;) Has this been added via: https://github.com/neos/flow-development-collection/pull/2449 ?

yes
