### ISSUE TITLE
Generation of URIs via f:uri.action in CLI context generate broken links since Flow 5

### ISSUE THREAD

**Issue by c-krause** [neos/flow-development-collection#1848]
### Description

Since Flow 5.x URLs generated in CLI context via ActionViewHelper are broken.

<f:uri.action action="action" package="Acme.Acme" controller="Controller" absolute="1" arguments="{parameter: 1}"/>

Flow 4.x example: http://some.domain.de/controller/action/parameter/1
Flow <= 5.3.8 example: http://some.domain.de/./controller/action/parameter/1
Flow 5.3.8 example: http://some.domain.de./controller/action/parameter/1

### Steps to Reproduce

1. Create a CommandController with an action that creates a file from a template (like an XML file)
2. Create the template with a f:uri.action call to an action
3. Create the XML file by calling the command.
4. The created file contains a broken link.

#### Expected behavior

A correct URL should have been rendered by the ViewHelper (http://some.domain.de/controller/action/parameter/1).

#### Actual behavior

Since Flow >= 5.0 and <= 5.3.8 technical working but wrong URLs are generated (http://some.domain.de/./controller/action/parameter/1)
Since Flow 5.3.8 the generated URLs are not working at all (http://some.domain.de./controller/action/parameter/1).

### Affected Versions

Flow >= 5.0: wrong but working URLs
Flow 5.3.8: broken URLs

**Comment by ComiR** [comment]
https://github.com/ComiR/flow-development-collection/commit/df7d2b6cd1db2d75c2d96274a6f562c8ed0914b4 fixes this for Flow >=5.1.

The lowest supported version as of now is 4.3, where it apparently does work, but here would be the patch for the versions <5.1: https://github.com/ComiR/flow-development-collection/commit/7a25f255c6b66bcb1e846c0990ae81a97c5b8e69.

I did not test it further and I am not sure for which version to create a PR in this case.

**Comment by kitsunet** [comment]
generally this needs to be fixed in the 5.0 branch, but we first need conclusive functional tests for all edge cases because we had to revert one fix recently that broke another case, so I am not taking any risks here anymore. First a round of tests exposing all possible faulty behavior, then the fix.

**Comment by kitsunet** [comment]
See also https://github.com/neos/flow-development-collection/pull/1841
and semi related: https://github.com/neos/flow-development-collection/pull/1845

**Comment by kitsunet** [comment]
After discussion in Slack I hear that ServerRequests are created from globals, that makes no sense on CLI as the globals on CLI are not sensible for a ServerRequest!
Using `Neos\Http\Factories\ServerRequestFactory` to generate a ServerRequest to use might already fix this problem.

**Comment by kitsunet** [comment]
Note as for Flow 5 (and not 6) the problem seems to be different and mostly based in the fact that SCRIPT_NAME contains some relative path on CLI and we don'T overwrite it if you create a StandaloneView. I guess this is nothing we really want/can fix without a behavior fix at this point. Things look different in Flow 6 anyway and make it easier to create a "good" fake request for such cases.

**Comment by kitsunet** [comment]
Roughly how it should work fine in Flow pre 6.x:

```
// $baseUriString could come from configuration for example -> Neos.Flow.http.baseUri
$request = Request::create(new Uri($baseUriString));
$actionRequest = new ActionRequest($request);
$view = new StandaloneView($actionRequest);
```

**Comment by bwaidelich** [comment]
FYI: Linking from the CLI is indeed broken since Flow 6, see #2084
