### ISSUE TITLE
originallySubmittedResource doesn't work anymore

### ISSUE THREAD

**Issue by ComiR** [neos/flow-development-collection#1857]
If you have a `<f:form.upload/>` with a value (either explicitly set via value attribute, form object property or due to failed validation - i.e. the originallySubmittedResource is set) and submit the form without selecting another file, the resource won't get mapped to the resulting request argument.

I'm assuming this is because `\GuzzleHttp\Psr7\ServerRequest` doesn't use `\Neos\Http\Factories\FlowUploadedFile` but `\GuzzleHttp\Psr7\UploadedFile` which doesn't know about any originally submitted resource.

Problem occured with Flow 6.0.5.

**Comment by kitsunet** [comment]
There is an upcast happening in `\Neos\Flow\Mvc\ActionRequestFactory::mergeHttpRequestArguments`

**Comment by albe** [comment]
Should be fixed as of Flow 6.1.4 + 6.0.10
