### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#1866]
PHP 7.4 will be released soon and we should make sure at least Flow 6.1 supports it

**Comment by kdambekalns** [comment]
@albe I am trying PHP 6.4 with Flow 5.3 now…

**Comment by kdambekalns** [comment]
Ok, one more dependency we have that is not ready: https://github.com/Behat/Transliterator/pull/29

**Comment by kdambekalns** [comment]
I directly pushed some further changes to `.travis.yml` in Flow, switching to Ubuntu Bionic and stable PHP 7.4 as well as PostgreSQL 9.5 (instead of 9.4).

**Comment by kdambekalns** [comment]
The same adjustments are in the Neos PR now…

**Comment by kdambekalns** [comment]
The PR to `behat/transliterator` was merged some minutes ago…

**Comment by kdambekalns** [comment]
Everything merged, all builds green, release jobs are running. Finally.

**Comment by jonnitto** [comment]
So we could close this issue, right?
