### ISSUE TITLE
PdoBackend: Replacing authenticated accounts should be atomic

### ISSUE THREAD

**Issue by rolandschuetz** [neos/flow-development-collection#1874]
### Description

The Neos.UI backend creates a lot of parallel requests for assets property to load previews. Now I’m using the PdoBackend for storing session data.

The request executed Session_Original::storeAuthenticatedAccountsInfo() which executed PdoBackend::set, which then does:

```
$this->remove($entryIdentifier);

...
$statementHandle = $this->databaseHandle->prepare('INSERT INTO "' ...
```
See https://github.com/neos/flow-development-collection/blob/master/Neos.Cache/Classes/Backend/PdoBackend.php#L161

This allows race conditions and causes an exception `Integrity constraint violation: 1062 Duplicate entry `. The current master already introduced a transaction, but I believe the removal should be part of the transaction.

#### Expected behavior

Multiple parallel requests with a valid session all return correct responses.

#### Actual behavior

The ones with race condition errors return 500.

### Affected Versions

Neos: 4.3.3
Flow: 5.3.2

**Comment by kdambekalns** [comment]
The problem is, that `remove(…)` does a transaction as well, nesting transactions is not supported / something you want. So `set(…)` would need to remove the data within the same transaction.

**Comment by Tomen** [comment]
How about adding an internal method that roughly does this:

```
private function _remove(string $entryIdentifier)
{
    $statementHandle = $this->databaseHandle->prepare('DELETE FROM "tags" WHERE "identifier"=? AND "context"=? AND "cache"=?');
    $statementHandle->execute([$entryIdentifier, $this->context(), $this->cacheIdentifier]);
    $statementHandle = $this->databaseHandle->prepare('DELETE FROM "cache" WHERE "identifier"=? AND "context"=? AND "cache"=?');
    $statementHandle->execute([$entryIdentifier, $this->context(), $this->cacheIdentifier]);
}

```

This code could then be called by `remove()` which handles the transaction as well as `set()` or other methods.

**Comment by rolandschuetz** [comment]
If there are no side-effects I'm not aware the problem can easily be fixed. Looking at other backend implementations, it seems AOP is not a concern.

**Comment by kdambekalns** [comment]
> How about adding an internal method

Yes, obviously… I simply wanted to note that down for anyonw who wants to tackle this. Might be me, but not today anymore, so… ;)
