### ISSUE TITLE
CurlEngine / CURLOPT_HTTPHEADER

### ISSUE THREAD

**Issue by Inchie** [neos/flow-development-collection#1886]
At the moment it is possible to use the request engine to set some additional options
('Neos\Flow\Http\Client\CurlEngine'). 

```
$curlHttpHeader = [
    'Accept: application/json',
    'Authorization: Secret 56-78-89',
    'Cache-Control: no-cache'
];

$this->requestEngine->setOption(CURLOPT_HTTPHEADER, $curlHttpHeader);
```

This  additional options will be never part of the request. The options will be overwritten 
in the line 68 or 131.

`curl_setopt($curlHandle, CURLOPT_HTTPHEADER, ['Expect:']); // Line 68` 

`curl_setopt($curlHandle, CURLOPT_HTTPHEADER, $preparedHeaders); // Line 131` 

Perhaps it is better to throw an Exception if somebody use them.

**Comment by dlubitz** [comment]
Isn't it kind of intended, that the headers are not set as an option, as you set it in the request?

https://github.com/neos/flow-development-collection/blob/f49760f410a8ee959b65b6ad36c42125c782f19e/Neos.Flow/Classes/Http/Client/CurlEngine.php#L113-L118

Other topic is the `Excpect:` HTTP Header. As it gets overridden by the prepared headers, it is never sent.
https://github.com/neos/flow-development-collection/blob/f49760f410a8ee959b65b6ad36c42125c782f19e/Neos.Flow/Classes/Http/Client/CurlEngine.php#L71
https://github.com/neos/flow-development-collection/blob/f49760f410a8ee959b65b6ad36c42125c782f19e/Neos.Flow/Classes/Http/Client/CurlEngine.php#L118

**Comment by sorenmalling** [comment]
> Isn't it kind of intended, that the headers are not set as an option, as you set it in the request?

It could seem like it  - so throwing a helpful exception would be good for helping those using the option, and expecting they will be there 👍

**Comment by sorenmalling** [comment]
And let's note that `setOption` is not a part of the RequestEngine interface - so it's very CurlEngine specfici :)
