### ISSUE TITLE
Fluid: Set view variables via signal/configuration

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#1902]
### Description

Similar to `{settings}` (set via processRequest in ActionController) I will like to open a discussion about how we could make it possible to add global variables to the view. A usecase could be as follows (and is in my current case):

 * Add the authenticated account to the view to have it available.

It can be done with a abstractcontroller and the initializeView method. Downside is, the creation of dependency and required inheritance of a single controller inside the code.

I suggest a `emitViewResolved` signal/slot inside the ActionController method, that pass the view object and give the possibility to work with the view.

Please bring feedback and ideas to this issue for a good and solid solution and descission :-)

**Comment by albe** [comment]
I do like the concept of just adding a signal that emits resolved views. Seems simple and low-level enough, but makes sense on a broader perspective than e.g. directly adding variables via settings.
