### ISSUE TITLE
While kickstarting a new package: Trying to access array offset on value of type null in PackageManager

### ISSUE THREAD

**Issue by radmiraal** [neos/flow-development-collection#1981]
### Description

When I kickstart a new package using the kickstarter it fails.

### Steps to Reproduce

1. Clean Flow development distro with collection on master
2. Run ./flow package:create --package-key Foo.Bar

#### Expected behavior

The notification the package is created

#### Actual behavior

Notice: Trying to access array offset on value of type null in /.../Packages/Framework/Neos.Flow/Classes/Package/PackageManager.php line 373

  Type: Neos\Flow\Error\Exception
  Code: 1
  File: Packages/Framework/Neos.Flow/Classes/Error/ErrorHandler.php
  Line: 81

### Affected Versions

Flow: 6.0, 6.1, 6.2 and master

I tried to find what happens, it seems like the PackageManager instance which is injected using \Neos\Flow\Command\PackageCommandController::injectPackageManager has $settings with value NULL.

**Comment by sorenmalling** [comment]
I can confirm this behavior on master. 

Even by changing the way settings are injected (move to InjectConfiguration annotation) did not change $this->settings from being NULL

**Comment by radmiraal** [comment]
in the meantime we tracked it down to the fact injectSettings has to be called manually during flow bootstrap as the packagemanager is excluded from reflection.

The removal of the injection is caused by https://github.com/neos/flow-development-collection/commit/b71e1924e423b73814b09552d34291002e4a18f1

**Comment by sorenmalling** [comment]
Awesome catch! 👍

**Comment by kitsunet** [comment]
🙈  I am sorry, that line went into he change by mistake... OBviously needs to be put back.
