### ISSUE TITLE
ReadTheDocs edit link leads to readonly repo

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2017]
See https://github.com/neos/flow-development-collection/pull/2016#pullrequestreview-419179322

Can we somehow fix this? Change RTD to pull from this collection repo instead?

**Comment by albe** [comment]
See https://github.com/neos/flow-development-collection/pull/2016#issuecomment-634645407
There is a setting apparently: 
```
html_context = {
    'source_url_prefix': "https://gitlab.com/anarcat/foo/blob/HEAD/doc/",
}
# this is the default....
```

**Comment by kdambekalns** [comment]
Uh! That's interesting! According to the link in that link this should help:

```
html_context = {
    'source_url_prefix': "https://gitlab.com/anarcat/foo/blob/HEAD/doc/",
}
# this is the default....
# html_show_sourcelink = True
```

**Comment by kdambekalns** [comment]
If this works "for real" (I tested it locally), I'll adjust the remaining branches and the Neos configuration as well. We'll know tomorrow. 🙂

**Comment by kdambekalns** [comment]
For the record:
```
# Configure links to view/edit source to point to development collection
html_context = {
    'source_url_prefix': 'https://github.com/neos/flow-development-collection/blob/5.3/Neos.Flow/Documentation/',
    'github_user': 'neos',
    'github_repo': 'flow-development-collection',
    'github_version': '5.3',
    'conf_py_path': '/Neos.Flow/Documentation/',
}
```

**Comment by kdambekalns** [comment]
Note: `source_url_prefix` is not used if the edit link is shown, it can go away.

That being said, this is how it works. Locally for me, and for hundreds of others using the theme but apparently not rendering it on RTD.

Yes, it's in the code (https://github.com/readthedocs/sphinx_rtd_theme/blob/fd83875eefbf1f99d7b6576bacb7d61ae2ac23bc/sphinx_rtd_theme/breadcrumbs.html#L47) – but the documentation only mentions `github_url` (https://github.com/readthedocs/sphinx_rtd_theme/blob/c04c214a8591a0290f30026b89bf3215fb1061b4/docs/configuring.rst#file-wide-metadata). 🤔 That setting forces a single URL, not really helpful.

I'll try again with the variables set as "file-wide metadata" – if that doesn't work, I'd guess RTD overrides those values. Then the next try would indeed be `github_url`…

**Comment by kdambekalns** [comment]
@albe So it does work, after all… but you upmerged without adjusting the `github_version` for each branch! That was something I had planned, so the matching version is edited when someone follows that link…

**Comment by albe** [comment]
Quickly fixed it in all branches 6.0+ - we need to remember adjusting this when branching off, so should probably go into our "release documentation" (I'm definitely the first one that would forget that 😆)

**Comment by albe** [comment]
But wait, the changelog from the release tags yesterday isn't rendered yet?
https://flowframework.readthedocs.io/en/5.3/TheDefinitiveGuide/PartV/ChangeLogs/5318.html

**Comment by kdambekalns** [comment]
Now it is, and https://flowframework.readthedocs.io/en/5.3/TheDefinitiveGuide/PartV/ChangeLogs/5318.html points to https://github.com/neos/flow/blob/5.3/Documentation/TheDefinitiveGuide/PartV/ChangeLogs/5318.rst for the "Edit on GitHub" link… 🤬

**Comment by albe** [comment]
yep... 😢

**Comment by albe** [comment]
Coming back to this, did we actually have rerenders with the `html_context {}` and checked those? Because according to https://github.com/readthedocs/sphinx_rtd_theme/issues/465#issuecomment-521272830 that should work.

Alternatively adding `:github_url: https://github.com/...` to every doc should also lead to the wanted effect?

**Comment by kdambekalns** [comment]
Finally done by now…
