### ISSUE TITLE
AjaxWidgetComponent breaks with ActionController's response handling

### ISSUE THREAD

**Issue by fcool** [neos/flow-development-collection#2027]
# Description

The AjaxWidgetComponent dispatches WidgetControllers, which itself are ActionControllers. ActionControllers rely in their `renderView` method on being able to replace the response, if a response had been returned from the view. 
But as the AjaxWidgetComponent cancels the HTTPChain the component originally responsible for replacement never is called.

### Steps to Reproduce

1. Use a custom view in a controller inheriting from `AbstractWidgetController`
2. Return a PSR-7 response

#### Expected behavior

The PSR-7 Response should be handled as in other ActionControllers

#### Actual behavior

An empty Response is returned

### Affected Versions

Flow: 6.0 and later

**Comment by sorenmalling** [comment]
As the PR has been merged, I close this issue :) 

Thank you @fcool 👍
