### ISSUE TITLE
PdoBackend::setup() will throw exception if tables exist already

### ISSUE THREAD

**Issue by nlx-lars** [neos/flow-development-collection#2039]
# Description

When running either `./flow cache:setupall` while having more than one PdoBackend configured with the same dataSourceName or `./flow cache:setup` against a PdoBackend whose tables already exist, an exception is thrown.

### Steps to Reproduce

1. Configure Cache with PdoBackend
2. Run `./flow cache:setupall`
3. Run `./flow cache:setupall` again

#### Expected behavior

The second `cache:setup` or `cache:setupall` command should have 0 as exit code and maybe a notice that the tables exist already.

#### Actual behavior

The PdoBackend tries to create the cache tables twice, leading to an error. This is problematic when using `cache:setupall` in a deployment process.

### Affected Versions

Neos: 4.2+

Flow: 5.2+

**Comment by nlx-lars** [comment]
@bwaidelich, @albe and @kitsunet what do you think about this?

The PdoBackend has a `tableExists` method that could be used to determine if tables have to be created in the setup. If the do already exist, a Notice could be added to the Result.

**Comment by bwaidelich** [comment]
Thanks for the input. In a previous version I used the schema manager to get the tables in sync with the SQL, but that was reverted because it introduced a new dependency. Checking if the table exists at all seems sensible to me

**Comment by nlx-lars** [comment]
@bwaidelich nice, I'll submit a PR then! 👍
