### ISSUE TITLE
Add Notice to Signals and Slots Docs to use ::class and beware of common file mistake

### ISSUE THREAD

**Issue by filipppp** [neos/flow-development-collection#2061]
### Description

New developers could interpret the documentation regarding Signals and Slots (https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/SignalsAndSlots.html) wrong and use the file path to the class instead of the Namespace. 

### Resolution
We should update the example to use `ClassName::class `instead of a String containting the namespace since this is considered best practice. This would also eliminate the misinterpretation of the docs.

**Comment by bwaidelich** [comment]
While we're on it we should also add a big notice about the method name that has to be prefixed with `emit` but referenced without the prefix

**Comment by bwaidelich** [comment]
Related: #1003
