### ISSUE TITLE
Unused MD5 in ResourceMetaDataInterface

### ISSUE THREAD

**Issue by rkrahnen** [neos/flow-development-collection#2112]
The `ResourceMetaDataInterface` contains two content hashes, a SHA1 and a MD5. While the SHA1 is used for the whole resource management, the MD5 is used only once when creating a `StorageObject` for a `PersistentResource`, so only for copying it without any further usage.

In my opinion the MD5 should be marked as deprecated in Flow 6.3 and removed in Flow 7.0.

**Comment by sorenmalling** [comment]
@rkrahnen Where in the code have you found the md5 methods/property being used?

Can you try and remove them and run the tests to see if any errors occures?

**Comment by rkrahnen** [comment]
There are three places where `setMd5` is used:
1. \Neos\Flow\ResourceManagement\Storage\FileSystemStorage::getObjectsByCollection
2. \Neos\Flow\ResourceManagement\Storage\PackageStorage::createStorageObject
3. \Neos\Flow\ResourceManagement\Storage\WritableFileSystemStorage::importTemporaryFile

The second and third usage both set a new value by using `md5_file()`, whereas the first usage is the one mentioned in my first comment and is the only place where `getMd5` is used.

So for me it seems like it is set but never used (ignoring the copying one).

Sadly I am currently not able to run the tests, sorry.

**Comment by sorenmalling** [comment]
Try and remove the usage and commit a PR - then the tests will automatically run 👍

**Comment by rkrahnen** [comment]
Hopefully I did it right: https://github.com/neos/flow-development-collection/pull/2113
