### ISSUE TITLE
Update doctrine dependencies

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2122]
doctrine/common and doctrine/migrations are due for an update for some time. Doctrine/common is even supposed to be phased out (https://www.doctrine-project.org/2018/07/12/common-2-9-and-dbal-2-8-and-orm-2-6-2.html). Doctrine/orm is still okay with 2.7, but 2.8.x is in the making.
see #1880, #2026 & #2021

**Comment by kdambekalns** [comment]
I'd love to tackle this (at least partly), after all #1880 has been there for… uhm… ages. 😬

**Comment by kdambekalns** [comment]
On `doctrine/common`:

```
$ composer why doctrine/common
doctrine/orm                      2.7.4        requires  doctrine/common (^2.11 || ^3.0)
gedmo/doctrine-extensions         v2.4.42      requires  doctrine/common (~2.4)
neos/flow-development-collection  9999999-dev  requires  doctrine/common (^2.4)
neos/neos-development-collection  9999999-dev  requires  doctrine/common (^2.7)
```

If we update `gedmo/doctrine-extensions` to 3.0.0, we could use `doctrine/common` as `^3.0` - the changes seem reasonable: https://github.com/Atlantic18/DoctrineExtensions/releases/tag/v3.0.0

**Comment by albe** [comment]
We have a dependency on gedmo/doctrine-extensions? 🤯

**Comment by kdambekalns** [comment]
Neos, not Flow: https://github.com/neos/neos-development-collection/search?q=gedmo%2Fdoctrine-extensions

**Comment by kdambekalns** [comment]
Timestamps in NodeData: https://github.com/neos/neos-development-collection/search?q=Gedmo

**Comment by albe** [comment]
Ah, okay!

**Comment by kdambekalns** [comment]
- `doctrine/dbal` runs with PHP8 as of 2.12.0: https://github.com/doctrine/dbal/pull/4347
- `doctrine/orm` is on the way: https://github.com/doctrine/orm/pull/8303

**Comment by kdambekalns** [comment]
No so fast, GH automation!

**Comment by albe** [comment]
Only #2247 left and this can be closed 🎉

**Comment by markusguenther** [comment]
As all PRs are merged I will close this issue :)
