### ISSUE TITLE
Make ValueObjects embedded by default

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2123]
Embedded value objects are the preferred storage method for all value objects, since it better reflects true value object semantics.

TBD:
- Is this really viable? (I think so)
- Should we provide a code migration that flips all ValueObjects that are not explicitly embedded=false in order to increase b/c?

See https://github.com/neos/flow-development-collection/pull/1718

**Comment by sorenmalling** [comment]
> Is this really viable? (I think so)

Agreed - the none-embedded concept and Flow implementation have held me from learning about and use ValueObject in general in Flow.

> Should we provide a code migration that flips all ValueObjects that are not explicitly embedded=false in order to increase b/c?

Good idea - it will be a great migration path. Can you provide such code migration?

**Comment by bwaidelich** [comment]
To be honest: I'm not sure if it's worth a breaking change just change the default behavior rather than providing some good documentation about it.
If we really go this route, we should definitely add a core migration

**Comment by albe** [comment]
That migration is already in the PR :) It's super straightforward, just turning `@Flow\ValueObject` into `@Flow\ValueObject(embedded=false)`. Hence it's only breaking if not running the code migration

**Comment by bwaidelich** [comment]
awesome! sorry, I didn't even check
