### ISSUE TITLE
Composer removed package are kept in Packages/Application and kept active for Flow's autoloading

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#2135]
### Description

Running `composer remove vendor/package` removes the package from composer.json and composer.lock (and autoloaded stuff).
But the packages is kept in `Packages/Application` unless you remove it yourself.
If this folder contains a `Configuration/Settings.yaml`, that include routes, these routes are still displayed when running `./flow routing:list`.

@bwaidelich  adds: Even after running `./flow flow:package:rescan`. It’s about time that we get rid of our custom autoloading magic

### Steps to Reproduce

1. Create package with Configurations/Settings.yaml including Routes
2. Confirn with ./flow routing:list that your routes are present
3. use composer remove to remove your package
3.a. package is removed - bust still present in Packages/Application
4. Run ./flow routing:list and find your routes are still present

#### Expected behavior

The Flow package you remove, should be considered removed and inactive and shuld not live in Packages/Application or be loaded

#### Actual behavior

The package is stated as active due to it's location and therefore loaded

### Affected Versions

Flow:
master

**Comment by sorenmalling** [comment]
Found the following code from composer PathDownloader::remove (https://github.com/composer/composer/blob/master/src/Composer/Downloader/PathDownloader.php#L179) 

![image](https://user-images.githubusercontent.com/531918/93745363-b1fd1780-fbf3-11ea-9b3b-6dd2b268e49e.png)


So this could be a issue with using symlinks from DistributionPackages, that causes removed package to stay there

**Comment by kdambekalns** [comment]
Tried that with Flow dev-master and Composer 2.1.3:

```
$ composer2 require flownative/flow-doubleoptin
…

$ ls -l Packages/Application
drwxr-xr-x+ 9 karsten  staff   288 May  8  2020 Flownative.DoubleOptIn
drwxr-xr-x+ 9 karsten  staff   288 Jul 27 11:51 Neos.Behat
drwxr-xr-x+ 9 karsten  staff   288 Dec  8  2020 Neos.Welcome

$ composer2 remove flownative/flow-doubleoptin
…

$ ls -l Packages/Application
drwxr-xr-x+ 9 karsten  staff   288 Jul 27 11:51 Neos.Behat
drwxr-xr-x+ 9 karsten  staff   288 Dec  8  2020 Neos.Welcome
```

Works fine. Let's use a distribution package:

```
$ composer2 require flownative/flow-doubleoptin:dev-master
…

$ ls -l Packages/Application
lrwxr-xr-x  1 karsten  staff   49 Jul 27 12:03 Flownative.DoubleOptIn -> ../../DistributionPackages/Flownative.DoubleOptIn
drwxr-xr-x+ 9 karsten  staff  288 Jul 27 11:51 Neos.Behat
drwxr-xr-x+ 9 karsten  staff  288 Dec  8  2020 Neos.Welcome

$ composer2 remove flownative/flow-doubleoptin
…
Package operations: 0 installs, 0 updates, 1 removal
  - Removing flownative/flow-doubleoptin (dev-master), source is still present in Packages/Application/Flownative.DoubleOptIn
…

$ ls -l Packages/Application
lrwxr-xr-x  1 karsten  staff   49 Jul 27 12:03 Flownative.DoubleOptIn -> ../../DistributionPackages/Flownative.DoubleOptIn
drwxr-xr-x+ 9 karsten  staff  288 Jul 27 11:51 Neos.Behat
drwxr-xr-x+ 9 karsten  staff  288 Dec  8  2020 Neos.Welcome
```

Yes, the symlink stays in place, but Composer clearly states that fact. That could be something new in Composer 2, but I conclude this is not an issue with Flow in any way. Nor do I see a way to fix this from our side. Therefore I created an issue with Composer. Let's see.
