### ISSUE TITLE
Remove neos/fluid-adaptor as hard dependency in neos/flow composer.json 

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#2151]
This is a discussion issue about removing fluid-adaptor as hard dependency of neos/flow.

neos/fluid-adaptor is added in the `require`  section of the composer.json in neos/flow

https://packagist.org/packages/neos/flow

![image](https://user-images.githubusercontent.com/531918/94900952-2b1f2900-0496-11eb-9f97-aeb7e12ca0d5.png)

I suggest that we remove the hard dependency form neos/flow.

From reading the Flow core, we have a SimpleTemplateView that implements our ViewInterface and is already registered as `defaultImplementation` in Settings path `Neos.Flow.mvc.view.defaultImplementation`

The neos/neos package can require it itself, leaving that at no chance of breaking.

**Pros**
 * Lighter Flow installation
 * Less dependency on outside packages

**Cons**
 * You have to update your package to require the fluid-adaptor package (can be done with proper documentation and upgrade notes)

Please chime in on this topic. If nothing technically stops it, what would you say to have this in for 7.0?

**Comment by albe** [comment]
Love the pros. Maybe we can keep fluid(-adaptor) in the "suggest" section though, so installing a fresh Flow will remind you to add Fluid if you want it.

**Comment by sorenmalling** [comment]
> Maybe we can keep fluid(-adaptor) in the "suggest" section though

Brilliant idea!

**Comment by albe** [comment]
Then let's do it :)

**Comment by bwaidelich** [comment]
https://github.com/neos/flow-development-collection/blob/7.0/composer.json#L34 still has a dependency to Fluid it seems

**Comment by albe** [comment]
> https://github.com/neos/flow-development-collection/blob/7.0/composer.json#L34 still has a dependency to Fluid it seems

Correct and that is still needed (and would come back from the composer merger) for the time being, because otherwise fluid wouldn't be installed in the dev-distribution setup, while fluid-adaptor would be available. That would break builds. We need to split fluid-adaptor
