### ISSUE TITLE
FEATURE: Add meta data to roles and privileges

### ISSUE THREAD

**Issue by daniellienert** [neos/flow-development-collection#2162]
When lots of roles (targeting lots of privileges) are defined, managing them and assigning them to users in the Neos backend gets quite complicated and error prone. The major issue is, that we only have the role identifier (somehow truncated) to be displayed in the backend module.

Having two additional (optional) configuration options, label and description for both configuration types would make things much clearer.

Example:

```
...
    'Neos.Neos:Backend.Service.Workspaces.Index':
      matcher: 'method(Neos\Neos\Controller\Service\WorkspacesController->(index|error|show)Action())'
      label: 'Index Workspaces'
      description: 'List workspaces in the Neos backend module'
...

...
roles:
  'Neos.Neos:LivePublisher':
    label: Neos Live Publisher'
    description: Enables the user to publish changes to the live workspace
    privileges:
...
```

The result in Neos could be something like this, when clicking on the ℹ️ icon:

![image](https://user-images.githubusercontent.com/642226/95674409-57325c80-0bb0-11eb-907c-a1b37632ef21.png)

**Comment by daniellienert** [comment]
@bwaidelich, would love to read your thoughts on this.

**Comment by bwaidelich** [comment]
I think it's a great idea without top much risk involved!

**Comment by albe** [comment]
I second that assessment by Bastian :) That makes so much sense and should be painless to implement!

**Comment by sorenmalling** [comment]
If implanted I suggest them being used/displayed in a cli context/command.

Can we make that?

**Comment by daniellienert** [comment]
Wasn't that hard. Currently struggling with the necessary css and javascript magic to display it kind of clear. (Should just have used a command controller .... 😂 ) 
![image](https://user-images.githubusercontent.com/642226/95691416-5ab0fc80-0c1f-11eb-8469-7dd3a09a8de8.png)
