### ISSUE TITLE
Make it easier to get hold of the current DBAL connection

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#2170]
Currently in order to use the "current" DBAL connection one has to inject the `EntityManager` such as:

```php
class SomeClass {

    public function injectEntityManager(EntityManagerInterface $entityManager): void
    {
        $this->dbal = $entityManager->getConnection();
    }
}
```

Instead it should be possible to inject an instance of `Doctrine\DBAL\Connection` directly.

**Comment by sorenmalling** [comment]
You are the best @bwaidelich, for taking good care of organizing PR and issues 👍
