### ISSUE TITLE
Remove classes marked as deprecated and can be removed by 7.0

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#2172]
In a large number of cases (Generic persitence for ex.) it's marked with

 `deprecated since Flow 6.0`

And in some, we have to check history, if no [version number] is mentioned :) This can require that we go through git history for that single file when in doubt, so we do not remove wrong stuff by accident :) 

Use `grep -Rin "deprecated" Neos.Flow/Classes` from the Framework folder to find for the `Neos.Flow` package, and so on with others.

**Comment by bwaidelich** [comment]
As mentioned by @Sebobo in our team meeting: We'll have to consider deprecated Fusion prototypes, too!

**Comment by sorenmalling** [comment]
> ~As mentioned by @Sebobo in our team meeting: We'll have to consider deprecated Fusion prototypes, too!~ Update: That's relevant for _Neos_ of course, not here

https://github.com/neos/fusion/search?q=deprecated

Collection of code with "deprecated" in it :)

**Comment by sorenmalling** [comment]
@bwaidelich I will go into this again in next week. Wrote to @albe about coordinating the removal of Component stuff first, so we don't end up in a conflict or anything.

**Comment by bwaidelich** [comment]
@sorenmalling Thanks for the update.
Since the middleware stuff is mostly in, I kickstarted this one with #2262 now – lets see what the CI pipeline has to say to this 6,099 removed lines ;)

**Comment by bwaidelich** [comment]
I hope we caught most deprecations with #2262
