### ISSUE TITLE
Flow Configuration is unprocessed during `shutdownObject()` lifecycle method

### ISSUE THREAD

**Issue by nlx-lars** [neos/flow-development-collection#2183]
### Description

If a setting contains variables (either environment variables with `%env:NAME%` or constants with `%NAME%`), those won't be replaced with their value during the `shutdownObject()` lifecycle method. Instead, the setting will contain the unprocessed `%env:NAME%` string, possibly leading to broken cleanup behavior.

=> This seems to only happen in the first request after a `./flow flow:cache:flush && ./flow cache:warmup`. Probably because `$cacheNeedsUpdate` is false in subsequent requests?

### Steps to Reproduce

1. Define a setting with an environment variable
```yaml
Foo:
  Bar:
    baz: '%env:SHUTDOWN_TEST%'
```
2. Create a class that uses this setting in it's `shutdownObject()` method
```php
<?php

use Neos\Flow\Annotations as Flow;

/**
 * @Flow\Scope("singleton")
 */
class FooService
{

    /**
     * @Flow\InjectConfiguration(package="Foo.Bar", path="baz")
     * @var string
     */
    protected $baz;
    
    public function initializeObject(): void
    {
        // $this->baz will contain the value of the environment variable "SHUTDOWN_TEST"
    }
    
    public function shutdownObject(): void
    {
        // $this->baz will contain the unprocessed string "%env:SHUTDOWN_TEST%"
    }
    
}
```

#### Expected behavior

The property `$baz` should contain the value of the `SHUTDOWN_TEST` environment variable.

#### Actual behavior

The property `$baz` should contains the unprocessed value (`%env:SHUTDOWN_TEST%`) of the configuration string.

### Affected Versions

Neos: NA

Flow: 5.3

### Further information
This is caused by the order in which the ConfigurationManager and ObjectManager are connected to the `bootstrapShuttingDown` Signal, see [Flow's Package.php](https://github.com/neos/flow-development-collection/blob/5.3/Neos.Flow/Classes/Package.php#L107).
First, `ConfigurationManager::shutdown()` is called which then saves the current configuration with a call to [$this-> saveConfigurationCache()](https://github.com/neos/flow-development-collection/blob/5.3/Neos.Flow/Classes/Configuration/ConfigurationManager.php#L550). That method (or the call to 
 [loadConfiguration()](https://github.com/neos/flow-development-collection/blob/5.3/Neos.Flow/Classes/Configuration/ConfigurationManager.php#L377) to be more precise) will leave the internal `$configurations` property of the ConfigurationManager in this unprocessed state.

Now, the `shutdown()` method of the ObjectManager is called which will trigger the `shutdownObject()` lifecycle method for all other objects with this broken configuration state.

I found these 2 ways to fix this problem:
1. Swap the order in which the ConfigurationManager and ObjectManager are connected to the `bootstrapShuttingDown` signal
2. Add a call to [loadConfigurationCache()](https://github.com/neos/flow-development-collection/blob/5.3/Neos.Flow/Classes/Configuration/ConfigurationManager.php#L506) after saving the configuration inside the [shutdown()](https://github.com/neos/flow-development-collection/blob/5.3/Neos.Flow/Classes/Configuration/ConfigurationManager.php#L344) method of the ConfigurationManager

Obviously the cleaner approach is 1., however on the other hand I would not expect a call to `saveConfigurationCache()` to break the current configuration.

**Comment by albe** [comment]
Thanks for the report and the thorough analysis! I agree that the order of the shutdown registrations is wrong, given that they will be called in the order they are registered. Since ObjectManagement depends on Configuration, the former needs to be "shutdown" first.
