### ISSUE TITLE
InstallerScripts is not compatible to composer 2.0

### ISSUE THREAD

**Issue by daniellienert** [neos/flow-development-collection#2187]
Relates to #2025

**Comment by ariesprodesign** [comment]
Same problem:
`> Neos\Flow\Composer\InstallerScripts::postPackageUpdateAndInstall
PHP Fatal error:  Uncaught Error: Call to undefined method Composer\DependencyResolver\Operation\UpdateOperation::getJobType() in D:\xampp\htdocs\honey-dev\Packages\Framework\Neos.Flow\Classes\Composer\InstallerScripts.php:74
`

**Comment by bwaidelich** [comment]
This can be closed, no?

**Comment by kdambekalns** [comment]
Fixed with latest release(s).
