### ISSUE TITLE
cannot build interceptor code for private method BrowserState::initializeData()

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#2190]
### Description

Updated a new Neos instance (Neos 5.3.0 and Flow 6.3.1 => 6.3.2) and ran ./flow package: rescan. Get the following error.

```
The Neos\Flow\Aop\Builder\AdvicedMethodInterceptorBuilder cannot build interceptor code for private method Neos\Media\Browser\Domain\Session\BrowserState::initializeData().
Please change the scope to at least protected or adjust the pointcut
expression in the corresponding aspect.
  Type: Neos\Flow\Aop\Exception
  Code: 1593070574
  File:
Packages/Framework/Neos.Flow/Classes/Aop/Builder/AdvicedMethodInterceptorBu
        ilder.php
  Line: 42
Open Data/Logs/Exceptions/20201029091519918cd4.txt for a full stack
trace.
  Type: Neos\Flow\Core\Booting\Exception\SubProcessException
  Code: 1355480641
  File: Packages/Framework/Neos.Flow/Classes/Core/Booting/Scripts.php
  Line: 699
Open Data/Logs/Exceptions/20201029091518caed70.txt for a full stack trace.
```

### Affected Versions

Neos: 5.3.0

Flow: 6.3.2

**Comment by kdambekalns** [comment]
It's in Flow, after all, so I moved the issue.

**Comment by bwaidelich** [comment]
..good call (both)

**Comment by albe** [comment]
> Adding some
> 
> ```
>         if (!is_callable([$className, $methodName])) {
>             return false;
>         }
> ```
> 
> there seems to do the trick but I'm not sure if that's the best way to go

`is_callable` checks callability from *current* scope, right? But what about protected methods?

**Comment by bwaidelich** [comment]
> is_callable checks callability from current scope, right? But what about protected methods?

good point.. maybe check for private scope explicitly

**Comment by bwaidelich** [comment]
@kdambekalns @albe This issue is assigned to the three of us for some reason.
Is one of you working on a fix? Because I'm currently _not_, but I could have a look tomorrow if nobody takes care of it before that

**Comment by kdambekalns** [comment]
I assigned it to us, since we discussed it this morning. Didn't @kitsunet mention he might be able to look into it?

**Comment by kdambekalns** [comment]
I'll work on this now.
