### ISSUE TITLE
PositionalArraySorter forgets items that are positioned relative to non-existing key

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2213]
See https://github.com/neos/flow-development-collection/pull/2207#discussion_r516978425

The problem is https://github.com/neos/flow-development-collection/blob/master/Neos.Utility.Arrays/Classes/PositionalArraySorter.php#L223-L228 and https://github.com/neos/flow-development-collection/blob/master/Neos.Utility.Arrays/Classes/PositionalArraySorter.php#L250-L254

It should be checked if the matched key `$matches[1]` exists inside the *original untouched* `$arrayKeysWithPosition`. If not, the item should be inserted into `middleKeys` or an exception be thrown.
If the original order within the settings should be kept, then `position` of the key needs to be changed, and `middleKeys` be collected **after** before/after keys.

**Comment by bwaidelich** [comment]
I had a quick look at this and came to the same conclusion. I think we should throw an exception if a nonexisting key is referenced. Every other behaviour is nondterministic and prone to typos.
Obviously a breaking change (there is even a test case that breaks with that change). But easier to implement and, more importantly, very sensible IMO

**Comment by radmiraal** [comment]
I found this issue after running into exceptions in a Flow application which has Neos.Media installed. Neos.Media has the following config:

```
    mvc:
      routes:
        Neos.Media:
          position: 'before Neos.Neos'
```

With the added exceptions in the PositionalArraySorter the loading of the route ordering now fails if Neos.Neos is not installed (which is a valid use case). Another context the change could cause problems is the ordering of packages which can be defined in the composer.json. The ordering could be meant as "order after package x if it is really installed". Those kinds of sorting are valid, but might now lead to exceptions.

What I'm unsure about: is this an issue with the exceptions in the PositionalArraySorter or is this the responsibility of the component loading the routing configuration or the package manager in case of the package sorting? My gut feeling says the exceptions are a good thing, and cleaning up the array fed to the PositionalArraySorter might be up to the component that requires sorting (as this component is probably more capable of deciding what it means when a key is missing).

Any opinion on that @bwaidelich / @albe ?

**Comment by bwaidelich** [comment]
Thanks for the comment!
It should be "position: start"i
 in the Media package IMO and potentially overriden from the Neos package

**Comment by radmiraal** [comment]
Not sure if I agree. `before Neos` is the only requirement, `position start` sounds like another thing that might lead to the requirement having multiple positions like 'start but after ...' for example, not sure what the side effects might be.

But that's already out of scope for this issue I guess, would a post on discuss still be the place to collect thoughts on a topic like this?

**Comment by bwaidelich** [comment]
> before Neos is the only requirement

Right, but IMO it doesn't make sense that this package defines this order since that creates a bidirectional dependency (or an nondeterministic if Neos isn't installed). And since this package can be used without Neos it should not refer to it I suppose.

> position start sounds like another thing that might lead to the requirement having multiple positions

Yes, that's true. I think we should just omit the position here.

>  would a post on discuss still be the place to collect thoughts on a topic like this?

I think a new issue on https://github.com/neos/neos-development-collection would be a good place. Would you be up for adding one?

> btw: happy last hours in 2020

Happy New Year! :)

> let's make sure we meet again in 2021

Yes, that would be great!!

**Comment by radmiraal** [comment]
I created the issue ;) so further action in https://github.com/neos/neos-development-collection/issues/3258
