### ISSUE TITLE
@ORM\Column not taken into account when creating mapping for relations

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#2215]
The following annotations

```
     /*
     * @var \Dafis\Core\Domain\Model\Organization
     * @ORM\ManyToOne
     * @ORM\Column(name="organization_id")
     */
    protected $organization;
```

creates a auto-generated migration like this

`$this->addSql('CREATE TABLE dafis_core_domain_model_organization_client (id VARCHAR(255) NOT NULL, organization VARCHAR(255) DEFAULT NULL, ...`

becuase the FlowAnnotationDriver does not take `@ORM\Column` annotations into account when creating relation mapping

**Comment by albe** [comment]
Apparently, that's also what doctrine does, so we have taken that 1:1 from there:
https://github.com/doctrine/orm/blob/2.6/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php#L312-L314

>            // Field can only be annotated with one of:
>            // @Column, @OneToOne, @OneToMany, @ManyToOne, @ManyToMany

So Column is orthogonal to the relation annotations, it specifies a concrete column in the table and hence makes no sense for specifically xToMany relations and only partly for xToOne.
It seems JoinColumn is the right tool to specifiy the column name for a relation (foreign key) https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/annotations-reference.html#joincolumn

**Comment by sorenmalling** [comment]
Closing again, based on research and comment from @albe including this from Slack

```
Also, we try to copy the doctrine driver and just make the existing annotations more useable via sane defaults, not rearranging or changing their functionality
```
👍
