### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#2233]
- Travis tests on PHP 8 since https://github.com/neos/flow-development-collection/pull/2015
- `doctrine/dbal` runs with PHP8 as of 2.12.0: https://github.com/doctrine/dbal/pull/4347
- `doctrine/orm` is on the way: https://github.com/doctrine/orm/pull/8303

**Comment by kdambekalns** [comment]
`doctrine/commons` is raised to 2.13.1 in #1880 and supports PHP 8 as of that version.

**Comment by kdambekalns** [comment]
`doctrine/dbal` is raised to 2.12 in #1880 and supports PHP 8 as of that version.

**Comment by kdambekalns** [comment]
The Doctrine dependencies need to be raised in Neos, too, once #1880 is merged.

**Comment by albe** [comment]
With #2287 existing code runs on PHP 8. However, to fully support PHP 8 we need to be able to deal with union types, constructor properties and annotations (at least for proper proxy building).

First step is maybe to add meta-info on union types to the reflection service.

**Comment by albe** [comment]
PHP8 Attributes are now supported as of #2468 but #2404 is still WIP

**Comment by bwaidelich** [comment]
@albe the related PRs have been merged, can this one be closed?
