### ISSUE TITLE
flow kickstart:package Happy.Coding installation not successfully installed

### ISSUE THREAD

**Issue by tscgist** [neos/flow-development-collection#2248]
### Description

When following the getting-started hints in a fresh docker windows 10 environment, flow kickstart:package Happy.Coding example errors and rolls back any installation steps.

### Steps to Reproduce

1. Install fresh checkout of flow
2. ./flow kickstart:package Happy.Coding

#### Expected behavior

Generates working example.

#### Actual behavior

./flow kickstart:package Happy.Coding
You are running composer with Xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package composer-runtime-api ^2.0.0 exists as composer-runtime-api[1.0.0] but these are rejected by your constraint.
  Problem 2
    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.
    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.
    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.
    - Installation request for ocramius/proxy-manager ^2.10 -> satisfiable by ocramius/proxy-manager[2.10.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
The installation was not successful.
Composer returned the error code: 2

  Type: Neos\Flow\Package\Exception
  Code: 1572187932
  File: Packages/Framework/Neos.Flow/Classes/Package/PackageManager.php
  Line: 408

Open Data/Logs/Exceptions/2020111513212559a8ba.txt for a full stack trace.

### Affected Versions

latest version 2020-11-15

I fixed the issue for me just by changing the value of contant RUNTIME_API_VERSION from "1.0.0" to "2.0.0" [in ..\Packages\Libraries\composer\composer\src\Composer\Composer.php, line 67]

**Comment by Benjamin-K** [comment]
I'm having the same problem. But i can give some more insides. The problem occurs, when you try to create or kickstart a package while already having upgraded to **composer 2**. `neos/flow` still has `composer/composer@^1.9` as a requirement, so this versions don't match any more. 

### Possible workaround:

1. Reset your local composer version to version 1: `composer self-update --1`
2. Update your packages, so all packages work with the downgraded composer version: `composer update` (possibly with `--no-dev`)
3. Do your package kickstart: `flow kickstart:package Happy.Coding`
4. Use new composer version again: `composer self-update --2`
5. Update packages again: `composer update` (`--no-dev`).


### Steps to fix this in flow

❗️Breaking Change❗️

- Change requirement for `composer/composer` to `^2.0` in `neos/flow`.
- Add requirement for `composer-runtime-api@^2.0.0` in `neos/flow`.

This will require every user to use composer version 2 to update flow to a newer version.

As an alternative, there could be always two releases for flow. One, that works with composer 1, another that works with composer 2. But this would increase the work needed to further maintain the Flow Framework.

**Comment by Benjamin-K** [comment]
Ok, after checking Composer Readme, it might also work, if the Flow Framework only changes requirements for `composer/composer` to `^2.0`. I think users with composer v1 should still be able to use Flow / Neos. But this needs to be tested. The requirement for `composer-runtime-api` should not be added.

**Comment by albe** [comment]
So basically means we should "backport" https://github.com/neos/flow-development-collection/pull/2251 - which would be okay for me /cc @kdambekalns

**Comment by Benjamin-K** [comment]
I think you can safely use `composer/composer@^2.0`. Composer itself says:

> If your code relies on any of these runtime features, you should require "composer-runtime-api": "^2.0" in your composer.json. This is a virtual package which is provided by Composer and will make sure people have to use Composer 2.x to install your package.

If we do not add this to our requirements, i think it should work out without problems. But it needs to be checked of course.

**Comment by kdambekalns** [comment]
Sounds reasonable. TBH, what I did not check for #2251 is what happens if a custom package actually requires Composer, that would be a conflict then. But maybe we can allow both, i.e. `^1.9 || ^2.0`?

**Comment by albe** [comment]
> But maybe we can allow both, i.e. ^1.9 || ^2.0?

Yes, I would do that, as we also did this in 7.0 :)

**Comment by Benjamin-K** [comment]
Sounds like a plan. `^1.9 || ^2.0` should work just fine. If there is any package, that heavily requires composer 2, it should require `composer-runtime-api@^2.0.0` anyway. So we should go for it :)

**Comment by sorenmalling** [comment]
@albe Can this issue be closed after your merge?

**Comment by albe** [comment]
Yes, if anything is still not working in that regard after the next patch-level release, feel free to reopen.
