### ISSUE TITLE
Improve getting started database setup with alternative method

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2264]
The current getting started guide suggests running `./flow doctrine:migrate` to setup the initial database schema.
For example DigitalOcean has a managed database setup, where `sql_require_primary_key` is enforced, which prevents migrations that have a `DROP PRIMARY KEY ...` statement from running.
There is an alternative way to setup a fresh database though, that avoids this issue (and other potential problems with migrations):
`./flow doctrine:create && ./flow doctrine:migrationversion --add --version all`

This creates the new schema directly and just marks all migrations as applied. Of course this will not solve the problem for future migrations.

We should mention this alternative in the getting started guide https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartII/Configuration.html#database-setup

**Comment by kdambekalns** [comment]
Does it create the exact same result? I know that `update` can do really harmful things (drop/create instead of rename), which is not an issue when starting from scratch. Anyway, that'd need to be checked carefully.

But: How on earth are future updates supposed to work in a setup like that, when you cannot drop a PK? That sounds like a pretty stupid limitation, TBH.

**Comment by albe** [comment]
> But: How on earth are future updates supposed to work in a setup like that, when you cannot drop a PK? That sounds like a pretty stupid limitation, TBH.

Yeah. Their argument seems to be their replication protocol, which requires a PK 🤷‍♂️ Anyway, further updates are of course a problem with that. If you need to change a tables PK, you need to backup the table, recreate with new PK, then reinsert the backup-data. One giant PITA, but still doable.

> Does it create the exact same result?

I'm pretty confident it does. Yes, updates do destructive things, but still the end result should always be the same (structurally, not data) as running migrations.
