### ISSUE TITLE
Update to PhpUnit 9

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#2293]
As per https://phpunit.de/supported-versions.html we should switch to PhpUnit 9 for the next major (at least). PhpUnit 8 will be supported (only) until February 5, 2021–that is rather soon.

- [x] [BuildEssentials](https://github.com/neos/BuildEssentials/pull/44)
- [x] [Flow development collection](https://github.com/neos/flow-development-collection/pull/2310)
- [x] [Flow development distribution](https://github.com/neos/flow-development-distribution/pull/52)
- [x] [Flow base distribution](https://github.com/neos/flow-base-distribution/pull/14)

**Comment by bwaidelich** [comment]
Is this mostly about new dependencies or do we have to fix tests as well? can you already tell?

**Comment by kdambekalns** [comment]
Test need to be tweaked, deprecated assertions are used. I'll push something today.

**Comment by bwaidelich** [comment]
Thanks a lot for taking care!
I removed the ticks in the todo list above since the related PRs are not merged yet
