### ISSUE TITLE
Research/Discussion: Can we use the Schema object of a migration, to create migrations, instead of raw sql

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#2299]
Everytime a core migration is created, we need to "double it" to make is support other databases (ex. Postgre)

That also means, a community package created, with migrations, either has to say "we only support MySql" or create migration for other database platforms.

But, each time we create a migration, we always get the `Schema $schema` object for both up and down methods

```
public function up(Schema $schema): void
{
...
}
```

This object allows us to use the doctrine/dbal possibilities (including types - see screenshot below) to create migration, not being dependent on raw SQL.

```
$schema->createTable('transfers')
            ->addColumn('createdDateAndTime', 'datetime')
```

and so on.

This is similar to (at least of my knowledge, more probably) Rails and Laravel describes a migration, in style of code and api.

## Pros
 * IDE friendly (autocomplete etc)
 * One migration independent of database?
 * Supports whatever doctrine/dbal support

## Cons
 * Something about column fields and mapping?
 * You have to write it your self - unless, we can use some magic that I didn't look into atm

**Types**
![image](https://user-images.githubusercontent.com/531918/100849359-c034a300-3482-11eb-986c-2d56a62ab555.png)

**Comment by sorenmalling** [comment]
Migrations could be located in the `Vendor.Package/Migrations` folder with same names as today.

The SchemaTool (used by our own Doctrine Service class) can generate and execute the created schema, based on the database platform setup in Settings.yaml

**Comment by albe** [comment]
For the record https://twitter.com/Ocramius/status/1346844436416917504

**Comment by sorenmalling** [comment]
That is a super valid point an concrete issue and blocker :)

**Comment by sorenmalling** [comment]
With the issue raised by @ocramius in the linked twitter thread from @albe I say that this topic can be closed. 

Well documented and concluded, that the dependency of Doctrine and it's generating of SQL makes it a bad idea to move the core migrations to using the Schema object.

Thus it's free for others to go with it, this ticket and the twitter thread (screenshot below for reference) state's that it's no a durable solution.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/531918/104285070-5bbe2800-54b3-11eb-9475-602006cf975c.png">
