### ISSUE TITLE
Migration Version20201109224100 changes unrelated code

### ISSUE THREAD

**Issue by theilm** [neos/flow-development-collection#2363]
### Description

The migration Version20201109224100 adds the correct return type to the getDescription method of DB migrations to be compatible with the method signature of the abstract class. It searches only for the method name, though, and changes all methods that have the same name. That could break userland code.

#### Expected behavior

Only DB migration files are changed.

#### Actual behavior

All methods with the same name are changed.

**Comment by sorenmalling** [comment]
Hi @theilm - thanks for the report :) Do you think you can provide a fix to the code migration, so it does as expected?

**Comment by theilm** [comment]
Hi @sorenmalling, I created a pull request - I am not 100% sure about the implementation and the correct target branch, so feedback is welcome! :)
