### ISSUE TITLE
Introduce ability to add custom default Fluid namespaces via configuration

### ISSUE THREAD

**Issue by martinlipp** [neos/flow-development-collection#2375]
### Description

It would be nice to have the ability to add custom Fluid namespaces (beside the 'f' namespace) via configuration. Custom view helpers inside one's own package are often needed in all/many templates, partials and layouts, and it can be cumbersome to have to add the namespace to all of this files.
I can provide a pull request were this feature is added with minimal code updates inside the FluidAdaptor\Core\ViewHelper\ViewHelperResolver class.

**Comment by sorenmalling** [comment]
Hi @martinlipp 
Did you know that you can call your viewhelper by the syntax

`<vendor.package:viewhelper arguments.... />`

Let me give you an example

```
<dafis.application:navigation.menu>
<li class="{f:if(condition: menuItem.active, then: 'menu-item--active')}">
					<a href="{f:uri.action(package: menuItem.targetPackageKey, controller: menuItem.targetControllerName, action: menuItem.targetActionName, arguments: {organizationIdentifier: organizationIdentifier})}">
						{menuItem.label}
					</a>
				</li>
</dafis.application:navigation.menu>
```

This renders my viewhelper located in the follow namespace/location

```
<?php

namespace Dafis\Application\ViewHelpers\Navigation;

use Neos\Flow\Annotations as Flow;
use Neos\FluidAdaptor\Core\ViewHelper\AbstractViewHelper;
use Dafis\Application\UserInterface\Navigation\Menu;

class MenuViewHelper extends AbstractViewHelper
{
// render method and friends goes here
}
```

so no need for importing the namespace, only to get a shorter syntax.

**Comment by martinlipp** [comment]
Thank you, @sorenmalling.
Yes, I'm aware of that. But I think it would still be a nice feature. Having to write the whole namespace for every view helper, could easily become cumbersome too. I'd prefer the abbreviated syntax, especially when configureable with one line.

**Comment by sorenmalling** [comment]
@martinlipp 
I'm all in favor for that - push a PR and I will review help :)

**Comment by martinlipp** [comment]
Here's a pull request for this feature: https://github.com/neos/flow-development-collection/pull/2378
