### ISSUE TITLE
Improve psalm hinting with additional annotations

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2376]
See https://gist.github.com/Ocramius/4bd03ad4d545bb07164c133d4d2b3686 for a (small) reference of what is possible

**Comment by mhsdesign** [comment]
im not against it, but we should discuss our code styleguide and keep it uniform. I think codewise the new CR is pretty neat but idk if they use psaml too in this way...

My opinion would be:
We dont need so many special psalm types if we just dump arrays and use Collection Objects and use more Value Objects in general.

**Comment by kdambekalns** [comment]
We switched to PHPStan…
