### ISSUE TITLE
Question: Linking external files into /Web directory

### ISSUE THREAD

**Issue by SC-cmarquardt** [neos/flow-development-collection#2379]
Hi,

is there a way to symlink static files which are located parallel to the project directory into the /Web directory?
Reason: Files which are needed in the project must be maintained from "outside" the project filesystem.
My current configuration looks like this
```
# Storages
externalStaticDocumentsStorage: 
  storage: 'Neos\Flow\ResourceManagement\Storage\FileSystemStorage' 
  storageOptions:
     path: '%FLOW_PATH_ROOT%../Resource_documents/'

# Target
externalStaticDocumentsTarget: 
  target: 'Neos\Flow\ResourceManagement\Target\FileSystemSymlinkTarget'
   targetOptions:
     path: '%FLOW_PATH_WEB%_Resources/StaticDocs/' 
    baseUri: '_Resources/StaticDocs/' 
    relativeSymlinks: false

# Collection
statdocs: 
  storage: 'externalStaticDocumentsStorage' 
  target: 'externalStaticDocumentsTarget'

```
But the symlinks are not created. Just an empty folder. As far as I can see the FileSystemStorage works on a Repository method for fetching all files. Only the PackageStorage fetches  files directly from the filesystem. But I can't use a path outside of the Package as configuration.
Is there a build in solution?

Kind regards,
Christopher

**Comment by sorenmalling** [comment]
Hi @SC-cmarquardt 

Please raise questions on https://discuss.neos.io
