### ISSUE TITLE
force flag does no longer create empty migration with doctrine:migrationgenerate

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#2385]
If you use the command

`./flow doctrine:migrationgenerate --force`

to try and create a empty migration, this will not create any :)

The conclusion is, that there is no migrations to generate (from the ORM).

The `force` flag is only used for a condition, to see if it's `false` there is any new migration waiting

**Comment by kdambekalns** [comment]
Try to disable `--diff-against-current`…

**Comment by sorenmalling** [comment]
Thank you for your kind answer. That setting did not pop into mind as having anything to do with generating a empty migration file, hence my created issue.

All is good - nothing to see here
