### ISSUE TITLE
ObjectAccess with direct access fails on private properties of proxied classes

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#2388]
### Description

Classes with private properties do not react as epxected to `ObjectAccess::setProperty()` with `$forceDirectAccess` enabled.

### Steps to Reproduce

Have a class wirh a private property that is proxied for DI/AOP purposes. You end up with a structure like this:

```
class SomeClass_Original {
    private $property = 'initial';
    public function showProperty() {
        echo $this->property;
    }
}
class SomeClass extends SomeClass_Original {
    // DI and AOP code built by Flow
}

$subject = new SomeClass();
```

1. `ObjectAccess::setProperty($subject, 'changed', true)`
2. `$subject->showProperty`

#### Expected behavior

Property is set in "original" class and output is: `changed`

#### Actual behavior

Property is set in proxy class and output is: `initial`

### Affected Versions

Flow: effectively all, the code in question is unchanged for the last 6 years.

### Possible solution

Change https://github.com/neos/flow-development-collection/blob/1a4e6ba72d6e20821a8c7e97a9fe109e6013eccb/Neos.Utility.ObjectHandling/Classes/ObjectAccess.php#L250-L257 to

```php
$className = TypeHandling::getTypeForValue($subject);
if (property_exists($className, $propertyName)) {
    $propertyReflection = new \ReflectionProperty($className, $propertyName);
    $propertyReflection->setAccessible(true);
    $propertyReflection->setValue($subject, $propertyValue);
} elseif (substr_compare(get_parent_class($className), '_Original', -9) === 0 && property_exists(get_parent_class($className), $propertyName)) {
    $propertyReflection = new \ReflectionProperty(get_parent_class($className), $propertyName);
    $propertyReflection->setAccessible(true);
    $propertyReflection->setValue($subject, $propertyValue);
} else {
    $subject->$propertyName = $propertyValue;
}
```

**Question** – do we want this?

**Comment by bwaidelich** [comment]
I don't think that this change would break anything so +1 for the idea.

The hard-coded `'_Original'` should probably replaced with `Neos\Flow\ObjectManagement\Proxy\Compiler::ORIGINAL_CLASSNAME_SUFFIX` though.
Or even with sth like:
```php
} elseif ($subject instanceof ProxyInterface) {
...
```

**Comment by kdambekalns** [comment]
> The hard-coded `'_Original'` should probably replaced with `Neos\Flow\ObjectManagement\Proxy\Compiler::ORIGINAL_CLASSNAME_SUFFIX` though.

Right, forgot about that one!

> Or even with sth like:
> 
> ```
> } elseif ($subject instanceof ProxyInterface) {
> ...
> ```

Probably even better, indeed.
