### ISSUE TITLE
For a easier scalable setup, DoctrineMigrations folder in Data could be moved to Temporary

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#2425]
While creating a setup for the platform.sh hosting, I found my application crashing when spinning up due to the DoctrineMigrations folder was trying to be created on a mount not created.

This was due to `DoctrineMigrations`trying to be created in the root of the `Data` folder - but not before the version was deployed and the migration was about to be executed, and the `getDependencyFactotry` of the Doctrine Service class was called.

I suggest to move the `DoctrineMigrations` folder into the `Temporary` folder og use the `FLOW_PATH_TEMPORARY_BASE`. 

A mount for the temporary (cache for examples) files  is seen created, and if that is already created as a mount, this will lead to know issue with `DoctrineMigrations` is not writable (in a deployed read-only environment)

**Comment by sorenmalling** [comment]
For a reference, these mounts are created for a Flow setup on platform.sh

```
mounts:
  '/Data/Logs':
    source: 'local'
    source_path: 'files/data-logs'
  '/Data/Temporary':
    source: 'local'
    source_path: 'files/data-temporary'
  '/Data/Persistent':
    source: 'local'
    source_path: 'files/data-persistent'
  '/Web/_Resources':
    source: 'local'
    source_path: 'files/web-resources'
  '/Data/DoctrineMigrations':
    source: 'local'
    source_path: 'data/doctrine-migrations'

```

**Comment by albe** [comment]
Related to https://github.com/neos/flow-development-collection/issues/2284
