### ISSUE TITLE
Php 8.0 compatibility issues in TEST-environment, - concerning Neos_FluidAdaptor

### ISSUE THREAD

**Issue by ChKoeppel** [neos/flow-development-collection#2435]
### Description
Following notice appears in frontend ... (only on first hit after flushing)
**Deprecated**: Required_ parameter $renderingContext follows optional parameter $arguments in ..._ 
- Flow_Object_Classes/Neos_FluidAdaptor_ViewHelpers_Security_IfHasRoleViewHelper.php on line 110
- Flow_Object_Classes/Neos_FluidAdaptor_ViewHelpers_Security_IfAuthenticatedViewHelper.php on line 72
- ...

### Steps to Reproduce
1. setup "**php 8.0 testing environment**" proposed by '**albe**'
2. composer require "**neos/flow-development-collection**": "**dev-albe-doctrine-php8 as 7.0.x-dev**"
3. all works still fine with php 7.4 ...
4. change now php-version to **php 8.0**
5. flush caches and warmup ...
6. 'Deprecated' notice messages (mentioned below) appear on first hit ... and disappear afterwards ...
7. apart these minor 'deprecation' notices, - there are no further visible issues on this test-setup so far ...
8. my application runs with '**fluid-templates**', '**neos.media**', etc

#### Expected behavior
...

#### Actual behavior
- mentioned 'Deprecated' notice in frontend only on first hit after flushing
- no errors thrown into the logs
- btw ... my Flow-application gains 20-30% of speed with php 8.0 (against 7.4) (=THANK YOU !!)

### Affected Versions
Testing 'flow dev' environment on Neos.Flow version 7.0
- '**dev-albe-doctrine-php8**' ... 
- and PHP 8.0 ...

Setup with composer:
- "neos/flow-development-collection": "dev-albe-doctrine-php8 as 7.0.x-dev"

Flow:
- neos/flow-development-collection     dev-albe-doctrine-php8 82d5c85

### Fixing strategies
adapt code in the **Neos.FluidAdaptor**
- https://php.watch/versions/8.0/deprecate-required-param-after-optional

**Comment by albe** [comment]
Thanks for the report! Helps us get PHP8 support available soon :) Will take care about the deprecation warnings ASAP.

The first changes from the albe-doctrine-php8 branch are already merged, so the `"dev-albe-doctrine-php8 as 7.0.x-dev"` is no longer necessary.
