### ISSUE TITLE
Annotations incompatible with doctrine/orm 2.9.x

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2487]
Our existing usage of doctrine Annotations was based on the assumption that all attributes can be skipped and added through the Framework's own reflection information inside the AnnotationDriver.
Hence it was possible to annotate a relation like:
```
/**
 * @var Collection<SomeEntity>
 * @ORM\ManyToMany
 */
```
while doctrine would expect `@ORM\ManyToMany(targetEntity="SomeEntity")`.

With https://github.com/doctrine/orm/pull/8266 the annotations now take constructor arguments that are more strict and e.g. the ManyToMany annotation expects the `targetEntity` to be set (https://github.com/doctrine/orm/pull/8266/files#diff-fd66a66edd41537e14044223e2df923209d449caf67b2eb46293125be94f4a60R64). This in turn means, that we can no longer add the targetEntity meta information in our own AnnotationDriver, since the annotation is already instanciated in the `DocParser` https://github.com/doctrine/annotations/blob/1.13.x/lib/Doctrine/Common/Annotations/DocParser.php#L971

```
Argument 1 passed to Doctrine\ORM\Mapping\ManyToMany::__construct() must be of the type string, null given, called in /home/runner/work/flow-development-collection/flow-development-collection/flow-development-distribution/Packages/Libraries/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 971
Type: TypeError
  File:
Packages/Libraries/doctrine/orm/lib/Doctrine/ORM/Mapping/ManyToMany.php
  Line: 63
```

This will probably be tricky to resolve unless we can get some help from the doctrine team.

**Comment by albe** [comment]
fyi @kdambekalns

**Comment by albe** [comment]
Not necessarily, because native annotations (=attributes) are reflected without creating an instance of the class. You only get a blueprint for creating an instance with the arguments specified in the attribute - and you can of course mutate those before the instanciation.
So in closing, going full PHP8 attributes would solve this, but then again that's still a bit down the road.

From what I can see, only few doctrine annotations are actually affected (ManyToX and Embedded) - so mayyyyybeeeeee we can convince the doctrine team to make those three classes accept null as argument in the constructor?

**Comment by kdambekalns** [comment]
But… a PR that includes "prototype" in the title made it into a minor release, breaking things!? 🤔🤣

**Comment by albe** [comment]
Can be closed since doctrine restored b/c with the constructor arguments.

One additional side-note: Doctrine will support type reflection from PHP typehints, so at least for *ToOne relations it will be possible to do
```
/**
 * @ORM\ManyToOne
 */
 protected SomeEntity $entity;
```
some time in the future without us having to add this to our AnnotationDriver (we will need to sync it to the upstream driver though).
