### ISSUE TITLE
UsernamePasswordHttpBasic does not work if the app has also an provider with BearerToken

### ISSUE THREAD

**Issue by runner78** [neos/flow-development-collection#2490]
### Description

I planned to replace my own BearerToken with the new one from Flow 7.1, but had to find out that the application would then no longer allow any other type of Authorization header like "Basic".
My application has 2 authentication Provider, one JWT (bearer token) and one AppClient (Basic, custom Client id).

With Basic Authorization header:
Error message: Could not extract access token from Authorization header: "Bearer" keyword is missing

Flow: 7.1

**Comment by albe** [comment]
Hey, thanks for the report! I can see how this can be an issue and throwing an exception in the token was maybe a mistake (https://github.com/neos/flow-development-collection/blob/d3ae53288528865acf7558d13cc2bef49e557e91/Neos.Flow/Classes/Security/Authentication/Token/BearerToken.php#L57)
It should just set the authentication status and return.

/cc @daniellienert

**Comment by daniellienert** [comment]
Absolutely, already fixed this in some customer implementation recently. I'll take care
