### ISSUE TITLE
"iterable" gets qualified during proxy building

### ISSUE THREAD

**Issue by fcool** [neos/flow-development-collection#2498]
Since PHP 7.1 `iterable` is a new scalar pseudo-type, which is not allowed to be "qualified".

But having a method returning an `iterable` (and corresponding type-hint) will lead to a proxy method, annotated with `\iterable`, which will lead to a PHP Fatal error: `Type declaration 'iterable' must be unqualified in ...`

This could be solved in `\Neos\Utility\TypeHandling::isSimpleType`, or in `\Neos\Flow\Reflection\ReflectionService::reflectClassMethod` having an array of words, which should not be qualified `!in_array($returnType, ['self', 'null', 'callable', 'void'])`.

As I am unsure, where it really belongs: Ideas?

Flow: 5.3

**Comment by kdambekalns** [comment]
To me it's not really a "simple" type (but I admit that method name is awkward.)

**Comment by albe** [comment]
I'd put it in the array of exemptions that already exists - `!in_array($returnType, ['self', 'null', 'callable', 'void'])` - since `iterable` is not a real "type".

**Comment by fcool** [comment]
But as Flow 5.3 is "security only", the target would probably Flow 6.3, correct?

**Comment by albe** [comment]
Yes, correct
