### ISSUE TITLE
Usage of removed function `GuzzleHttp\Psr7\stream_for()`

### ISSUE THREAD

**Issue by MCStreetguy** [neos/flow-development-collection#2511]
### Description

The `Neos\Flow\Mvc\ActionResponse` class still makes use of a removed function `stream_for` from the `guzzlehttp/psr7` package. _([reference](https://github.com/neos/flow-development-collection/blob/6.3/Neos.Flow/Classes/Mvc/ActionResponse.php#L60))_
As far as I can see this has already been addressed some time ago with https://github.com/neos/flow-development-collection/pull/2455 for version 7.1, but I could not find any information on a fix for older versions such as the previous 6.3.
As 6.3 is still considered supported and as it's dependency constraints allow for `guzzlehttp/psr7` to be installed in version `^2.0`, I wanted to re-raise this issue with that particular version in mind.

I also checked the other changed files from the mentioned merge request, which all seem to be affected by this problem too:

- [Http/Client/CurlEngine.php](https://github.com/neos/flow-development-collection/blob/6.3/Neos.Flow/Classes/Http/Client/CurlEngine.php)
- [Http/Helper/ResponseInformationHelper.php](https://github.com/neos/flow-development-collection/blob/6.3/Neos.Flow/Classes/Http/Helper/ResponseInformationHelper.php)
- [Http/Helper/UploadedFilesHelper.php](https://github.com/neos/flow-development-collection/blob/6.3/Neos.Flow/Classes/Http/Helper/UploadedFilesHelper.php)
- [Security/Authentication/EntryPoint/HttpBasic.php](https://github.com/neos/flow-development-collection/blob/6.3/Neos.Flow/Classes/Security/Authentication/EntryPoint/HttpBasic.php)
- [Security/Authentication/EntryPoint/WebRedirect.php](https://github.com/neos/flow-development-collection/blob/6.3/Neos.Flow/Classes/Security/Authentication/EntryPoint/WebRedirect.php)
- [Unit/Http/Helper/ResponseInformationHelperTest.php](https://github.com/neos/flow-development-collection/blob/6.3/Neos.Flow/Classes/Unit/Http/Helper/ResponseInformationHelperTest.php)

### Steps to Reproduce

1. Create a new project based on `neos/flow-base-distribution:^6.3` (or alternatively `neos/neos-base-distribution:^5.3`)
2. Spin up a (local) webserver of some kind for the new project
3. Try to access any url of the project in the browser

#### Expected behavior

The application should not error on each request.

#### Actual behavior

Flow dies immediately with the following error message:

```plain
Call to undefined function GuzzleHttp\Psr7\stream_for()

Exception Code    0
Exception Type    Error
Thrown in FIle    Packages/Framework/Neos.Flow/Classes/Mvc/ActionResponse.php
Line              60
```

### Affected Versions

Neos: 5.3 LTS / v5.3.3

Flow: 6.3 LTS / v6.3.10

The oldest version affected by this bug I could find is Flow v6.0.0. As it is not supported anymore, the only relevant versions to this issue range from 6.3.0 up to 6.3.10.

### Workaround

It's possible to work around the problem by pinning the package `guzzlehttp/psr7` to version `1.8.2`.

**Comment by albe** [comment]
Hey, thanks for the report. We decided to disallow guzzlehttp/psr7 2.0 in 6.3+ as of https://github.com/neos/flow-development-collection/pull/2502 because otherwise we'd have to increase the minimum version for that to ^1.7 in a patch-level release which I don't like too much. That allowed 2.0 installation before the official release was a mistake in the first place.
Once a new release is tagged, this should be resolved. We just need to decide how to proceed with Flow 7.1 and guzzlehttp/psr7 - see https://github.com/neos/flow-development-collection/pull/2501

**Comment by MCStreetguy** [comment]
First, thank you for the quick feedback!
I'm glad to hear that the fix is just waiting for the next release. The two pull requests I had actually overlooked in my research, my fault. Then I'll stick with the workaround for now until the update is available.

I would still leave the issue open as a reference for others until the fix is live, if you don't mind.

**Comment by albe** [comment]
FYI: We have finally decided on #2501 and a new release should be tagged soon (latest over the WE)

**Comment by albe** [comment]
Releases have been tagged, so I'm closing this :) Thanks for your patience!
