### ISSUE TITLE
Trying to get property 'lazy' of non-object in ConfigurationBuilder

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#2532]
### Description

After a change to the code base of a project the next compile run dies with an exception caused by a notice: 

    Trying to get property 'lazy' of non-object in ConfigurationBuilder

### Steps to Reproduce

Reproducing this on a second environment has failed, sadly.

#### Expected behavior

Upon changing the code base (in Development context) chanegs are picked up by the file monitoring and classes are reflected, proxies built, …

#### Actual behavior

```
Exception #1 in line 492 of /home/…/Packages/Framework/Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php: Notice: Trying to get property 'lazy' of non-object in /home/…/Packages/Framework/Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php line 492



20 Neos\Flow\Error\ErrorHandler::handleError(8, "Trying to get property 'lazy' of non-object", "/home/…/Package…tManagement/Configuration/ConfigurationBuilder.php", 492, array|12|)
19 Neos\Flow\ObjectManagement\Configuration\ConfigurationBuilder::autowireProperties(array|1211|)
18 Neos\Flow\ObjectManagement\Configuration\ConfigurationBuilder::buildObjectConfigurations(array|18|, array|16|)
17 Neos\Flow\ObjectManagement\CompileTimeObjectManager::initialize(array|109|)
16 Neos\Flow\Core\Booting\Scripts::initializeObjectManagerCompileTimeFinalize(Neos\Flow\Core\Bootstrap)
15 call_user_func(array|2|, Neos\Flow\Core\Bootstrap)
14 Neos\Flow\Core\Booting\Step::__invoke(Neos\Flow\Core\Bootstrap)
13 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
12 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
11 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
10 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
9 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
8 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
7 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
6 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
5 Neos\Flow\Core\Booting\Sequence::invoke(Neos\Flow\Core\Bootstrap)
4 Neos\Flow\Cli\CommandRequestHandler::boot("Compiletime")
3 Neos\Flow\Cli\CommandRequestHandler::handleRequest()
2 Neos\Flow\Core\Bootstrap::run()
1 require("/home/…/Packages/Framework/Neos.Flow/Scripts/flow.php")
```

The notice is triggered by the use of `$injectAnnotation->lazy` in line 492 https://github.com/neos/flow-development-collection/blob/5725a9d38e8eb77d0290934a56b1bdce02c4f137/Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php#L490-L493

### Affected Versions

Flow: 5.3.27
PHP: 7.2.34

**Comment by kdambekalns** [comment]
The `$injectAnnotation` is returned from https://github.com/neos/flow-development-collection/blob/5725a9d38e8eb77d0290934a56b1bdce02c4f137/Neos.Flow/Classes/Reflection/ReflectionService.php#L1089-L1097

The reason for the error is the fact that the `current()` call does not return the existing annotation instance (verified through debugging). The array pointer seems to point somewhere else. Using `reset()` instead of current solves the issue.

Using `reset()` does not really alter the (promised) behaviour of the method, but without understanding why this happens I am reluctant to change it…

**Has anyone ever seen such a behaviour?**

**Comment by kitsunet** [comment]
Yep have seen that in multiple projects, it's very fickle, unless it's in my loop I basically never use current. Then rather reset because it's easier to reason what you get from it.

**Comment by kitsunet** [comment]
the comment even says one random annotation, it's non deterministic anyways. So changing that sounds like a non issue to me.

**Comment by iseries** [comment]
Faced this in a project, too. Got 544 such Exceptions since 17.08.2021 - 13:02:21.

```
Exception #1 in line 476 of /var/www/clients/client21/web/neos/Packages/Framework/Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php: Notice: Trying to get property 'lazy' of non-object in /var/www/clients/client21/web/neos/Packages/Framework/Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php line 476

18 Neos\Flow\Error\ErrorHandler::handleError(8, "Trying to get property 'lazy' of non-object", "/var/www/clients/client21/web/neos/Packages/F…tManagement/Configuration/ConfigurationBuilder.php", 476, array|16|)
17 Neos\Flow\ObjectManagement\Configuration\ConfigurationBuilder::autowireProperties(array|1354|)
16 Neos\Flow\ObjectManagement\Configuration\ConfigurationBuilder::buildObjectConfigurations(array|29|, array|105|)
15 Neos\Flow\ObjectManagement\CompileTimeObjectManager::initialize(array|105|)
14 Neos\Flow\Core\Booting\Scripts::initializeObjectManagerCompileTimeFinalize(Neos\Flow\Core\Bootstrap)
13 call_user_func(array|2|, Neos\Flow\Core\Bootstrap)
12 Neos\Flow\Core\Booting\Step::__invoke(Neos\Flow\Core\Bootstrap)
11 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
10 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
9 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
8 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
7 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
6 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
5 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
4 Neos\Flow\Core\Booting\Sequence::invoke(Neos\Flow\Core\Bootstrap)
3 Neos\Flow\Cli\CommandRequestHandler::boot("Compiletime")
2 Neos\Flow\Cli\CommandRequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()


[array] => 
```

**Comment by albe** [comment]
> The reason for the error is the fact that the `current()` call does not return the existing annotation instance (verified through debugging). The array pointer seems to point somewhere else. Using `reset()` instead of current solves the issue.
> 
> Using `reset()` does not really alter the (promised) behaviour of the method, but without understanding why this happens I am reluctant to change it…

I mean, `current()` only returns the current item of the internal pointer of the array points to without changing it. So it is fully dependent on the method returning the array and if it somehow changed the internal pointer.
See https://3v4l.org/1RB2i#v7.4.22
As to what changes the internal pointer of that array in the ReflectionService - I have no idea.

Now given the expected behaviour of this method is rather to return the *first* annotation (even though it states a random annotation, but really no one expects it to return a different annotation every time), I would say using `reset()` (and adjusting the docblock) is the sane approach.

**Comment by iseries** [comment]
Sorry to interrupt this conversation again, I just want to say that in my case the exception should have not come up at all. As in the default php.ini recommended: The `~E_NOTICE` value should be not included in production. The consequences for me of the "bug" are due to crappy php configurations on a production server.
