### ISSUE TITLE
Behat tests fail with PHP error caused by Guzzle

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#2547]
### Description

See https://github.com/neos/flow-development-collection/runs/3418861158?check_suite_focus=true

`PHP Fatal error:  Cannot redeclare GuzzleHttp\Promise\queue() (previously declared in /home/runner/work/flow-development-collection/flow-development-collection/flow-development-distribution/Build/Behat/vendor/guzzlehttp/promises/src/functions.php:24) in /home/runner/work/flow-development-collection/flow-development-collection/flow-development-distribution/Packages/Libraries/guzzlehttp/promises/src/functions.php on line 33`

**Comment by albe** [comment]
😬

**Comment by kdambekalns** [comment]
🤷‍♂️
