### ISSUE TITLE
Role privileges in split policy files are overwritten instead of merged

### ISSUE THREAD

**Issue by daniellienert** [neos/flow-development-collection#2592]
### Description

Given you have a 2 policy files in you package: 

**Policy.One.yaml**

```
roles:
  'Neos.Neos:Administrator':
    privileges:
      -
        privilegeTarget: 'Package.PrivilegeOne'
        permission: GRANT
```

**Policy.Two.yaml**

```
roles:
  'Neos.Neos:Administrator':
    privileges:
      -
        privilegeTarget: 'Package.PrivilegeTwo'
        permission: GRANT
```

then the privilegeOne is overwritten by the definition in Policy.Two.yaml.

#### Expected behavior

I expect the array to be extended, like it is when two Policy.yaml are defined in two different packages.

### Affected Versions

Flow: 7.1

**Comment by daniellienert** [comment]
The behavior is due to the used `arrayMergeRecursiveOverrule` function which also overrides integer keys.

**Comment by sorenmalling** [comment]
@daniellienert Dulicate of https://github.com/neos/flow-development-collection/issues/2341 ?

**Comment by daniellienert** [comment]
@sorenmalling, indeed
