### ISSUE TITLE
Allow to disable authentication providers

### ISSUE THREAD

**Issue by davidspiola** [neos/flow-development-collection#2606]
### Description
Right now, it is not possible to disable authentication providers that have been introduced in other packages (e.g. third-party packages). 

### Steps to Reproduce
1. Go to Neos:Flow:security:authentication:providers
2. Disable the desired provider by 'TheProvider': ~
3. reload auth request

#### Expected behavior

No error should occure 

#### Actual behavior

Error Message: The configured authentication provider "TheProvider" needs a "provider" option!

### Affected Versions

Neos 5.3 LTS and above

**Comment by jonnitto** [comment]
@davidspiola I think you forgot to push, the PR has only one commit
