### ISSUE TITLE
Redis Cache does not respect the application context

### ISSUE THREAD

**Issue by daniellienert** [neos/flow-development-collection#2618]
### Description

The redis backend does not respect the application context in its `buildKey` method. Without that, cache keys are the same if Flow is executed in different contexts.

**Caution! If you use a type of deployment, where every release has its own directory path (like surf / deployer), you either need to set the `FLOW_PATH_ROOT` environment variable or adjust the `applicationIdentifier` in order to be able to flush the redis cache after the release switch step.**

#### Expected behavior

Like file and pdo backend, the redis backend should respect the application context.

### Affected Versions

Neos: * 
Flow: *

**Comment by skurfuerst** [comment]
Hey @daniellienert , 

this can be closed as it is fixed, right? :-)

All the best,
Sebastian

**Comment by daniellienert** [comment]
Right
