### ISSUE TITLE
ResponseInformationHelper breaks Cache-Control header

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#2625]
### Description

When settings the `Cache-Control` header, the `ResponseInformationHelper` breaks it in `makeStandardsCompliant` under certain circumstances.

### Steps to Reproduce

1. `$this->response->setHttpHeader('Cache-Control', 'must-revalidate');`

#### Expected behavior

`Cache-Control: must-revalidate` in response

#### Actual behavior

`Cache-Control: e` in response

### Affected Versions

Flow: ^7.0

**Comment by kdambekalns** [comment]
https://github.com/neos/flow-development-collection/blob/bdc4ab2d44a75630d4c693b2f67ec9b428ba984d/Neos.Flow/Classes/Http/Helper/ResponseInformationHelper.php#L205

assumes the complete header line is in `$cacheControlHeaderLine` and tries to strip `Cache-Control:` from it.

**Comment by kdambekalns** [comment]
As per Slack this seems to affect 6.3 as well…

**Comment by mhsdesign** [comment]
Well and luckily we dont support it anymore :D

So this seems to be fixed for flow >= 7 (see test https://github.com/neos/flow-development-collection/blob/e9e8e1b60d5147899e1a6a86d5aa3edc15c635c5/Neos.Flow/Tests/Unit/Http/Helper/ResponseInformationHelperTest.php#L235-L247)
