### ISSUE TITLE
BUG: uninitialized property state with objects Neos\Flow\var_dump()

### ISSUE THREAD

**Issue by mhsdesign** [neos/flow-development-collection#2664]
### Description

With PHP 7.4 came typed properties for classes. They have an uninitialized state at the beginning (before write) and 'must not be accessed before initialization'.

When using flows var_dump to dump such object with uninitialized (typed) properties, these lines will raise an error:
https://github.com/neos/flow-development-collection/blob/2e8d02fab6b66a0194271f332261ce3e51cb3a24/Neos.Flow/Classes/Error/Debugger.php#L291-L292

Since the property is accessed before initialization.

Something along these lines will solve the problem dirty:
```php
$property->setAccessible(true);
if ($property->isInitialized($object) === false) {
    $value = null;
} else {
    $value = $property->getValue($object);
}
```

Affected Versions

Flow:
Versions, that support at least 7.4

**Comment by sorenmalling** [comment]
I can confirm the issue
