### ISSUE TITLE
Failing HMAC validation leads to log flooding

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#2681]
### Description

When a request comes in and the HMAC validation fails, this causes a `CRITICAL` log message, as the resulting exception is not handled.

### Steps to Reproduce

1. have a website with some form to submit
2. wait for a spammer / security scan
3. marvel at the logs being flooded with `Exception #1320830018 in line 99 of /application/Packages/Framework/Neos.Flow/Classes/ObjectManagement/DependencyInjection/DependencyProxy.php: The given string was not appended with a valid HMAC.`

#### Expected behavior

Since this is hardly a critical issue, it should not cause `CRITICAL` log entries. `NOTICE` seems fine. And in terms of HTTP status this is clearly not a 500, but a 400.

#### Actual behavior

A lot of `CRITICAL` log messages and a response status of 500.

### Affected Versions

Neos: 5.3+
Flow: 6.3+

**Comment by kdambekalns** [comment]
See #2682 for a "twin issue" of this one.

**Comment by kdambekalns** [comment]
Why did I label this as "discussion"? Because I am not sure how to approach this best. My take would be to catch the related exceptions inside the `ActionController` in `processRequest()`, log a notice (pointing to an exception trace) and then finish with `throwStatus(400)`.

If this is really an issue that needs to be solved, the log can still be used to find out details. For that it needs the exception trace generated by `logThrowable()`. But that does not take into account any log level thresholds, so even if I filtered the notices from my log, I'd still get tons of those exception trace files.

Should I teach `ThrowableStorage` new tricks? Decide in the controller? Skip the exception trace?

**Comment by robertlemke** [comment]
First of all, the current error message is not really helpful as it contains "something about dependency injection and HMAC".

It would be nice though if we could store a stack trace for later inspection even if the log message is not CRITICAL. In hindsight it might have been better to separate logging and storage of error details.

So, I'm in favor of telling `ThrowableStorage` new tricks, but would have to take some time to think about a good API.

As for this particular exception, I like your suggestion to handle it in `ActionController` as you described.

**Comment by robertlemke** [comment]
Ah, right. But then the name `logThrowable()` is misleading. Also the comment "Writes information about the given exception into the log" is not correct.
