### ISSUE TITLE
Eel Helper `Array.push` auto cast string to array.

### ISSUE THREAD

**Issue by mhsdesign** [neos/flow-development-collection#2710]
### Description

The eel helper `Array.concat` auto casts non array arguments to arrays, how about to do the same 'magic' for `Array.push` ?

### Steps to Reproduce

use `Array.push` on a string like `Array.push("foo", "bar")`

#### Expected behavior

expect some auto cast magic, so we get `["foo", "bar"]` as result.

#### Actual behavior

type php error, `iterable` is expected.

## Usecase in Neos.Fusion:

this way one could add via `@process` in fusion super easily an additional css class, even if the class was a string before:

currently: https://github.com/neos/neos-development-collection/blob/a48994472e5dd0fec137f41a51bca5a710879c86/Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCollection.fusion#L32

**then, given any of these fusion configurations:**

**1.)**
`attributes.class = "class1 class2"`
**2.)**
`attributes.class = ${["class1", "class2"]}`
**3.)**
```
attributes.class = Neos.Fusion:DataStructure {
    class1 = "class1"
    class2 = "class2"
}
```

**the following process would be working for each config despite array or string**
`attributes.class.@process.addClass = ${Array.push(value, "class3")}`

after `@process`

**1.)**
`["class1 class2", "class3"]`
**2.)**
`["class1", "class2", "class3"]`
**2.)**
`["class1" => "class1", "class2" => "class2", 0 => "class3"]`

the rendered html would be for all the same:
`class="class1 class2 class3"`

**Comment by albe** [comment]
Very good and valid case in point you make there. One case where usability overrules API typing strictness. I like the idea 👍
