### ISSUE TITLE
PDOException on running flow command database:setcharset with PHP8 / MariaDB

### ISSUE THREAD

**Issue by vixe76** [neos/flow-development-collection#2724]
### Description

Running `./flow database:setcharset` with MariaDB / MySQL results in an PDOException

```
Exception in line 1853 of /data/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Connection.php: There is no active transaction

13 PDO::rollBack()
12 Doctrine\DBAL\Connection::rollBack()
11 Neos\Flow\Command\DatabaseCommandController_Original::convertToCharacterSetAndCollation("utf8mb4", "utf8mb4_unicode_ci", NULL, false)
10 Neos\Flow\Command\DatabaseCommandController_Original::setCharsetCommand("utf8mb4", "utf8mb4_unicode_ci", NULL, false)
9 Neos\Flow\Cli\CommandController_Original::callCommandMethod()
8 Neos\Flow\Cli\CommandController_Original::processRequest(Neos\Flow\Cli\Request, Neos\Flow\Cli\Response)
7 Neos\Flow\Cli\Dispatcher_Original::dispatch(Neos\Flow\Cli\Request, Neos\Flow\Cli\Response)
6 Neos\Flow\Cli\CommandRequestHandler::Neos\Flow\Cli\{closure}()
5 Closure::__invoke()
4 Neos\Flow\Security\Context_Original::withoutAuthorizationChecks(Closure)
3 Neos\Flow\Cli\CommandRequestHandler::handleRequest()
2 Neos\Flow\Core\Bootstrap::run()
1 require("/data/Packages/Framework/Neos.Flow/Scripts/flow.php")
```

### Affected Versions

Flow: 7.3

**Comment by sorenmalling** [comment]
@vixe76 Can you try and use the `$output` argument of the setcharset command, and execute the generated SQL directly to the databsae, to see if we get a error from maraidb?

**Comment by vixe76** [comment]
The generated SQL runs without any error because there isn't a transaction contained. 
I think the cause is changed PDO transaction handling in PHP 8 for some statements (CREATE TABLE, ALTER TABLE, etc.).

https://www.doctrine-project.org/projects/doctrine-migrations/en/3.3/explanation/implicit-commits.html

**Comment by bwaidelich** [comment]
This can be fixed in the command handler by removing the lines related to transactions (https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Command/DatabaseCommandController.php#L137)

For the record: Those transactions never worked (and could not be rolled back) but previously this was just ignored

**Comment by sorenmalling** [comment]
Well, that was quick 🐎

**Comment by kdambekalns** [comment]
Thanks for the report, @vixe76!

I have to admit that someone using / upgrading to PHP8 still is not on that charset, though. 😎

Or did you try running that for some other reason?

**Comment by vixe76** [comment]
The reason was a Flow 7.3 with PHP 8 Upgrade.

**Comment by kdambekalns** [comment]
> The reason was a Flow 7.3 with PHP 8 Upgrade.

Figured that much. I was just wondering if you actually needed that, because you were still on plain utf8. Pure curiosity. 😎

**Comment by vixe76** [comment]
You're right ... I'm really not needed that since the DB was with a prior Flow upgrade always on utf8mb. It was more a reflex to do that unreflected on every upgrade step by reading the [release notes](https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartV/ReleaseNotes/730.html) :see_no_evil:

**Comment by kdambekalns** [comment]
> You're right ... I'm really not needed

But probably very good you had that reflex, that's how you found a bug! 👍🏼
