### ISSUE TITLE
BUG: LockManager: defined refers to a constant but FLOW_LOCKHOLDINGPAGE used as environment

### ISSUE THREAD

**Issue by circleart** [neos/flow-development-collection#2798]
### Description

The possibility of specifying the path to the lock holding page in the LockManager is currently broken.
Reference is made here to a constant that has not been defined.
Since this constant is not used anywhere else, it should certainly be referring to the environment directly here, rather than to a constant.

### Steps to Reproduce

❗  The problem can only be checked in the production context.

1. Create an environment variable FLOW_LOCKHOLDINGPAGE and point to a document provided relative to the package directory. `Application/Acme.Foo/Resources/Private/CustomLockHoldingPage.html`
2. Lock your application using the LockManager's lockSiteOrExit Method.
3. Visit the application

#### Expected behavior

The HTML document `CustomLockHoldingPage.html`that was defined via the environment is displayed.

#### Actual behavior

The `Neos.Flow/Resources/Private/Core/LockHoldingStackPage.html` document is always displayed.

### Affected Versions

This feature was introduced with version 5.2. It seems it never really got to work. 
https://github.com/neos/flow-development-collection/pull/1381

Flow: 7.3.1

### Possible solution

Neos.Flow/Classes/Core/LockManager.php Line: 57

```php
    /**
     * Initializes the manager, removing expired locks
     */
    public function __construct()
    {
        $lockPath = $this->getLockPath();
        $this->lockPathAndFilename = $lockPath . md5(FLOW_PATH_ROOT) . '_Flow.lock';
        $this->lockFlagPathAndFilename = $lockPath . md5(FLOW_PATH_ROOT) . '_FlowIsLocked';
        $this->lockHoldingPage = getenv('FLOW_LOCKHOLDINGPAGE')
            ? FLOW_PATH_PACKAGES . getenv('FLOW_LOCKHOLDINGPAGE')
            : FLOW_PATH_FLOW . 'Resources/Private/Core/LockHoldingStackPage.html';
        $this->removeExpiredLock();
    }
```

On this occasion it would be possible to rename the corresponding environment variable from `FLOW_LOCKHOLDINGPAGE` to `FLOW_LOCK_HOLDING_PAGE`.

**Comment by kdambekalns** [comment]
OMG… the orignal PR even describes an environment variable, yet uses `defined()` as if it was a constant… 🙈

**Comment by albe** [comment]
> OMG… the orignal PR even describes an environment variable, yet uses `defined()` as if it was a constant… 🙈

Yes, I'm actually a monkey pretending to be a real developer 🤣

**Comment by circleart** [comment]
It's a pity, I was too slow. 😆 I already had a solution and wanted to provide that fix too.

@kdambekalns Maybe you should also offer the possibility that the environment is called FLOW_LOCK_HOLDING_PAGE as we discussed on slack. 

Additionally, I noticed that you can still define lockHoldingPage in the class.

```php
    /**
     * @var string
     */
    protected $lockHoldingPage;
```
