### ISSUE TITLE
FEATURE: Uri Builder should be able to create Psr URLs instead of strings

### ISSUE THREAD

**Issue by mficzel** [neos/flow-development-collection#2902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The uri builder creates urls as strings, this makes it needlessly harder to manipulate them as they often have to be converted to PSR urls for that.

### Possible Solution

The uriBuilder could get two new methods:

1. `buildUri(): Psr\Http\Message\UriInterface`
2. `uriForAction(....): Psr\Http\Message\UriInterface`

The existing methods `build(): string` and `uriFor(...): string` are kept for backwards compatibility but only call the new methods and convert the result to string.

**Comment by mhsdesign** [comment]
definitely! I find it quite amusing, that `uriFor` doesnt do it ^^

But i thought there was a rewrite or replacement of this uribuilder by @bwaidelich already in progress and always considered it legacy ;)

**Comment by mficzel** [comment]
@mficzel do you mean this https://github.com/neos/neos-development-collection/blob/9.0/Neos.Neos/Classes/FrontendRouting/NodeUriBuilder.php that is for nodes only and works on top of the existing uri-builder.

**Comment by mhsdesign** [comment]
My NamE iST nOt MficZel

i meant https://github.com/neos/flow-development-collection/pull/2744 ^^

**Comment by mficzel** [comment]
@mhsdesign Ah this pr looks really interesting.

**Comment by bwaidelich** [comment]
> I find it quite amusing, that uriFor doesnt do it ^^

The `UriBuilder` is one of the oldest parts of Flow, it gotta be more than 12 years old by now o.O
I only dared to touch it with #2744 but the feedback was rather low. Until now :)

And, to be honest, I completely forgot about this PR afterwards.. But I'm more than happy to help getting this into 8.2 or 9.0!

**Comment by mficzel** [comment]
Close this in favor of the approach in https://github.com/neos/flow-development-collection/pull/2744
