### ISSUE TITLE
BUG: const argument default value in function signature

### ISSUE THREAD

**Issue by simstern** [neos/flow-development-collection#2908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using constants in a method signature I'm getting the exception: `Class "Neos\Flow\Persistence\Doctrine\Proxies\__CG__\Foo\Bar\Domain\Model\Foo\Bar\Domain\Model\Baz" not found`

My function signature looks like this:

```
public function getBaz(string $status = Baz::STATUS_ACTIVE): ?Baz
{}
```

The exception occurs whether Baz is a proxied class or not (`@Flow\Proxy(false)`)

### Expected Behavior

The class Baz should resolve correctly.

### Steps To Reproduce

Using a const argument default value in function signature

### Environment

```markdown
- Flow: 7.3.7 (worked in prior versions)
- PHP: 8.1.1
```

**Comment by sorenmalling** [comment]
@simstern Can you attached the fully created proxy class here? Need to ensure that the `use` statements in the top is there :)

**Comment by simstern** [comment]
@sorenmalling thanks for your answer and sorry for the late response. 

I was looking into that following your response a few weeks ago but was caught up with another issue at that time and cannot remember where I left debugging to understand the problem 🙄 
However: I was not able to reproduce it again even with version 7.3.7 and then rolled that version out onto the systems where we first encountered the bug. All fine ever since. No clue, but fine to close this. Thanks!
