### ISSUE TITLE
FEATURE: Use PHPs hash_pbkdf2

### ISSUE THREAD

**Issue by reflexxion** [neos/flow-development-collection#2916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently the flow framework implements it's own calculation logic for generating `PBKDF2` hashes.

In `\Neos\Flow\Security\Cryptography\Algorithms` there is even a comment, that it should be replaced.

https://github.com/neos/flow-development-collection/blob/34ef4625b86f7888ef70dd71cfc78ba128f5ab0b/Neos.Flow/Classes/Security/Cryptography/Algorithms.php#L28-L29

### Possible Solution

As of PHP >= 5.5 [`hash_pbkdf2`](https://www.php.net/manual/de/function.hash-pbkdf2.php) was implemented. 
We can simply replace the current generation logic with this function.

IMO `\Neos\Flow\Security\Cryptography\Algorithms` can then be marked as `@deprecated`.

**Comment by kdambekalns** [comment]
How time flies… The function being available since PHP 5.5 made me wonder why we didn't use it right away back then. So I looked it up, and https://github.com/neos/flow-development-collection/commit/173ece18ad5c2f9d9b2cceec939759c35e9cf1fd is more than 11 years old! That was the time of PHP 5.3! 🤯

Great find! 🎉

**Comment by reflexxion** [comment]
Yes, I was wondering about that too :-D

But having that sentence
> Flow was one of the first PHP projects taking advantage of namespaces and other features introduced in PHP version 5.3.

in the docs also says something about it ;-)

I even think we should switch to [`password_hash`](https://www.php.net/manual/de/function.password-hash.php) for the BcryptStrategy (and probably integrate argon). Or use e.g. [`symfony/password-hasher`](https://github.com/symfony/password-hasher) at all.

**Comment by kdambekalns** [comment]
> I even think we should switch to [`password_hash`](https://www.php.net/manual/de/function.password-hash.php) for the BcryptStrategy

See https://github.com/neos/flow-development-collection/pull/2920
