### ISSUE TITLE
BUG: SimpleFileBackend->flushByTag() throws error with PHP 8

### ISSUE THREAD

**Issue by TheLalaMan** [neos/flow-development-collection#2929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We observe the following error since upgrading from PHP 7.4 to 8.1 in our code that uses `$this->cacheManager->flushCachesByTag($tag);` with custom SimpleFileBackend caches:

```
fread(): Argument #2 ($length) must be greater than 0
```

This prevents the tagged cache entries from being flushed. 

Unfortunately switching our custom caches to Redis did not solve the problem, it seems that the error will appear as long as there are SimpleFileBackend caches present. We have circumvented the issue now by not using `flushCachesByTag()` anymore and flushing the affected caches completely.

### Expected Behavior

`$this->cacheManager->flushCachesByTag($tag);` should not throw an error.

### Steps To Reproduce

- Switch to Production mode (error is not reproducible in Development because there no cache entries are created)
- Use `flushCachesByTag("RANDOM_TAG")` anywhere

### Environment

```markdown
- Flow: 7.3.7
- PHP: 8.1
- Neos 7.3.8
```

### Anything else?

See https://neos-project.slack.com/archives/C050C8FEK/p1653907831814319

**Comment by kdambekalns** [comment]
`flushByTag()` uses `findIdentifiersByTag()`, in which `readCacheFile()` is called. There the `fread()` call is done.

Two questions:

- can you provide the call that causes this? Is it [line 249](https://github.com/neos/flow-development-collection/blob/0807ca229d80e90babafb4c0fd40a4462f5df086/Neos.Cache/Classes/Backend/FileBackend.php#L249) or [line 250](https://github.com/neos/flow-development-collection/blob/0807ca229d80e90babafb4c0fd40a4462f5df086/Neos.Cache/Classes/Backend/FileBackend.php#L250)?
- can you provide (one) cache entry file that causes this?

**Comment by TheLalaMan** [comment]
A bit more detailled info: Error is thrown in https://github.com/neos/flow-development-collection/blob/0807ca229d80e90babafb4c0fd40a4462f5df086/Neos.Cache/Classes/Backend/SimpleFileBackend.php#L506

```
Exception in line 506 of /.../Packages/Libraries/neos/cache/Classes/Backend/SimpleFileBackend.php: fread(): Argument #2 ($length) must be greater than 0
```

From the exception file:
```
Exception in line 506 of /.../Packages/Libraries/neos/cache/Classes/Backend/SimpleFileBackend.php: fread(): Argument #2 ($length) must be greater than 0

58 fread()
57 Neos\Cache\Backend\SimpleFileBackend::readCacheFile()
56 Neos\Cache\Backend\FileBackend::findIdentifiersByTag()
55 Neos\Cache\Backend\FileBackend::flushByTag()
54 Neos\Cache\Frontend\AbstractFrontend::flushByTag()
53 Neos\Flow\Cache\CacheManager::flushCachesByTag()
...
```

**Comment by TheLalaMan** [comment]
> `flushByTag()` uses `findIdentifiersByTag()`, in which `readCacheFile()` is called. There the `fread()` call is done.
> 
> Two questions:
> 
>     * can you provide the call that causes this? Is it [line 249](https://github.com/neos/flow-development-collection/blob/0807ca229d80e90babafb4c0fd40a4462f5df086/Neos.Cache/Classes/Backend/FileBackend.php#L249) or ?
> 

It looks like [line 250](https://github.com/neos/flow-development-collection/blob/0807ca229d80e90babafb4c0fd40a4462f5df086/Neos.Cache/Classes/Backend/FileBackend.php#L250) is causing it, because I can comment it out and then the error does not occur. If I comment out line 249 instead, the error is there again.

**Comment by TheLalaMan** [comment]
>     * can you provide (one) cache entry file that causes this?

Let me get back to you on this, there are too many calls being logged if I put a debug print statement in the code. But I do not think it is related to our custom caches and what's inside them, because the error occurs even if those caches are not present yet...

**Comment by TheLalaMan** [comment]
Sorry, impossible to pinpoint the exact file- could you try to reproduce on your side? ;-)

**Comment by kitsunet** [comment]
https://github.com/neos/flow-development-collection/pull/2930 might help

**Comment by kdambekalns** [comment]
Re-opening, as I just saw this again. And I believe I have a super-simple fix…
