### ISSUE TITLE
BUG: (PHP 8.2 Support) Creation of dynamic property [...]::$Flow_Injected_Properties is deprecated

### ISSUE THREAD

**Issue by grebaldi** [neos/flow-development-collection#2946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running a basic Neos.Demo installation on PHP 8.2 currently leads to this (repeated) PHP deprecation message:
```
Deprecated: Creation of dynamic property Neos\Flow\ResourceManagement\Streams\ResourceStreamWrapper::$Flow_Injected_Properties is deprecated in /tmp/neos/Development/SubContextddev/Cache/Code/Flow_Object_Classes/Neos_Flow_ResourceManagement_Streams_ResourceStreamWrapper.php on line 591
```

Indeed, dynamic properties have been deprecated in PHP 8.2:
>  The creation of dynamic properties is deprecated to help avoid mistakes and typos, unless the class opts in by using the `#[\AllowDynamicProperties]` attribute. `stdClass` allows dynamic properties.
>
> Usage of the __get/__set magic methods is not affected by this change.

(see: https://www.php.net/releases/8.2/en.php)

### Expected Behavior

There is no deprecation message.

### Steps To Reproduce

* Set up a Neos Distribution running Neos.Demo on PHP 8.2
* See deprecation message on homepage

### Environment

```markdown
- Flow: 8.2
- PHP: 8.2
```

**Comment by kdambekalns** [comment]
Another way to see hundreds of such messages: Run the tests on 8.2… 😉
