### ISSUE TITLE
Introduce laminas code for proxy method rendering

### ISSUE THREAD

**Issue by robertlemke** [neos/flow-development-collection#3042]
As a preparation for the refactoring of Flow's proxy class building and the reflection service, introduce [laminas/laminas-code](https://github.com/laminas/laminas-code) for rendering the methods in our proxy classes.

**Comment by mhsdesign** [comment]
Hi - just out of interest (i bet you have this thought out already), but wasnt there a performance problem with laminas? https://github.com/neos/flow-development-collection/pull/2701#issuecomment-1078739551 or as i assume the performance problem was about laminas code reflection and not laminas/laminas-code?

**Comment by robertlemke** [comment]
> Hi - just out of interest (i bet you have this thought out already), but wasnt there a performance problem with laminas? [#2701 (comment)](https://github.com/neos/flow-development-collection/pull/2701#issuecomment-1078739551) or as i assume the performance problem was about laminas code reflection and not laminas/laminas-code?

Yes, that's the challenge I need to solve, but I'm on it.
