### ISSUE TITLE
FEATURE: Configure settings directly in a constructor argument

### ISSUE THREAD

**Issue by mhsdesign** [neos/flow-development-collection#3077]
```php
public function __construct(
    #[Flow\Configuration("fusion.autoInclude")]
    private array $autoIncludeConfiguration,
) {
}
```

this syntax combines the benefit, of both worlds:

- inject configuration is easily readable and configurable (you dont need to add a comment that you use Objects.yaml)
- constructor injection + objects yaml is easily testable -> as you can just specifiy a different parameter 

_Originally posted by @mhsdesign in https://github.com/neos/flow-development-collection/issues/2966#issuecomment-1445154289_
            

also related: https://github.com/neos/flow-development-collection/issues/3080

**Comment by robertlemke** [comment]
I'd prefer the existing established attribute though, and autowiring should still be possible:

```php
public function __construct(
    readonly private SomeOtherService $someOtherService,
    #[Flow\InjectConfiguration(path: 'fusion.autoInclude')]
    readonly private array $autoIncludeConfiguration,
) {
}
```

**Comment by mhsdesign** [comment]
yes okay i agree to use the same.

And the mentioned approach nearly works partially as is, but a bit differently.

you have to make it nullable and protected, that way it will actually just be found by flow as a normal property and initialized after the constructor has been called.


```php
public function __construct(
    readonly private SomeOtherService $someOtherService,
    #[Flow\InjectConfiguration(path: 'fusion.autoInclude')]
    protected ?array $autoIncludeConfiguration = null,
) {
}
```

but this is of course not ideal and actually has no benefit of having it in the constructor, as (i think i tested that) you cant set the value via constructor, as it will be overidden by the setting and the value is not available in the constructor (for constraint checks)

**Comment by mhsdesign** [comment]
See test that it currently works semi cool https://github.com/neos/flow-development-collection/pull/2974

**Comment by mhsdesign** [comment]
Currently the proxy class for 

```php
readonly class PrototypeClassL
{
    public function __construct(
        #[Flow\InjectConfiguration(path: 'tests.functional.settingInjection.someSetting')]
        public string $value,
    ) {
        assert($this->value !== '');
    }
}
```

would look like this:

```php
/**
 * A class of scope prototype with settings injected in the constructor
 * @codeCoverageIgnore
 */
readonly class PrototypeClassL extends PrototypeClassL_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        $arguments = func_get_args();
        parent::__construct(...$arguments);
        if ('Neos\Flow\Tests\Functional\ObjectManagement\Fixtures\PrototypeClassL' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {
        $this->Flow_Proxy_injectProperties();
        $result = null;


        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->value = \Neos\Flow\Core\Bootstrap::$staticObjectManager->get(\Neos\Flow\Configuration\ConfigurationManager::class)->getConfiguration('Settings', 'Neos.Flow.tests.functional.settingInjection.someSetting');
        $this->Flow_Injected_Properties = array (
          0 => 'value',
        );
    }
}

```


you can see that the setting will be injected with `Flow_Proxy_injectProperties()`, but not passed as constructor argument
