### ISSUE TITLE
BUG: Upgrading http-factories from 7.3.8 to 7.3.12 *downgrades* GuzzleHttp

### ISSUE THREAD

**Issue by jakobmerrild** [neos/flow-development-collection#3079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When upgrading the dependency on `neos/http-factories` from `7.3.8` to `7.3.12` the dependency on `guzzlehttp/psr7` is downgraded from `^2.1.1` to `^1.8.4`

I suspect this is because the `7.3.8` tag seems to accidentally be on a commit on the `8.x` branch https://github.com/neos/http-factories/blob/ddf639fb7d39460d87acd48c66b4e0c98be56a78/composer.json#L12
while `7.3.12` seems to once again be on the `7.x` branch: https://github.com/neos/http-factories/blob/8184b3a1c92add547400e3ef063b1095c87d7808/composer.json#L12

### Expected Behavior

I generally expect transitive dependencies to go in the same direction as dependencies on `neos` packages, i.e. if I bump my `neos` version transitive dependencies stay the same version or are bumped and vice versa.

### Environment

```markdown
- Flow: 7.3.12
- PHP: 8.1
```

**Comment by dlubitz** [comment]
Thanks for your contribution. Looks like an upmerge issue. Was handled properly for later versions.

https://github.com/neos/http-factories/blob/8.0.9/composer.json

**Comment by dlubitz** [comment]
Sorry for the inconvenience, but 7.3.8 seems to be a broken tag with wrong dependencies merged. With 7.3.9 everything looks fine.
