### ISSUE TITLE
BUG?: Injected property cannot be readonly

### ISSUE THREAD

**Issue by mhsdesign** [neos/flow-development-collection#3090]
> Error: Cannot initialize readonly property Neos\Flow\Tests\Functional\ObjectManagement\Fixtures\PrototypeClassM_Original::$configuration from scope Neos\Flow\Tests\Functional\ObjectManagement\Fixtures\PrototypeClassM

```
class PrototypeClassM
{
    #[Flow\InjectConfiguration('tests.functional.settingInjection.someSetting')]
    readonly public string $configuration;
}
```

it is debatable, if we should support this, but the current proxy code is faulty.

**Comment by sorenmalling** [comment]
Note from my experience: If you use constructor injection, you can use `readonly` properties

**Comment by kitsunet** [comment]
yep just use constructor injection
