### ISSUE TITLE
Flow & co `7.3.8` was accidentally tagged from the 8.2 branch

### ISSUE THREAD

**Issue by mhsdesign** [neos/flow-development-collection#3110]
This was suspected here and there and @kdambekalns could confirm this as well https://github.com/neos/flow-development-collection/pull/3081#issuecomment-1628668690:

> Right, as was pointed out here, the 7.3.8 was tagged off the `8.2` branch, as far as I can tell… 🙈
> 
> In the following image orange is `8.0`, yellow is `7.3` and red is `master`: <img alt="branch-point" width="1036" src="https://user-images.githubusercontent.com/95873/252310941-88bd1120-8934-48c6-8c5f-63639f981833.png">
> 
> At some point that was branched to be `8.2`, and the release was done on it:
> 
> <img alt="tag-point" width="1040" src="https://user-images.githubusercontent.com/95873/252311547-46c4355a-2b99-4de7-ac4a-3796e1e517ce.png">
> The tag now lives "disconnected" in the Git repository…

It caused confusion for example here: https://github.com/neos/flow-development-collection/issues/3079 and here https://neos-project.slack.com/archives/C050KKBEB/p1679399692161239

This cannot be fixed and im just documenting this for reference ;) - one needs to update to a correctly released patch ;)

Related https://neos-project.slack.com/archives/C050KKBEB/p1677569725807379

**Comment by mhsdesign** [comment]
@fcool wrote on slack

> Shouldn't we unpublish 7.3.8 then? If it carries the "wrong" dependencies composer will always explore this release again to solve dependency issues with the 7.x branch and will try to "upgrade" (or downgrade to 7.3.8 to upgrade other packages).

> If all other packages manage their dependencies strict enough it is only expensive in computational time. If not it will probably always select 7.3.8 as it is more compatible with other new releases.


Without doubt I would have done this for any little side project (pull out all magic to rewrite history) 
But I thought neos was to big to do anything like this. If there is a way with okayish implications I would love to see it.

**Comment by kdambekalns** [comment]
- We could delete the tag & release from GitHub and then from Packagist, too. 🤔
- Then again, projects I upgraded all picked newer dependencies correctly once 7.3.9 was released. 🤷
- Also checking the release branch against the release version in the Jenkins job would be cool. We could even determine the branch from the version. 😎😇

**Comment by mhsdesign** [comment]
It seems the same fate happened to Neos.Neos `7.3.9` https://neos-project.slack.com/archives/C04PYL8H3/p1694626966083459

This commit should only appear in 8.0:
https://github.com/neos/neos-development-collection/commit/c6bf5b874d55b7f1741d71ba5be5c9fad9bb5ba0

**Comment by kdambekalns** [comment]
> It seems the same fate happened to Neos.Neos `7.3.9`

That's why `7.3.10` was released the same day and `7.3.9` was never announced.
