### ISSUE TITLE
BUG: Since a recent commit, the date and time logged into the System.log is wrong

### ISSUE THREAD

**Issue by Toshi68k** [neos/flow-development-collection#3121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After a recent commit, the date and time logged into the `System.log` is wrong. Instead of logging the following correct date and time:

`Year-Month-Day Hour-Minute-Second`

the following is logged:

`Year-Month-Day Hour-Month-Minute`

### Expected Behavior

Logging of the following format  (_as before the commit_):

`Year-Month-Day Hour-Minute-Second`

### Steps To Reproduce

Logging something into the `System.log`.

### Environment

```markdown
- Flow: 8.3.3
- PHP: 8.2.8
```

### Anything else?

In a recent commit the creation of the current date and time changed from the `date()` function to `DateTime()->format()` function. The formatter passed to the `DateTime()->format()` function is wrong:

Problematic file:
`Packages/Libraries/neos/flow-log/Classes/Backend/FileBackend.php:244`

Before fix:
```php
$output = (new \DateTime())->format('y-m-d H:m:i') . $processId . ' ' . $ipAddress . $severityLabel . ' ' . str_pad((string)$packageKey, 20) . ' ' . $message;
```

After fix:
```php
$output = (new \DateTime())->format('y-m-d H:i:s') . $processId . ' ' . $ipAddress . $severityLabel . ' ' . str_pad((string)$packageKey, 20) . ' ' . $message;
```

**Comment by mhsdesign** [comment]
Hi ;) thanks for reporting and debugging. This seems to be a regressing due to https://github.com/neos/flow-development-collection/pull/3094

https://github.com/neos/flow-development-collection/commit/bfdab3d023a551f7396113b270a22683225d6fc3#diff-2561cac5034ec96ea2bb33f3f3363cadadc5a1ab72b91b2bf33ec2eb3173da14R244

**Comment by kdambekalns** [comment]
I even looked at that line during upmerging, and remembered changing it. Turns out I got confused by the awkward syntax of `strftime` placeholders… Sorry!
