### ISSUE TITLE
BUG: Doctrine packages got downgraded with 8.0

### ISSUE THREAD

**Issue by dlubitz** [neos/flow-development-collection#3127]
In Flow 7.3 we have (highest deps) follwing versions installed:
- doctrine/lexer (2.1.0)
- doctrine/orm (2.15.3) (or since yesterday 2.16.0)

But in Flow  8.x:
- Locking doctrine/lexer (1.2.3)
- Locking doctrine/orm (2.14.3)

This is caused by:
- **we upgraded psr/log from ^1.0 to "^2.0 || ^3.0" (from 7.3 to 8.x)**
- that forbids doctrine/migrations 3.1.5 (as seen above) and instead goes up to 3.4.2
- because 3.1.5 is psr/log 1
- while 3.4 is psr/log 2
- migration 3.4.2 has a new dependency on doctrine/deprecations with version ^0.5
- the older version 3.1.5 had no dependency on that at all
- so now we are limited to deprecations ^0.5
- which limits us to lexer 1.2.3 (no dependency) or 3.x (also no dependency on the deprecations
- 2.x depends on deprecations 1
- but lexer version 3 is not allowed by orm 
- so down to 1 it is

Conclusion:
- we should get doctrine/migrations up to ^3.5 allowing deprecations 1 again
- but that requires dbal 3.5 as well

See slack: https://neos-project.slack.com/archives/C050KKBEB/p1690979100024069

Affected Flow versions: >=8.0

**Comment by mhsdesign** [comment]
i had a similar issue in a customer project, where "doctrine/migrations" got downgraded to the version which has no dependency on "doctrine/deprecations".

This would have been no problem in my case as well if "doctrine/migrations:3.4.2" would just allow  "doctrine/deprecations:0.5 || 1.0".

So maybe we should just ask doctrine to loosen the constraint on "deprecations" in a patch fix "3.4.3" of "doctrine/migrations". This is imo the real problem and would also fix our problem as then we could install "doctrine/deprecations:1.0" which in turn allows all further updated doctrine dependencies.

**Comment by dlubitz** [comment]
This is fixed by doctrine.

https://github.com/doctrine/migrations/pull/1358

See also: https://neos-project.slack.com/archives/C050KKBEB/p1690979100024069
