### ISSUE TITLE
FEATURE: Rotate / clean up exception dumps similar to log files

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#3158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Flow rotates it's log files as configured, but does not do anything like that to the exception dumps it writes to disk. This is something that can be unexpected and unless monitored could lead to issues with disk space and general "information overload".

### Possible Solution

When rotating log files, also check exception dumps and remove the ones older than a certain threshold and/or if there are more than a certain number of those.

**Comment by mhsdesign** [comment]
Can this be closed as implemented via https://github.com/neos/flow-development-collection/pull/3187
