### ISSUE TITLE
BUG: neos/flow  9.0.x-dev requires neos ~8.3.0 packages

### ISSUE THREAD

**Issue by ghost** [neos/flow-development-collection#3168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The composer.json in the version 9 branch https://github.com/neos/flow/blob/9.0/composer.json requires neos ~8.3.0 packages. This triggers an composer error:

    Problem 1
      - Root composer.json requires neos/flow 9.0.x-dev -> satisfiable by neos/flow[9.0.x-dev].
      - neos/flow 9.0.x-dev requires neos/cache ~8.3.0 -> found neos/cache[8.3.0, ..., 8.3.x-dev] but it conflicts with your root composer.json require (9.0.x-dev).

if you have an early 9er installation like:

        "neos/flow": "9.0.x-dev",
        "neos/cache": "9.0.x-dev",
        "neos/eel": "9.0.x-dev",
        "neos/error-messages": "9.0.x-dev",
        "neos/utility-objecthandling": "9.0.x-dev",
        "neos/utility-mediatypes": "9.0.x-dev",
        "neos/utility-arrays": "9.0.x-dev",
        "neos/utility-files": "9.0.x-dev",
        "neos/utility-opcodecache": "9.0.x-dev",
        "neos/utility-schema": "9.0.x-dev",
        "neos/utility-unicode": "9.0.x-dev",
        "neos/flow-log": "9.0.x-dev",
        "neos/http-factories": "9.0.x-dev",
        "neos/utility-pdo": "9.0.x-dev",
        "neos/fluid-adaptor": "9.0.x-dev",

### Expected Behavior

The composer.json requires neos ~9.0.0 like it has been before

https://github.com/neos/flow/blob/b32fdef71183000a7d13b5bc8e86a4d5ee242486/composer.json

### Environment

```markdown
- Flow:
- PHP:
```

### Anything else?

Relates: #3035

**Comment by kdambekalns** [comment]
Fixed, see #3186.

Thanks @kitsunet!
