### ISSUE TITLE
TASK: 9.0 Remove php version compares across the codebase

### ISSUE THREAD

**Issue by mhsdesign** [neos/flow-development-collection#3177]
we dont support php 7x anymore and have no need for 

```
if (PHP_MAJOR_VERSION >= 8) {
```

**Comment by ahaeslich** [comment]
@mhsdesign isn't this related or a duplicat of #3085? Depending on how you want to interpret both descriptions 😉

**Comment by mhsdesign** [comment]
Hahah 😂 I didn’t found it via search and didn’t know if I dreamed of creating this issue.

**Comment by ahaeslich** [comment]
😎
