### ISSUE TITLE
FEATURE: Support Doctrine ORM 3.0

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#3204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Doctrine 3.0 is close to being released, and would be a match for a breaking Flow release… ;)

**Comment by mhsdesign** [comment]
Related `doctrine/dbal` version 3 updated https://github.com/neos/flow-development-collection/pull/2637

**Comment by kitsunet** [comment]
Fixed with https://github.com/neos/flow-development-collection/pull/2637
