### ISSUE TITLE
BUG: utilities-mediatypes can't handle streams anymore

### ISSUE THREAD

**Issue by Kleisli** [neos/flow-development-collection#3246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After this recent update to the mediatypes package https://github.com/neos/utility-mediatypes/commit/243b9e1240fa32123561021665172277ca3a3e13 (see https://github.com/neos/flow-development-collection/pull/3172), when I try to select an unsplash image with package for a content element, there is a warning when `neos/media/browser/asset-proxies/import.json` is called

`
Warning: mime_content_type(): Stream does not support seeking in /var/www/html/Packages/Libraries/neos/utility-mediatypes/Classes/MediaTypes.php line 1844
`

### Expected Behavior

The function that contains line 1844 is `getMediaTypeFromResource()` and it is called from 
`Neos\Flow\ResourceManagement\ResourceManager->importResource()`

The first parameter `$source` from `importResource` is passed to `getMediaTypeFromResource()` and it is explicitly stated that it can also be a stream (`A URI (can therefore also be a path and filename) or a PHP resource stream(!) pointing to the PersistentResource to import`), therefore `getMediaTypeFromResource()` ahould also be able to handle streams.

According to the docs (https://www.php.net/manual/en/function.mime-content-type.php) `mime_content_type()` is able to handle a `resource` and therefore also streams, but still something goes wrong. I just can't tell where the real bug is.. 

### Steps To Reproduce

Install dl/assetsource-unsplash and select an unsplash image for a content element with a property of type `Neos\Media\Domain\Model\ImageInterface`

### Environment

- PHP 8.2.11
- neos/utility-mediatypes 8.3.6
- dl/assetsource-unsplash 2.1.0
- neos/neos 8.3.6

Everything works fine, when I lock neos/flow and neos/utility-mediatypes to version 8.3.5

### Anything else?

CC @mficzel as author of the mediatypes package change and @daniellienert as author of assetsource-unsplash

**Comment by kitsunet** [comment]
good catch, sorry for this breakage!

**Comment by kitsunet** [comment]
Note to us: I think this is not quite the easy fix, becaue we definitely do not want to unwrap a stream just to figure out IF we need to do something as that would load any bigger file fully into memory.

**Comment by Sebobo** [comment]
We have super strange issues also most likely related to the same change in a large project with the Flownative S3 adapter.
Many persistent resources are not properly uploaded to S3. I can reproduce the problems with a local dockerized minio instance. Sadly I don't see anything in any log, why it wouldn't upload the file.
If I revert the https://github.com/neos/utility-mediatypes/commit/243b9e1240fa32123561021665172277ca3a3e13 change then uploads work again. 
In the customer project we had to rollback the Flow update and then reupload all affected assets, which was quite an issue as Flow doesn't really like to reimport the same asset twice.

@kitsunet if you have any idea how to debug this, I can offer a broken Neos via screen share.

**Comment by patricekaufmann** [comment]
We also ran into a very strange issue today and this topic seems like a good place to post about it. We noticed this when image thumbnails were corrupted when trying to generate a thumbnail that is larger than the original asset dimensions.

**When working with S3 storage**, inside ResourceManager::importResource, , at some point in time $source refers to a remote stream via the AWS S3 Stream Wrapper. The call of `mime_content_type` inside MediaTypes::getMediaTypeFromResource kind of corrupts the stream and leads to broken images in further procedures.

We did not get any exceptions, but the origin is the same as in the initial issue description.

**Comment by kitsunet** [comment]
Yep it does "corrupt" the stream by reading from it, given that this is a io stream it is not seekable so it will never rewind, any bytes read after the initial ones used up by mime_content_type will be missing from the resulting resource. We had a longer discussion about this today in the team meeting and as you see decided to revert this for now and fix it another way.

**Comment by dlubitz** [comment]
We tagged a new bugfix release, which reverts the latest changes. Please update to the latest Flow version.

https://discuss.neos.io/t/flow-bugfix-releases-7-3-18-8-0-15-8-1-11-8-2-9-8-3-7/6462
