### ISSUE TITLE
DateTimeRangeValidator not usable caused by DateFormat validation or incorrect translation format type 

### ISSUE THREAD

**Issue by andigehle** [neos/flow-development-collection#3323]
When using the DateTimeRangeValidator and submitting a form with such an date which is invalid, the following error messages are used: (See the placeholder definition in lower case "datetime")
https://github.com/neos/flow-development-collection/blob/8b2f13ee3f940bbf25937929eeec798a97f61817/Neos.Flow/Resources/Private/Translations/en/ValidationErrors.xlf#L33-L39

The translation string like {1, datetime, datetime} goes through the DateTimeFormatter and validates by DateReader::validateFormatType
https://github.com/neos/flow-development-collection/blob/8b2f13ee3f940bbf25937929eeec798a97f61817/Neos.Flow/Classes/I18n/Cldr/Reader/DatesReader.php#L349
The validation here checks hard on camelcase value "dateTime" and so the translation placeholder "datetime" throws an error to be not a valid format.

Exception: Provided formatType, "datetime", is not one of allowed values.
Trace:
Neos\Flow\I18n\Cldr\Reader\DatesReader_Original::validateFormatType("datetime")
Neos\Flow\I18n\Formatter\DatetimeFormatter_Original::format(DateTime, Neos\Flow\I18n\Locale, array|1|)
Neos\Flow\I18n\FormatResolver_Original::resolvePlaceholders("The given date must be after {0,datetime,datetime}", array|1|, Neos\Flow\I18n\Locale)

Possible solution:
 - Change the placeholder string in all translation files for DateTimeRange from "datetime" to "dateTime"

**Comment by jonnitto** [comment]
Hey, @andigehle, thank you for your issue. I've tested this and it is true. 
The string in the translation files should be changed from `{0,datetime,datetime}` to `{0,datetime,dateTime}`. And the variant with the `1` at the start to, of course

**Comment by jonnitto** [comment]
@kdambekalns Am I wrong, or are the validations errors not in weblate?

**Comment by kitsunet** [comment]
Doesn't look like it, weird! I guess that is a mistake and they should go in there.

**Comment by jonnitto** [comment]
I've created a PR. Currently, the date time validator is not useable at all. Seems like nobody used it before

**Comment by KarstenDambekalns-eaton** [comment]
Yeah, Weblate lacked an addon for component discovery… 🤷‍♂️
