### ISSUE TITLE
On a clean installation a doctrine:migrationgenerate creates migrations for base tables

### ISSUE THREAD

**Issue by daniellienert** [neos/flow-development-collection#478]
## Problem Description

On a clean installation. When you run `doctrine:migrationgenerate` before a first run
of `doctrine:migrate` migrations for the base tables are generated.
## Suggested Behavior

The command `doctrine:migrationgenerate` checks if open migrations exist and tells the user to run `doctrine:migrate` first.

**Comment by kitsunet** [comment]
That sounds reasonable. I would maybe add some "force" argument to override this, just in case. Maintenance and such...

**Comment by dfeyer** [comment]
I agree with @kitsunet 

Good idea, but add ```--force``` to support side case

**Comment by bwaidelich** [comment]
Additional idea: Without the `--force` flag Flow should never create an empty Migration but state sth like ```The database schema is up to date, no migration necessary```
