### ISSUE TITLE
Better support for final classes and private methods

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#496]
## Problem Description
In order to make use of dependency injection and AOP in general user-land classes must not be `final`. Besides, injected properties can not be `private` (but have to be `protected` or `public`).
Having everything extensible might be convenient but it can also have undesired side-effects so we should at least allow users to define a more strict API, using the `final` and `private` keywords.

This should be possible for example:

```php
final class SignUpUser implements CommandInterface
{
    private $username;
    private $password;
    private $hashedPassword;

    /**
     * @Flow\Inject
     * @var HashService
     */
    private $hashService;

    public function __construct(string $username, string $password)
    {
        $this->username = $username;
        $this->password = $password;
    }

   public function initializeObject()
   {
        $this->hashedPassword = $this->hashService->hashPassword($this->password);
        unset($this->password);
   }
}
```

This currently doesn't work because `final` classes are completely skipped from Flows object configuration. Besides `$hashService` wouldn't be allowed to be `private`.

Note: In a related matter I'd love to be able to allow `initializeObject()` to be `protected`.

## Suggestion

1. Don't skip `final` classes in `ConfigurationBuilder::buildObjectConfigurations()`
2. Don't skip `final` classes in `ProxyClassBuilder::build()` and `ProxyClassBuilder::getProxyableClasses()`
3. Adjust regex in `Proxy\Compiler::cacheOriginalClassFileAndProxyCode()` to remove the `final` keyword from `<class>_Original` declaration (and maybe add it to the new proxied `<class>` declaration)

Apart from adjusted tests there's some more work required to make this work. i.e. Flow complains about missing annotations:  `[Semantical Error] The class "\TYPO3\Flow\Annotations\Entity" is not annotated with @Annotation.`

**Comment by kitsunet** [comment]
How do you build a proxy for a final class?

**Comment by bwaidelich** [comment]
@kitsunet see suggestion 3.

**Comment by kitsunet** [comment]
no, not how can we build one, but it is  final, any proxy would result in a php fatal because it would extend a final class

**Comment by bwaidelich** [comment]
The ProxyBuilder would *remove* the `final` and instead add it to the Proxy class resulting in sth like
```php
class SignUpUser_Original implements CommandInterface
{
  // ...
}
final class SignUpUser extends SignUpUser_Original implements \TYPO3\Flow\Object\Proxy\ProxyInterface {
  // ...
}
```

**Comment by kitsunet** [comment]
uhhh, I see, mmm. Not sure I like that,.
Private properties? You cannot access them in the proxy class (and adding a new private there doesn't help because that agian is not accessible by the original code) .
our lazy injections and proxy traits are also even outside of the proxy class itself making this even more difficult.

**Comment by bwaidelich** [comment]
True, that restriction of the private fields make sense and we don't want to change that and can't add a wrapper (w/o using runtime reflection).
However, I would still very much like to be able to use `final` classes

**Comment by kitsunet** [comment]
Feels odd, but sure, sounds like a possible way :)

**Comment by stephanschuler** [comment]
I'm not sure if I like this. I do like the idea of being able to use private properties and the final keyword. But in my mind, the most likely way of implementing this means rewriting the original class file to an extent I'd rather not have my code to be rewritten.

While I do see a use case for private properties and protected methods I completely fail to think of a situation where proxy class building should be allowed to even touch private methods. It's something like "whoever creates anything private most likely wants to be as explicit as possible about it".

So don't count this for a vote at all but only thinking out loud :).

An option for private properties filled by DI could be: Create a trait that provides a protected method `__setPropertyByDI($propertyName, $value)`, make the original class file use that trait and make the proxy class call that newly introduced setter.

Regards,
Stephan.

**Comment by bwaidelich** [comment]
Let's forget about the private fields for injections. After all: If I can mark my class `final` I don't care about the fields being `protected` too much anyways ;)
Re

> rewriting the original class file to an extent I'd rather not have my code to be rewritten

Fair enough, but all that changes is that the `final` keyword would move from `YourClass_Original` to `YourClass`. And that only if you decided to _use_ `final` in the first place (meaning: your existing code would not be rewritten in any other way).

A more "sensitive" way to make this work could be an explicit `proxy(true)` if you want that new support:

```php
/**
 * @Flow\Proxy(true)
 */
final class SignUpUser implements CommandInterface
{
 // ...
```

Currently the final classes are just **silently** skipped and DI does not work for them. That's gotta change IMO

**Comment by albe** [comment]
:+1: for supporting final together with explicit "I want that still proxied" annotation

**Comment by robertlemke** [comment]
I think the trick to remove the `final` keyword and add it again in the proxy class is okay in this case. After all it's not worse than renaming the original class ;-)

👍

**Comment by kitsunet** [comment]
👍 for explicitly marking those classes as "want proxy"
