### ISSUE TITLE
Content security (EntityPrivilege) to be written

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#521]
Jira issue originally created by user @RafaelKa:

Very nice feature is not documented :/

 Jira-URL: https://jira.neos.io/browse/FLOW-117

**Comment by RafaelKa** [comment]
Can be closed.

done in [84bcc7a0232be3a34f30865398d79c2fbeb7806a](https://github.com/neos/flow-development-collection/commit/84bcc7a0232be3a34f30865398d79c2fbeb7806a)
