### ISSUE TITLE
Remove mentions of "voter" in Code and Documentation

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#523]
Jira issue originally created by user @bwaidelich:

The [security documentation](http://docs.typo3.org/flow/TYPO3FlowDocumentation/latest/TheDefinitiveGuide/PartIII/Security.html) still mentions "voters" even though they have been removed with FLOW-11

Apart from that we should adjust/remove the `TYPO3.Flow.security.authorization.allowAccessIfAllVotersAbstain` setting!

Option A: Rename to `grantAccessIfAllPrivilegesAbstain` and add code migration

Option B: Remove setting as its probably never used and would have unwanted effects

 Jira-URL: https://jira.neos.io/browse/FLOW-125

**Comment by RafaelKa** [comment]
Hello,
👍 for B.

**Comment by kitsunet** [comment]
This still needs to be done... Pinging @bwaidelich

**Comment by bwaidelich** [comment]
Thanks for the reminder. I was sure I had fixed this already.. _Checking_

**Comment by bwaidelich** [comment]
The Security Documentation has been adjusted with 78ad2d0f3752321f9e1e4d1591d57e82d0821ec5 or do you see any remaining mention of "voter", @kitsunet / @RafaelKa ?

**Comment by kitsunet** [comment]
Oh right, I did a quick search and found a few in Settings, PolicyService and PrivilegeManager, but not in docs. Close if you think it's fine.

**Comment by bwaidelich** [comment]
OK, closing it for now. Lets create a new ticket if this pops up somewhere
