### ISSUE TITLE
TrustedProperties don't include the uuid value

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#524]
Jira issue originally created by user econic:

If you render an edit/delete form, you can just replace the hidden **identity input to another entity's uuid that you have read access on and voilà, you can edit this entity.

Therefore i suggest the trustedProperties to contain also the **identity's value.

Since as a developer you would expect this to be checked, i regard this bug as critical because this opens up security vulnerabilities in all flow applications with edit/delete forms.

 Jira-URL: https://jira.neos.io/browse/FLOW-138

**Comment by RafaelKa** [comment]
I think @foerthner could help to choose the right way, 
but anyway my 5 cents:

Currently ["Content Security Framework"](http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Security.html#authorization) does not provide standard Privileges for entity-properties. Also as far as i know the current best way is this trustedProperties stuff(aka do not print form field for properties, which are not allowed to be changed. Can f.x. be done by wrapping with ifHasRole or ifAccess VHs). 

Maybe following will work(not tested!).
```
privilegeTargets:
  'TYPO3\Flow\Security\Authorization\Privilege\Method\MethodPrivilege':

    'Acme.MyPackage:MyModelDisallowedForEditingProperties':
      matcher: 'method(Acme\MyPackage\Domain\Model\MyModel->set[PropertyA|PropertyB|PropertyC|PropertyX]())'
```
I'm not sure if MethodPrivilege on entity setters will work(are they called on updateAction at all)?!

So if MethodPrivilege on setters snippet does not prevent updating the "not allowed" properies and the "trustedProperties"-Stuff must be used, 
then i'm for adding Entities-UUID to the __trustedProperties 👍 .

**Comment by kitsunet** [comment]
Nothing happened here, new entity security can handle the case, therefore closing for now.
