### ISSUE TITLE
Optimize session cache data writes

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#525]
Jira issue originally created by user @hlubek:

The session cache backend currently writes data back for every _access_ (including read-only requests) at the end of each request.

For Neos this involves the following keys (individual cache entries) for **each request** (also in the frontend), while having an active session:
- lastVisitedNode
- TYPO3_Flow_Security_Accounts
- TYPO3_Flow_Object_ObjectManager

We could greatly optimize I/O and cache file contention by checking on a cache frontend level if the data was actually changed. The idea is to store md5 sums of the data that was fetched (`get`) and comparing that on subsequent `set` operations and doing nothing if they are equal. Doing that on the frontend layer would not require an additional serialize call.

 Jira-URL: https://jira.neos.io/browse/FLOW-147

**Comment by kitsunet** [comment]
But then you also need to include tags and lifetime to the hash (and tags might be in different order), otherwise it will become impossible to "change" lifetime or tags for an existing entry.

**Comment by mficzel** [comment]
Plan of Attack:

1. Add lifetimeThreshold to only update changed the session metadata every xxx seconds 
2. Add first RuntimeSessionDataCache to Session to avoid calling cache->set for values that have been read and are unchanged that would be used in Session->getData. hasData and putData

**Comment by mficzel** [comment]
There is also a package that for locking sessions that night be related https://github.com/digital-competence/FlowSessionLock
