### ISSUE TITLE
EEL AttributeFilter can't deal with references type

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#529]
Jira issue originally created by user hanshoechtl:

I'm trying to render backreferences on my current page.
Nodes have references to my current page and I'd like to render them, by using this:

```
snippets = TYPO3.Neos:ContentCollection
snippets {
    collection = ${q(site).children('[instanceof Vendor.MySite:Snippet]').filter('[pagesToDisplay *= "'<ins>node</ins>'"]')}
}
```

**pagesToDisplay** is my property of type references.

I figured out that the value of the property pagesToDisplay is being evaluated to an array of Node-objects (which is correct)
inside the method matchesAttributeFilter:

```
protected function matchesAttributeFilter($element, array $attributeFilter) {
        if ($attributeFilter['Identifier'] !== NULL) {
            $value = $this->getPropertyPath($element, $attributeFilter['Identifier']);  // <- HERE
        } else {
            $value = $element;
        }
        $operand = NULL;
        if (isset($attributeFilter['Operand'])) {
            $operand = $attributeFilter['Operand'];
        }

        return $this->evaluateOperator($value, $attributeFilter['Operator'], $operand);  // <- only instanceof has special treatment in this method
    }
```

But because I'm not doing an "instanceof" operation, this array is being passed to the method evaluateOperator of TYPO3\Eel\FlowQuery\Operations\Object\FilterOperation which only does a strpos comparison.
So I guess this is only supposed to work on string-properties, but I suggest the contains filter-operation to work on arrays (here array of nodes) to.

 Jira-URL: https://jira.neos.io/browse/FLOW-154

**Comment by iseries** [comment]
This is very old and maybe forgotten but still a problem in current installations. 
https://discuss.neos.io/t/access-nodes-references-from-plugin/4416

I just want to bring it up again.

**Comment by sorenmalling** [comment]
I suggest this issue is moved to `neos-development-collection` since it's purely related to the CR and Node handling. 

This in order to keep the issues where others might search for them

**Comment by albe** [comment]
This should be solved as of https://github.com/neos/flow-development-collection/pull/1082, no?

**Comment by sorenmalling** [comment]
I'd say yes
