### ISSUE TITLE
Advices for parent class' methods throw warning when called in subclass

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#530]
Jira issue originally created by user vertexvaar:

Reviving an old Ticket because the bug occured to me: https://forge.typo3.org/issues/47271

Original Text:
I have a structure with a parent class and several subclasses. I want a before advice for all set\* methods of these classes.

Some methods from the parent class are invoked on objects of the subclass.
When having the advice before the set\* methods, the following error occurs:

Notice: Undefined property: MyPackage\Domain\Model\MySubclass::$Flow_Aop_Proxy_targetMethodsAndGroupedAdvices in .../Data/Temporary/Development/Cache/Code/Flow_Object_Classes/MyPackage_Domain_Model_MyClass.php line 629
where MyClass is the parent class of MySubclass.

The reason seems to be that the AOP properties of a class are marked as "private", which makes them inacessible from parent (and subclass) methods. I don't know if this could/should be solved by changing the type to protected, as this might raise other issues (I'm not too deeply into the AOP code of Flow), but AFAIS this is a possible solution.

 Jira-URL: https://jira.neos.io/browse/FLOW-155

**Comment by kitsunet** [comment]
This should be fixed from all I see, closing unless reopened.
