### ISSUE TITLE
Improve exception message for AccessDeny interceptor

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#531]
Jira issue originally created by user benjaminrau:

When i am logged in and authenticated as neos administrator every api request for my public rest api fails with a 403 Uncaught exception #1216919280 TYPO3_Flow_Security_Authorization_RequestFilter.php: You are not allowed to perform this action.

The api is allowed for "Everybody" and is used in the frontend. After i log out from the backend all api calls pass again. Also when i remove the package from authentication requestPatterns it works well.

Philipp Maier and Bastian Waidelich pointed out it might be due to a CSRF error - and improved error message would help oneself to find this out.

 Jira-URL: https://jira.neos.io/browse/FLOW-353

**Comment by kitsunet** [comment]
Related to #660
