### ISSUE TITLE
JsonView accepts encoding options

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#533]
Jira issue originally created by user pumatertion:

JsonView accepts encoding options
json_encode should support multiple bitmask options
see: http://www.php.net/manual/en/json.constants.php

 Jira-URL: https://jira.neos.io/browse/FLOW-157

**Comment by daniellienert** [comment]
Just looked into the JSONView. Seems that defining options for the Json Encoding are possible. So I  close this issue. Please don't hesitate to reopen it, if I am wrong.
