### ISSUE TITLE
Advices are called multiple times in inheritance hierarchies

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#534]
Jira issue originally created by user mhelmich:

I'm not sure if this behaviour is intentional; please feel free to yell if this is NOT a bug. I also noticed that it is very similar to FLOW-155 reported by [~vertexvaar] and can possibly be fixed with the same proposed solution.

I have a class hierarchy, and an advice around a method in the parent class. When calling the method (which calls it's parent method) on an instance of the subclass, the advice is called twice.

Simple example:

```
abstract class AbstractFoo {
    public function hello() {
        echo "Hello world.";
    }
    public function bye() {
        echo "Goodbye world.";
    }
}
```

```
class ConcreteFoo extends AbstractFoo {
    public function hello() {
        parent::hello();
        echo "Hallo Welt!";
    }
}
```

```
/****
 * @Flow\Aspect
 */
class HelloByeAspect {
    /****
     ** @Flow\Around("method(**.->hello())")
     */
    public function myHelloAspect(JoinPointInterface $joinPoint) {
        echo "called hello()";
    }
    /****
     ** @Flow\Around("method(**.->bye())")
     */
    public function myByeAspect(JoinPointInterface $joinPoint) {
        echo "called bye()";
    }
}
```

When calling `ConcreteFoo->hello`, I'd expect the advice to be invoked once; but it is actually invoked twice.
**The same goes for `ConcreteFoo->bye`, which isn't even overwritten in `ConcreteFoo`, but the advice is called twice nevertheless.**

My best guess is that, the `Flow*Aop_Proxy*methodIsInAdviceMode` property in the proxy classes is actually supposed to prevent this. However, this property is private and thus not visible in super(!)classes. Changing the visibility of this property to `protected` helps.

I tested with Flow 2.3, but probably occurs in earlier releases and in master, too. Will push a patch into Gerrit shortly.

 Jira-URL: https://jira.neos.io/browse/FLOW-158

**Comment by sorenmalling** [comment]
Related ticket #210 has been closed in january 2016 - i suggest that this ticket will be closed

@albe Can you agree on this?

**Comment by albe** [comment]
Yes, let's close this.

To quote @kitsunet from the PR:

> IMHO the current behavior does make sense. If you advice an Interface method ALL implementations should trigger the pointcut. If that method does a parent call, well then the advice should be called twice. IMHO that's just reasonable. If you want to target only one of the two then you target the specific class.

Targeting `method(**->...)` is equivalent in that regard. I still find it a bit unintuitive and the fact that `bye()` is adviced twice, even though it is not overridden is probably still debatable, but just an artifact of how we build advice proxies by inheritance.

If someone feels like debating this again with new points of view, feel free to reopen!
