### ISSUE TITLE
Table of contents links of FLOW's "The definitive guide" are broken

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#538]
Jira issue originally created by user mostwanted:

http://flow.typo3.org/documentation/guide

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11514/Screenshot+at+Dez.+22+15-43-30.png) 

 Jira-URL: https://jira.neos.io/browse/FLOW-166

**Comment by RafaelKa** [comment]
There are some old links around internet 
f.x. 
h-ttp://flow.typo3.org/documentation/guide redirects to h-ttps://flow.neos.io/documentation/guide/ which responses with 500.

This could scare off potencial users/contributors.

**Comment by kitsunet** [comment]
No longer applicable.
