### ISSUE TITLE
Missing possibility to change the path to the file for locked site

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#539]
Jira issue originally created by user benjamink:

When updating a site or when the cache is empty, the user gets a short message that the service is currently not available. It would be nice to have a setting to change the default html-template file like 

TYPO3.Flow.core.pathToLockedSite: 'resource://My.Package/.../MyLockedSitePage.html'

or sth. similar.

 Jira-URL: https://jira.neos.io/browse/FLOW-168

**Comment by sorenmalling** [comment]
It is possible to override the document displayed when the site is locked via the constant

FLOW_LOCKHOLDINGPAGE

See here for the source:
https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Core/LockManager.php#L57
