### ISSUE TITLE
Persisted DateTime losing timezone

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#544]
Jira issue originally created by user pumatertion:
1. Persisting a DateTime with timezone America/Caracas f.e.
2. $this->persistenceManager->clearState();
3. Query the datetime from db.

Results in: @see attached file.

We are losing timezone diff in this case.
imho the value of a datetime should be converted before persisting into utc.
on reading this datetime again, it should be converted in the configured timezone.

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11701/Bildschirmfoto+2015-01-09+um+14.35.49.png) 

 Jira-URL: https://jira.neos.io/browse/FLOW-174

**Comment by albe** [comment]
This is not really something that the Framework can solve in a good way. See https://www.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/working-with-datetime.html#handling-different-timezones-with-the-datetime-type for some explanations and a solution.

Closing this for now. If someone sees fit, feel free to reopen with a suggestion on how a Framework-Level solution could look.
