### ISSUE TITLE
Add TYPO3 Flow to list of tested frameworks on HHVM website

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#548]
Jira issue originally created by user ryzy:

We should add TYPO3 Flow to the list of automatically tested frameworks on HHVM site: http://hhvm.com/frameworks/

From what I understand, the HHVM team pays attention to these tests and it gives them a clue what other incompatibilities with PHP are still there. In a long term, instead of workarounds in Flow we would have it fixed in HHVM.

 Jira-URL: https://jira.neos.io/browse/FLOW-195

**Comment by RafaelKa** [comment]
Here is discussion about [HHVM support - no longer important](https://discuss.neos.io/t/hhvm-support-no-longer-important/726)

**Comment by kitsunet** [comment]
@albe in above discuss thread you said you worked with HHVM, would you comment about current support in thread?

I would close this ticket for now as the frameworks page seems to be gone without replacement.
