### ISSUE TITLE
core migration inconsistencies

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#551]
Jira issue originally created by user pumatertion:

My 7 cents about migration commands.
Is it realy needed to make a difference between core:migrate / doctrine:migrate and if its needed, their generic arguments should be unified (f.e. --verbose vs. --quiet).

1) "flow migrate" (to run all necessary migrations)
2) "flow migrate --type=doctrine|core" (to make the difference wich is currently done by different commands)
3) Generic "--dry-run" argument or at least "flow core:migrate --dry-run | flow doctrine:migrate --dry-run"
4) Generic "--status or --version" argument. Currenlty doctrine:migrate --version and core_migrate --status has the same job for me: Simply getting current state information of the migration.
5) Generic "--verbose or --quiet" argument. Currenlty doctrine:migrate is using --quiet and core:migrate using --verbose.
6) "flow core:migrate --status" shows "migrated" or "not migrated, skipped". "not migrated, skipped" is a mixup and not clear to me. its not possible in my opinion that some migration is skippable if no migration happened before. i can only skip migrated ones. for me a better information is "no migration necessary"
7) Output of what is "skipped" should be located in a result message of "flow core:migrate (--dry-run) --verbose".

 Jira-URL: https://jira.neos.io/browse/FLOW-204

**Comment by kitsunet** [comment]
Nothing happened here, also probably not going to happen.
