### ISSUE TITLE
Persistence: Support database connection URLs

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#553]
Jira issue originally created by user mjonuschat:

When using Paas Providers it has become a common practice to provide the configuration parameters for a database connection in form of an environment variable along the lines of _DATABASE_URL_. This variable would contain a connection string in the form of _postgresql://my.database.host:54321/flow_test_.

As Doctrine already supports using URLs for a connection (see: [http://doctrine-dbal.readthedocs.org/en/latest/reference/configuration.html#connecting-using-a-url]) it would be nice if the Configuration/Settings.yaml would allow configuring the connection parameters using a URL string (not necessarily directly read from the Environment, this would be an added bonus)

 Jira-URL: https://jira.neos.io/browse/FLOW-211

**Comment by kitsunet** [comment]
Since we upgraded to DBAL 2.5.x this works just fine, just tested a mysql connection url in a local installation, therefore closing.
