### ISSUE TITLE
Fluid compilation is disabled for templates with switch ViewHelpers

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#556]
Jira issue originally created by user @bwaidelich:

Since https://forge.typo3.org/issues/28544 Fluid compiles templates into PHP when they are parsed for the first time.
But this compilation is disabled if a ViewHelper is used, that:
- implements `ChildNodeAccessInterface` and
- does not implement `CompilableInterface`

This is the case for the `SwitchViewHelper`.
We should implement the `CompilableInterface` in a similar fashion to how `AbstractConditionViewHelper` solves that.

See https://forge.typo3.org/issues/64449 for the original report (in the TYPO3 CMS bugtracker)

 Jira-URL: https://jira.neos.io/browse/FLOW-224

**Comment by kitsunet** [comment]
Closing as, as standalone fluid implements compile for switch.
