### ISSUE TITLE
Using ::class instead of hardcoded classname as string

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#557]
Jira issue originally created by user pumatertion:

php 5.5 supports Foo::class to get the classname as string.
We should use this systemwide.

 Jira-URL: https://jira.neos.io/browse/FLOW-225

**Comment by RafaelKa** [comment]
Close?
done in [e6252398a00a55829a9f746bb85da307babea85b](https://github.com/neos/flow-development-collection/commit/e6252398a00a55829a9f746bb85da307babea85b)
