### ISSUE TITLE
As a developer I want to have support for class_uses() on proxied classes

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#562]
Jira issue originally created by user @radmiraal:

class_uses() returns all traits used by given class, but this does not show traits used by parent classes. To support this in flow we should either extend the api of the reflection service or somehow build this into the proxy class building

 Jira-URL: https://jira.neos.io/browse/FLOW-252

**Comment by robertlemke** [comment]
I haven't heard of anyone needing this again since 2015, so I'm closing it for now. 🕸️
