### ISSUE TITLE
umask/permissions for files should be set centralized

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#563]
Jira issue originally created by user @kitsunet:

Currently some operations set a permission mask and some don't. We should unify that and set proper permissions everywhere. Currently it can happen that cache files created during deployment won't be overwritable later by web requests for example.

 Jira-URL: https://jira.neos.io/browse/FLOW-275

**Comment by sorenmalling** [comment]
#591 was marked as a duplicate. That issue is closed, so this ticket will be closed as well
