### ISSUE TITLE
add setAccounts to \TYPO3\Party\Domain\Model\AbstractParty

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#567]
Jira issue originally created by user kaystrobach:

adding the following function to \TYPO3\Party\Domain\Model\AbstractParty gives the ability to change the account from the surrounding party, otherwise we always need to have to do the role selection explicitly in the account

```
/****
 * Sets the accounts of this party
 *
 * @param \Doctrine\Common\Collections\Collection $accounts All assigned TYPO3\Flow\Security\Account objects
 * @return void
 */
public function setAccounts($accounts) {
    $this->accounts = $accounts;
}
```

 Jira-URL: https://jira.neos.io/browse/FLOW-281

**Comment by RafaelKa** [comment]
@kaystrobach: is it still neded? Can be closed?

**Comment by kaystrobach** [comment]
Yes please add it, makes using accounts via party easier

**Comment by RafaelKa** [comment]
@kaystrobach can you please move(just copy and paste) this issue to [Party](https://github.com/neos/party) Package?

Then we can close it here.

**Comment by kaystrobach** [comment]
moved to https://github.com/neos/party/issues/13
