### ISSUE TITLE
Installed Typo3-Flow-2.3 through composer cannot find symfony\console manifest

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#569]
Jira issue originally created by user eroelofs:

After updating a project to use "typo3/flow": "2.3.**", instead of "typo3/flow": "2.2.**", I am getting errors from flow:

PHP Fatal error:  Uncaught exception 'TYPO3\Flow\Package\Exception\InvalidPackageManifestException' with message 'No composer manifest file found for package "symfony.console". Please create one at "Symfony/Component/Console/composer.json".' in /export/www/projects/zig-app-kvs-hx/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Package/Package.php:138

This is because "Symfony/Component/Console/composer.json" indeed does not exist. The Symfony\Console project has switched over to PSR-4 and their composer.json file is now located directly in their vendor folder.

However, the FLOW package loader does not look there. It only checks the manifestPath. I added in a kludge to try the packagePath directly if the composer.json cannot be found in the manifestPath, which caused no further errors.

I'm sure that the way composer installed the files match with what I'd expect and I think that FLOW should be able to the composer.json file in the main packagePath as well. FLOW should be PSR-4 compliant, which should include reading composer.json files from the base directory.

 Jira-URL: https://jira.neos.io/browse/FLOW-286

**Comment by RafaelKa** [comment]
Can not reproduce with frish 2.2.0 and switch 2.2.0 -> 2.3.0

Described error happens only by manual removing from `Packages/Libraries/symfony/console/composer.json` file.

I guess it can be closed.

**Comment by kitsunet** [comment]
New PackageManager does not keep the manifest path but only a package path so yes, can be closed.
