### ISSUE TITLE
Response::createFromRaw fails with multiple header parts

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#570]
Jira issue originally created by user dogawaf:

I try to use curlEngine to fetch a content that is behind a "302 Found". So I set CURLOPT_FOLLOWLOCATION to TRUE.

But when CURLOPT_FOLLOWLOCATION and CURLOPT_HEADER are both true and redirects have happened then the header returned by curl_exec() will contain all the headers in the redirect chain in the order they were encountered. (http://php.net/manual/fr/function.curl-setopt.php#103232)

But Request::createFromRaw() expects only one header part, so it fails when parsing headers and content: the content contains the second header part.

See the attached file for a raw output of curl_exec: 
[curl_multiple_header_parts.txt](https://github.com/neos/flow-development-collection/files/773444/curl_multiple_header_parts.txt)

Jira-URL: https://jira.neos.io/browse/FLOW-289

**Comment by kitsunet** [comment]
Related to #849

**Comment by kdambekalns** [comment]
This was attached to the original report: [curl_multiple_header_parts.txt](https://github.com/neos/flow-development-collection/files/773442/curl_multiple_header_parts.txt)

**Comment by albe** [comment]
Should be fixed with the above merged PR. So closing this.
