### ISSUE TITLE
render viewHelper does not respect optional=true for partials

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#571]
Jira issue originally created by user kaystrobach:

steps to reproduce:
1. create a template / controller / etc. for an action
2. add a layout to the action template
3. add a reference to a partial with the following code
   `<f:render partial=„somepath“ section=„whatever“ optional=„true“ />`

if the section is missing i get an fatal error, while from the description of optional i would expect to have simply zero output … intended behaviour or bug?

according to https://forge.typo3.org/issues/27119#note-20 it's thought to use partials and sections together for code completition.

In AbstractTemplateView::renderPartial there is a call of renderSection if this call would get the optinal parameter as $ignoreUnknown the problem would be solved

 Jira-URL: https://jira.neos.io/browse/FLOW-295

**Comment by albe** [comment]
Closing for now, since this is now an issue of TYPO3 Fluid if it still exists. Also, AFAIS there is now the `$ignoreUnknown` flag, which seems to do exactly that.
