### ISSUE TITLE
Request content stream cannot be set

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#572]
Jira issue originally created by user @kitsunet:

In \TYPO3\Flow\Http\Request the "inputStreamUri" defaults to "php://input".
\TYPO3\Flow\Http\Request::setContent() accepts a resource stream but actually doesn't handle it correctly. Effectively it will be set as $this->content in the parent class and then result in broken broken content afterwards.

 Jira-URL: https://jira.neos.io/browse/FLOW-304

**Comment by sorenmalling** [comment]
The mentioned class was removed in Neos 6 as of the PSR-7 implementation. This issue has then returned in a "updated" version according to the new PSR-7 implementation here #1800 

This issue could/should be closed in favour of the new issue
