### ISSUE TITLE
Request should provide separate GET and POST data

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#575]
Jira issue originally created by user @kitsunet:

With argument merging a fully valid request with ?entity=some-uuid and a POST body of properties to change on that "entity" fails because of the merging (string + array). If we separated the data we could merge on a case by case basis or generally handle this more gracefully.

 Jira-URL: https://jira.neos.io/browse/FLOW-312

**Comment by kitsunet** [comment]
ok, so this will be solved with #761

**Comment by bwaidelich** [comment]
@kitsunet as #761 is resolved by now, can this be closed?

**Comment by albe** [comment]
Yes, the `Request` now provides `getQueryParams()` (GET) and `getParsedBody()` (POST) getters (among others) to access the separate data sources.
