### ISSUE TITLE
Devcontext: Exception stream wrapper not found

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#576]
Jira issue originally created by user kaystrobach:

this exception occurs from time to time and the fix is to easily clear the FLOW cache.

would be nice if 

a) cache would be cleared and page reloaded

b) the exception would be catched and nicely displayed like most other exception with the hint to clear cache

May not be possible currently as it is a fatal error, ...

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/12144/Bildschirmfoto_2015-06-10_um_22.28.57.png) 

 Jira-URL: https://jira.neos.io/browse/FLOW-313

**Comment by kitsunet** [comment]
I think as this part has undergone quite some changes the bug might be gone by now. Closing until re-opened.
