### ISSUE TITLE
Doctrine query cache caches queries regardless of parameters changing

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#579]
Jira issue originally created by user @aertmann:

When creating a custom condition generator for Doctrine filters the queries are cached even though the parameters change.

This can be prevented by setting a new unique parameter in the SqlFilter, however it's likely because setParameter is not called properly.

See https://gist.github.com/aertmann/51ae0040b1ef179c208e for an example

 Jira-URL: https://jira.neos.io/browse/FLOW-334

**Comment by kitsunet** [comment]
@aertmann shouldn't this be fixed with: https://github.com/neos/flow-development-collection/pull/893

If yes I would like to close this.

**Comment by aertmann** [comment]
Would think so, haven't tested it though.
