### ISSUE TITLE
Matching Doctrine SQL filters are applied multiple times

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#580]
Jira issue originally created by user @aertmann:

When using the Doctrine SQL filter the appended queries get the same query appended multiple times depending on the grant/deny pattern. This is unnecessary since they do exactly the same, so running the applies queries through array_unique would make sense.

This can be done with array_unique($effectiveConstraints) in SqlFilter

 Jira-URL: https://jira.neos.io/browse/FLOW-335

**Comment by sorenmalling** [comment]
This is implemented in current SqlFilter class by

```
        $grantedConstraints = array_diff($grantedConstraints, $deniedConstraints);
        $effectiveConstraints = array_diff($sqlConstraints, $grantedConstraints);

        if (count($effectiveConstraints) > 0) {
            return ' (' . implode(') AND (', $effectiveConstraints) . ') ';
        }
        return '';
```

inside the  `addFilterConstraint` method
