### ISSUE TITLE
Authentication and Authorization fails in functional tests

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#581]
Jira issue originally created by user mostwanted:
# Situation in which the bug occures:

The bug occures while executing a functional test that [1] makes use of `$this->authenticateAccount($myAccount)` and then [2] tries to request a controller action that is/should be accessible for one of `$myAccount`'s roles.

``` php
$this->authenticateAccount($myAccount);
$content = $this->browser->request($url)->getContent();
```

In our case `$myAccount`'s `roles` attribute contains 1 custom role. In `policy.yaml` that role is granted access to all methods of the above mentioned controller.
# Problem:

The access to the controller's constructor is denied, although the configuration in `policy.yaml` would/should grant access.

```
Uncaught Exception in Flow #1222268609: Access denied for method
Method: Foo\Bar\Controller\BazController::**construct()

Evaluated following 1 privilege target(s):
"Foo.Bar:Baz": ABSTAIN
(0 granted, 0 denied, 1 abstained)

Authenticated roles: TYPO3.Flow:Everybody, TYPO3.Flow:Anonymous
thrown in file /Users/mostwanted/Projects/Loremsium/Data/Temporary/Testing/Cache/Code/Flow*Object_Classes/TYPO3_Flow_Security_Authorization_Interceptor*PolicyEnforcement.php
in line 105
```
# Our observations while debugging the problem:

Right after calling `authenticateAccount()` the `SecurityContext`'s `activeTokens` attribute contains [1] `DefaultProvider` and [2] `TestingProvider`. The `TestingProvider`'s `account` attribute holds `$myAccount` (with our custom role that should grant access to the later requested action controller.

Furthermore the `AuthenticationManager`'s `isAuthenticated` attribute is set to `TRUE` right after calling `authenticateAccount()`.

So far, so good.

It seems that [1] the `SecurityContext` is "loosing" the `activeToken` for the `TestingProvider`  and [2] the `AuthenticationManager`'s `isAuthenticated` attribute is set to `FALSE` somewhere while calling `$this->browser->request($url)`. Therefore the access to the requested controller action is denied.

 Jira-URL: https://jira.neos.io/browse/FLOW-346

**Comment by kitsunet** [comment]
This is correct and probably needs a behat test with a session to deal with it correctly. Closing for now.
