### ISSUE TITLE
Cannot use AbstractFormViewHelper outside of FormViewHelpers

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#583]
Jira issue originally created by user cerlestes:

Currently it's not possible to use any ViewHelper that calls AbstractFormViewHelper::registerFieldNameForFormTokenGeneration() outside of a FormViewHelper.

However, the HTML spec does not prohibit such a use, and it would certainly be useful in a variety of situations to use the form fields outside of a form (e.g. a <select> that holds URLs and updates the window.location via JavaScript).

The attached patchfile rewrites the mentioned method to not do anything when the ViewHelper is not operating inside of a FormViewHelper, as nothing needs to happen in such a situation (see AbstractFormViewHelper::prefixFieldName()).

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/12307/patch.diff) 

 Jira-URL: https://jira.neos.io/browse/FLOW-360

**Comment by albe** [comment]
I do think this is no longer relevant. Test in #1380 indicates so at least.
