### ISSUE TITLE
Flow dies with meaningless fatal error when executed with PHP < 5.5

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#589]
Jira issue originally created by user @bwaidelich:

When executing Flow with a PHP version lower than 5.5 the bootstrap dies with

```
PHP Parse error:  syntax error, unexpected T*CLASS, expecting T_STRING or T*VARIABLE or '$' in Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php on line 270
```

We could solve that by moving the version check into the `index.php` file or by making the Bootstrap class backwards compatible (i.e. replacing `\SomeClass::class` with `'SomeClass'`)

 Jira-URL: https://jira.neos.io/browse/FLOW-370

**Comment by kitsunet** [comment]
Will close as the discourage anything else than composer. IMHO not really an issue to solve on our side.
