### ISSUE TITLE
Add a central API to wrap file_put_contents with some helpers

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#591]
Jira issue originally created by user @dfeyer:

Currently we use a lots of file_put_contents in our code base, sometimes with lock or other logic to be sure that the write operation succeed.

Flow should provide a simple API, like a static method in the Files utility classe to help developper deal correctly with those case (atomic write, file locking, retry, ...)

The api should provide:
- Configurable user / group (web + cli)
- Configuration umask (fallback to default umask)
- Lock (optional)
- Retry (if unable to write, the system should retry X times, with a short delay)
  
  Jira-URL: https://jira.neos.io/browse/FLOW-377

**Comment by sorenmalling** [comment]
The referenced `FLOW-275` is #563

**Comment by sorenmalling** [comment]
Since this issue is closed, I will go ahead and close referred #563, which was marked as a duplicate
