### ISSUE TITLE
It would be nice if the BytesViewHelper contains a "forceLocale" parameter

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#601]
Jira issue originally created by user tstrotmann:

It would be nice if the BytesViewHelper contains a "forceLocale" parameter, analogous to the NumberViewHelper or CurrencyViewHelper

 Jira-URL: https://jira.neos.io/browse/FLOW-41

**Comment by RafaelKa** [comment]
It is hard to add "forceLocale" feature on BytesViewHelper, if it is important to leave BytesViewHelper static.

If no one objects against moving from `.\Fluid\Core\ViewHelper\Facets\CompilableInterface` to `.\Fluid\Core\ViewHelper\AbstractLocaleAwareViewHelper`, then we can implement this feature.

**Comment by sorenmalling** [comment]
@RafaelKa Go ahead, I don't see the issue in doing that

**Comment by albe** [comment]
That `CompilableInterface` is gone for good even, so implementation should be rather easy :)

**Comment by albe** [comment]
Closing as of #2164
