### ISSUE TITLE
Allow Split Sources for all default configuration types

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#603]
Jira issue originally created by user @skurfuerst:

I think it would be very helpful to allow Split configuration Sources for Settings, Objects, Policy and Caches -- i.e. everything except Routes (which already allow for inclusion of other files).

This can be changed in ConfigurationManager::$configurationTypes.
### Workaround

In case you need this feature **now** on Flow 2.2, you can do the following:

**create a Settings.SplitSourceMarker.yaml with the following contents:**

```
SettingsSplitSourceActive: TRUE
```

**create the following Package.php**

```
<?php

use TYPO3\Flow\Configuration\ConfigurationManager;
use TYPO3\Flow\Package\Package as BasePackage;

class Package extends BasePackage {

    /****
     * Invokes custom PHP code directly after the package manager has been initialized.
     *
     * @param \TYPO3\Flow\Core\Bootstrap $bootstrap The current bootstrap
     * @return void
     */
    public function boot(\TYPO3\Flow\Core\Bootstrap $bootstrap) {
        $dispatcher = $bootstrap->getSignalSlotDispatcher();

        /****
         * WORKAROUND for now to allow split sources for Settings.
         *
         * - We override the (built-in) configuration type "Settings", enabling "splitSource".
         * - Because Settings are loaded very early in the bootstrap, we need to flush the configuration cache to re-load the Settings.
         *
         * However, we must NOT CLEAR THE CACHE always; thus we have a marker setting "SettingsSplitSourceActive" which is included in Configuration/Settings.SplitSourceMarker.yaml.
         * If this is found in the Settings, we know the split source has been correctly cached; and we do not need to clear it again.
         */
        $dispatcher->connect('TYPO3\Flow\Configuration\ConfigurationManager', 'configurationManagerReady', function(ConfigurationManager $configurationManager) {
            $configurationManager->registerConfigurationType(ConfigurationManager::CONFIGURATION*TYPE_SETTINGS, ConfigurationManager::CONFIGURATION_PROCESSING_TYPE*SETTINGS, TRUE);

            if ($configurationManager->getConfiguration(ConfigurationManager::CONFIGURATION*TYPE*SETTINGS, 'SettingsSplitSourceActive') === NULL) {
                $configurationManager->flushConfigurationCache();
            }
        });
    }
}
```

The solution is slightly inefficient because the settings are parsed twice if they are uncached.

 Jira-URL: https://jira.neos.io/browse/FLOW-42

**Comment by albe** [comment]
Split sources are possible by now for Settings, so can this be closed @skurfuerst @bwaidelich ?

**Comment by albe** [comment]
You mean the `configurationType.allowSplitSource` setting? So you would remove it and allow split sources for all configurations?

**Comment by bwaidelich** [comment]
> So you would remove it and allow split sources for all configurations?

Yes, I think this is what this ticket was about originally

**Comment by sorenmalling** [comment]
@bwaidelich Should this still be done? I will gladly change those boolean values and have it mind along with #1824

**Comment by albe** [comment]
Never found a reason why split sources shouldn't be allowed for any of the conigs, so I'm fine with that. Allow it for all and get rid of the config option :)

**Comment by sorenmalling** [comment]
Can you assign me ?

**Comment by sorenmalling** [comment]
And is this considered a FEATURE and not in before next major? (could we add a label for that?)

**Comment by albe** [comment]
FEATUREs (if they don't break things) can go into minors safely. I think this is such a case, because old single file configurations should still work. If the removal of the configuration setting is considered breaking, we can just deprecate it now, change the default value for all configs and then finally remove it only in the next major.

**Comment by sorenmalling** [comment]
All set 

https://github.com/neos/flow-development-collection/pull/1825

Perhaps worth noticing that the default value of `$allowSplitSource` in `registerConfigurationType` has also been changed to `true`. Is this "bad" in terms of avoiding BC?

**Comment by kdambekalns** [comment]
We have split `Settings.yaml` in Flow as of version 5.0.x anyway, so…

**Comment by kdambekalns** [comment]
See #1193

**Comment by sorenmalling** [comment]
This is for _all_ configuration Yaml flies (Routes, Objects, Caches) - the
PR you link to is only for Settings.yaml (from my reading)

(Replies from email - sorry for any formatting issues)
-- 
Sendt fra min mobiltelefon

**Comment by davidspiola** [comment]
See #1825
