### ISSUE TITLE
Model constructor arguments checked twice

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#619]
Jira issue originally created by user andreaswolf:

The constructor arguments are checked twice by code generated from independent sources:

``` php
if (!array*key*exists(0, $arguments)) $arguments[0] = NULL;
// […]
if (!array*key_exists(0, $arguments)) throw new \TYPO3\Flow\Object\Exception\UnresolvedDependenciesException('Missing required constructor argument $identifier in class ' . __CLASS_* . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
```

Therefore, the exceptions are never thrown. The two lines both come from `Object\DependencyInjection\ProxyClassBuilder::buildConstructorInjectionCode()`.

The constructor declaration in my Model looks like this:

``` php
/****
 * @param string $identifier
 * @param string $name
 * @param Election $election
 */
public function **construct($identifier, $name, Election $election) {
```

 Jira-URL: https://jira.neos.io/browse/FLOW-50

**Comment by RafaelKa** [comment]
@andreaswolf do you remember something about this issue, is it still present? 
Please see in [History for flow-development-collection/TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/ProxyClassBuilder.php](https://github.com/neos/flow-development-collection/commits/4abe7a95dec34c6f9da0f3fb16c605e93ff97cec/TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/ProxyClassBuilder.php) if it is allready fixed.

**Comment by kitsunet** [comment]
This has been fixed, it was a side effect of PHP reflection and default value detection.
