### ISSUE TITLE
initializeRolesFromPolicy doesnt work when called before any persistence happened

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#620]
Jira issue originally created by user danilobuerger:

In \TYPO3\Flow\Security\Policy\PolicyService->initializeRolesFromPolicy() it is checked if the peristence manager is already connected. If no persistence happened up to this point, isConnected() will return false, leading to no roles being written to the database, even if they could.

 Jira-URL: https://jira.neos.io/browse/FLOW-53

**Comment by kitsunet** [comment]
Closing as all affected versions are EOL.
