### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#623]
Jira issue originally created by user tpei:

In the second PHP snippet at http://docs.typo3.org/flow/TYPO3FlowDocumentation/TheDefinitiveGuide/PartII/ModelAndRepository.html#blog-repository
the phpdoc indicates a second parameter $limit in the findByBlog function, but it is not present.

Shouldn’t the code look like this https://gist.github.com/TPei/3900a7fc3681c8b301d3 ?

 Jira-URL: https://jira.neos.io/browse/FLOW-57

**Comment by RafaelKa** [comment]
Can be closed.

Seems to be fixed in [93faabc3b9c1a9ddd4739906f0039133b643f0a9](https://github.com/neos/flow-development-collection/commit/93faabc3b9c1a9ddd4739906f0039133b643f0a9#diff-cd6554755ea52d093cba0e7053e46e6fR578)
