### ISSUE TITLE
Make it possible to override XLIFF definitions from other packages

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#624]
Jira issue originally created by user @hlubek:

In order to provide custom translations for existing labels, Flow should have a well defined convention on how to override XLIFF definitions from other packages. The package order (by dependency) should be respected for this.

**Idea**

In order to override translations from another package, a file with the same name and location is created in another package. This file contains a `<file>` element with a `product-name="PackageKey"` attribute for the package that should be overwritten. This way an XLIFF file can contain definitions for more than one package in a backward compatible and consistent way.

When accessing a label the filename and package key is given to a `TranslationProviderInterface` implementation which will use a merged version of the partial definitions (merged by package order).

Any labels that are exported to the client-side should use the same merged XLIFF definitions for a consistent approach to localization.

 Jira-URL: https://jira.neos.io/browse/FLOW-61

**Comment by fcool** [comment]
I think, this is something we have already finished. At least I think I use the merging described here already a lot in my projects. If you think differently, just reopen.
