### ISSUE TITLE
Allow to symlink configuration in Configuration/ folder

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#626]
Jira issue originally created by user @skurfuerst:

This issue was discovered recently at a customer, who wanted to share the same settings for development and production, and thus symlinked a folder underneath Configuration/Development/MySubContext to Configuration/Production/MySubContext (ordering does not really matter).

This had very strange effects in development context: Proxy class building was failing seemingly-random, the development context did not really work, flow:help was throwing fatal errors from time to time, etc.

Production context worked flawlessly.

Here's what happened:

*\* When Flow starts up in Development/MySubContext, it tries to initialize configuration very early on in the bootstrap. This is especially _before_\* caches are initialized. (Because caches are configured using configuration...)
- Because of the symlink between development and production, Flow finds the file Development/MySubContext/IncludeCachedConfigurations.php which has been created by production context.
  *\* It then loads the _Production_\* configuration, despite being in development mode.
- The result is this odd mixture of working code and errors.

Proposed fix:

*\* store IncludeCachedConfigurations.php in a fixed folder _Configuration/Compiled_, and name it after the current context; like _Production_MySubcontext_CachedConfigurations.php_*

Can anybody think of any drawbacks of this solution? I have the feeling it should work.

Greets,
Sebastian

 Jira-URL: https://jira.neos.io/browse/FLOW-69

**Comment by RafaelKa** [comment]
@skurfuerst:
Why not creating symlinks to the yaml files instead of folders?

Can it be closed?

**Comment by kitsunet** [comment]
This is probably resolved with the removal of IncludeConfiguration files in Flow 4.0 ?

**Comment by sorenmalling** [comment]
I will say so, yes :)
