### ISSUE TITLE
Concrete entities are not regarded when an abstract one is noted in Policy.yaml

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#629]
Jira issue originally created by user afoeder:

with, for example,

```
resources:
  entities:
    'Acme\Foobar\Domain\Model\AbstractProduct':
      [...]
```

all heirs of that AbstractProduct are not taken into account; hence the whole constraint does not match (because of cause there is no abstract entity at the end).

In fact this is only relevant for \TYPO3\Flow\Security\Aspect\PersistenceQueryRewritingAspect::checkAccessAfterFetchingAnObjectByIdentifier because in the other case, we're lucky if the table name corresponds the abstract entity itself which is the case in most... cases.

The method \TYPO3\Flow\Security\Policy\PolicyService::hasPolicyEntryForEntityType already gives false because the given entity type (the concrete one) is not in the \TYPO3\Flow\Security\Policy\PolicyService::$entityResourcesConstraints array (where only the abstract one is present).

IMO it would help to fix \TYPO3\Flow\Security\Policy\PolicyExpressionParser::parseEntityResources and also just "copy" the settings for every heir of the (abstract) class, but that would require some discussion since it's proxy=false...

 Jira-URL: https://jira.neos.io/browse/FLOW-72

**Comment by sorenmalling** [comment]
Hi @afoeder 
I see this issue is from the first version of the Policy framework (before the Privilege concept).

Does this issue still stand, with the way the EntityPrivilege is working today and how you configure it?

**Comment by afoeder** [comment]
Hey @sorenmalling I really cannot say but thanks for getting back at me. I guess you can close it.
Have a good time and stay safe all of you!
