### ISSUE TITLE
Memory limit in the dump produced by the Debugger

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#630]
Jira issue originally created by user dogawaf:

When an exception is thrown , the DebugExceptionHandler produces a nice backtrace and some dump of the arguments passed to functions.

I have some Doctrine ArrayCollection which point to records with recursive relationships.

When the debugger try to dump an argument of this type, php reaches the max memory limit, and crashes the server.

Commenting this line [1] fixes the symptom for me, but I am not able (available) to tackle the root cause.

[1] https://git.typo3.org/Packages/TYPO3.Flow.git/blob/HEAD:/Classes/TYPO3/Flow/Error/Debugger.php#l330

 Atachements:

![Jira Image](https://jira.neos.io/secure/attachment/11301/debug-title-1.png) 

 Jira-URL: https://jira.neos.io/browse/FLOW-75

**Comment by rcreate** [comment]
Hey guys, i ran into the same problem today. Is anything happend in the past 2 years? ;-)

**Comment by kitsunet** [comment]
Indeed, not but I also ran into this recently again and might really tackle it finally.

**Comment by daniellienert** [comment]
I ran into it reproducible when I add a typehint to an eel method and the pass a not fitting value.

**Comment by daniellienert** [comment]
Memory issues while debugging recursive relationships should be solved with #1493 and #1490
