### ISSUE TITLE
Programatically modify command descriptions

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#631]
Jira issue originally created by user @robertlemke:

Commands which are extensible, for example by some plugin mechanism, or depend on their environment, may want to tweak the short and long description which is shown in the help screen.

One solution would be an interface which needs to be implemented by the command controller in question which allows it to tweak descriptions.

 Jira-URL: https://jira.neos.io/browse/FLOW-78

**Comment by sorenmalling** [comment]
A Command implementing `DescriptionAwareCommandControllerInterface` gives you two methods (`processShortDescription` and `processDescription`) to provide programmatically descriptions for the command help index.

This issue could/should be closed at the described issue can be solved today
