### ISSUE TITLE
Roles might not be initialized when creating an account with the account factory

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#632]
Jira issue originally created by user andi:

If you create a new Flow project and try to create an account right away, e.g. by some command controller, it might happen that the roles have not yet been synchronized with the database.

To solve this the AccountFactory should call getRoles() on the PolicyService right at the beginning. This will make sure roles are correclty initialized in the database when a new account is created.

 Jira-URL: https://jira.neos.io/browse/FLOW-8

**Comment by kitsunet** [comment]
Yes, this can be closed by now.
