### ISSUE TITLE
Removing Childrole from Policy.yaml does not update records in db

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#635]
Jira issue originally created by user pumatertion:

Changing this:
roles:
  Customer: []
  Press: [Customer]

to this:
roles:
  Customer: []
  Press: []

The Press->Customer Relation does not get removed from table: typo3_flow_security_policy_role_parentroles_join

 Jira-URL: https://jira.neos.io/browse/FLOW-83

**Comment by RafaelKa** [comment]
duplicate from #577
affected Flow <3.0

**Comment by kitsunet** [comment]
Closing as versions no longer supported.
