### ISSUE TITLE
Possible CGL addition

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#636]
Jira issue originally created by user @radmiraal:

afaik we don't have a CGL yet about parenthesis usage in cases like below:
$a = $b === $c;
This could possibly be misread to $a = $b = $c; Should we add to the CGL that we require parenthesis like $a = ($b === $c); ?

 Jira-URL: https://jira.neos.io/browse/FLOW-88

**Comment by kitsunet** [comment]
No one has touched this, I also think common sense is fine, so closing.
