### ISSUE TITLE
security.* ViewHelpers don't work without initialized security context

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#637]
Jira issue originally created by user @bwaidelich:

When using the `ifAccess` ViewHelper like

```
<f:security.ifAccess privilegeTarget="Some.Package:SomePrivilege">
```

or the `ifHasRole` ViewHelper like

```
<f:security.ifHasRole role="Some.Package:SomeRole">
```

in an environment where the `Security\Context` cannot be initialized (e.g. when rendering a fluid template from a CLI command), an exception

```
The security Context cannot be initialized yet.
```

The expected behavior would be to evaluate to FALSE in this case

 Jira-URL: https://jira.neos.io/browse/FLOW-383

**Comment by kitsunet** [comment]
Fixed for next version.

**Comment by bwaidelich** [comment]
@kitsunet which PR fixes this?

**Comment by bwaidelich** [comment]
-> I just figured it out: a18729fce47a01a3f861b1898d67e20d1a40edd4 fixes this as a "side effect" ;)
