### ISSUE TITLE
Object configuration presets

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#671]
### Intro

I'd like to propose/discuss a feature for Flow 4.0+: The possibility to reuse the same object/singleton with different setups within one application.
### Scenarios
- Currently we need two different interfaces to achieve this feature for `SecurityLogger` vs `SystemLogger`
- For the CQRS/ES package it's important to be able to have logically separate `EventStore` instances per Bounded Context/Package possibly with different storage backends
- In general: Singletons with different setups
### "presets" Approach

My first approach was to extend the object configuration by some optional `presets` part that will _merge and overrule_ the basic object configuration:

``` yaml
TYPO3\Flow\Log\LoggerInterface:
  scope: 'singleton'
  factoryObjectName: 'TYPO3\Flow\Log\LoggerFactory'
  presets:
    'system':
      arguments:
        1:
          value: 'SystemLogger'
        # ...
    'security':
      arguments:
        1:
          value: 'Flow_Security'
        # ...
```

The corresponding injection would look sth like:

``` php
/**
 * @Flow\Inject(preset="system")
 * @var LoggerInterface
 **/
protected $systemLogger;
```
#### Advantages
- Central configuration around the interface in question
- Little duplication because presets inherit the main object configuration
#### Drawbacks/Challenges

This works fine with `prototypes` but for `singletons` we'd need to tweak the core of object management: `ObjectManagerInterface::get()` expects the object name and optionally some constructor arguments.
We could use a special format to refer to the `preset` here, like `<ObjectName>:<presetName>`. The generated proxy Code in `Flow_Proxy_injectProperties()` could then look something like

``` php
$this->Flow_Proxy_LazyPropertyInjection('TYPO3\Flow\Log\LoggerInterface:system', '', 'systemLogger', '6d57d95a1c3cd7528e3e6ea15012dac8', function() { return \TYPO3\Flow\Core\Bootstrap::$staticObjectManager->get('TYPO3\Flow\Log\LoggerInterface:system'); });
```

instead of the current

``` php
$this->Flow_Proxy_LazyPropertyInjection('TYPO3\Flow\Log\SystemLoggerInterface', '', 'systemLogger', '6d57d95a1c3cd7528e3e6ea15012dac8', function() { return \TYPO3\Flow\Core\Bootstrap::$staticObjectManager->get('TYPO3\Flow\Log\SystemLoggerInterface'); });
```

but it feels a bit "hacky"
### "objectName" Approach

We could use existing object vs class name distinction and allow "fake" object names.
The example from above could look like that:

``` yaml
TYPO3_Flow_SystemLogger:
  className: 'TYPO3\Flow\Log\LoggerInterface'
  scope: 'singleton'
  factoryObjectName: 'TYPO3\Flow\Log\LoggerFactory'
  arguments:
    1:
      value: 'SystemLogger'
    # ...
TYPO3_Flow_SecurityLogger:
  className: 'TYPO3\Flow\Log\LoggerInterface'
  scope: 'singleton'
  factoryObjectName: 'TYPO3\Flow\Log\LoggerFactory'
  arguments:
    1:
      value: 'Flow_Security'
    # ...
```

and

``` php
/**
 * @Flow\Inject(name="TYPO_Flow_SystemLogger")
 * @var LoggerInterface
 **/
protected $systemLogger;
```
#### Advantages
- Less intrusive
- Closer to the concept as initially intended
#### Drawbacks/Challenges
- More duplication (unless we merge the configurations somehow)
- Possible naming clashes (we can introduce a naming scheme though)

**Comment by kitsunet** [comment]
IMHO this is not a singleton anymore, I think we should get rid of this line of thinking. 
I would propose the following two variants:

Configuration and usage could be similar to the first approach, but internally two alternative implementation solutions:

1. Instead of asking the object manager in the injection we ask the object manager for the factory and the factory to build us the instance. If the instance is reused (what was called singleton) is the factories decision.

2. We do `ObjectManager->get(Interface::class, $presetName)` and give that to the factory instead of the implementation class. currently neither happens so it's just semi breaking because currently this kind of code with a configured factory was not valid but didn't throw an error.

**Comment by bwaidelich** [comment]
> IMHO this is not a singleton anymore, I think we should get rid of this line of thinking. 

It doesn't have to, but in the cases above (SystemLogger, SecurityLogger, EventStore) they *are* singletons in the context.
But you're right, that's not the important point here.

> Instead of asking the object manager in the injection we ask the object manager for the factory

It would be a pitty if we needed to build factories for all of these.. We could ofc have a generic one. But what's the difference to the `ObjectManager` then?

> We do ObjectManager->get(Interface::class, $presetName)

I doubt that this will work as `ObjectManagerInterface::get()` expects the object name + an arbitrary set of arguments that will be passed to the constructor.
I mean we could probably magically handle it like this: If the given interface is configured with a `factoryObjectName` (`ObjectConfiguration::isCreatedByFactory() === true`) we pass the arguments to the factory somehow. But that will clash with the `arguments` object configuration.

**Comment by kitsunet** [comment]
What is the singleton here? The Interface? Nope it's not, the current `SystemLoggerInterface` maybe is, but `LoggerInterface` clearly is not. The Implementation class? Nope again not a singleton. Both exist multiple times with different states.


Citing from the ObjectManager:

```
        if (func_num_args() > 1 && isset($this->objects[$objectName]) && $this->objects[$objectName]['s'] !== ObjectConfiguration::SCOPE_PROTOTYPE) {
            throw new \InvalidArgumentException('You cannot provide constructor arguments for singleton objects via get(). If you need to pass arguments to the constructor, define them in the Objects.yaml configuration.', 1298049934);
        }

        // some other stuff for other cases in between

        if (isset($this->objects[$objectName]['f'])) {
            $this->objects[$objectName]['i'] = $this->buildObjectByFactory($objectName);
            return $this->objects[$objectName]['i'];
        }
```

For singletons you cannot even use arguments at all. Additionally the arguments are currently NEVER used when a factory is configured, so we could safely do number 2 IMHO.

Also it feels like the object manager is a bit too powerful, I say "YES", let the object manager delegate responsibility for this specific interface to a factory. And yes, we must create a factory for those objects then, so what?

**Comment by bwaidelich** [comment]
> What is the singleton here?

```yaml
TYPO3\Flow\Log\LoggerInterface:
  scope: 'singleton'
  # ...
```
With that I want every object referred to with that interface (including presets) to be singletons.
So no, neither the interface nor the class is a singleton. The *implementation* is a singleton for the given preset.

> For singletons you cannot even use arguments at all

Right, but you can (and usually) do specify arguments that are passed to the `Factory`.
It's good to know that we can use the syntax `ObjectManagerInterface::get('SomeSingleton', $presetName)` unambiguously but IMO this is not very explicit and quite flaky (i.e. if `SomeSingleton` is configured to be a prototype at some point).

> And yes, we must create a factory for those objects then, so what?

So what? There are so many reasons. One of them being: Creating factories just to implement the singleton pattern with a new dimension will increase code => errors.
I agree that the ObjectManager is pretty powerful, but unless we decide to extract logic like singleton handling etc from it I would object to introducing a separate concept.

**Comment by kitsunet** [comment]
Advocatus Diaboli: Why have factories anyway? Right now they are not empowered to do anything really, we could easily let the object manager do it.

IMHO we cannot wait for "the big refactoring" to make it less powerful. Small steps in the right direction. Letting Factories (always, not only in the preset case) manage more themselves woudl be a nice first step.

**Comment by bwaidelich** [comment]
Mh, you have a point for sure. I need to let it sink in. And I'm curious about @robertlemke's and others POVs

**Comment by kitsunet** [comment]
Side note: If we start treating and talking about "object name" as a specific service (like a "TypoScript Cache" or a "System Logger") that might work even though I don't like it. The `SystemLoggerInterface` has given me so many problems over time, I really dislike it. But you will want to annotate an existing class not a virtual one (We could easily imagine to configure virtual classes):

```
TYPO3\Flow\Cache\SessionCache:
  // object configuration here
```

Then `TYPO3\Flow\Cache\SessionCache` would be the "object name" but doesn't really exist. That would be even more confusing and is a no-go IMHO. Also for code completion.
That's why for me the "object name" that we use is quite confusing. As a concept it cannot solve what we need to solve in a understandable and extensible way.
A service locator that I can ask for a "SessionCache" "service" would work, IMHO that concept has it's flaws as well, but it's more understandable than mixing real class instances with something (semi) virtual aka "object names".

**Comment by bwaidelich** [comment]
I also dislike the use of "virtual" object names that look like class names but don't exist. Also it breaks in several parts of the core currently.
What I could imagine (and currently play around with) is some kind of mix that uses the preset configuration syntax from above but allows `<ClassName>:<presetName>` as `object name`. I'll push a WIP PR once I got it working ;)

**Comment by robertlemke** [comment]
Hey! Before I get into details, can you try to get to the distill the essence and write down what you need (not how it is implemented) in one or more little sentences? Like user stories: who wants to do what in order to ...?

**Comment by kitsunet** [comment]
I think that's pretty easy.

As developer I want to configure multiple presets for a given configurable object (like cache or logger) and then have an easy way to get an object configured with one of the presets injected to my class.

In essence: make what `Caches.yaml` does a generic concept called preset, applicable to different types of objects. Have an easier way to inject one of those than writing Objects.yaml configuration for every single place I want to use a specific instance.

**Comment by bwaidelich** [comment]
> Before I get into details, can you try to the distill the essence

@robertlemke That's what I tried with the intro and scenarios above.
Like @kitsunet wrote: Reusing pre-configured objects without having to write custom factories/managers everywhere.

As a developer I don't want to write
```php
/**
 * @Flow\Inject
 * @var EventStoreManager
 **/
protected $eventStoreManager;

/**
 * @Flow\Inject
 * @var EventStore
 **/
private $eventStore;

public function initializeObject()
{
    $this->eventStore = $this->eventStoreManager->getForBoundedContext('My.Package');
}
```

But sth like

```php
/**
 * @Flow\Inject(preset="My.Package")
 * @var EventStore
 **/
protected $eventStore;
```

(I know that's not what you had in mind with "like user stories", but Christian captured that and this snippet might be a useful addition)

**Comment by skurfuerst** [comment]
Hey everybody,

certainly an interesting discussion :-) To give more perspective I wanted to again check out what Spring does. Basically, they have a similar distinction between our "object Name" (a "virtual object name" which you ask for on ObjectManager::get()) and actual class names. In Spring the object name is called "bean ID". [Documentation](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/beans.html#beans-factory-scopes-singleton)

The relevant part is the following:

> Spring’s concept of a singleton bean differs from the Singleton pattern as defined in the Gang of Four (GoF) patterns book. The GoF Singleton hard-codes the scope of an object such that one and only one instance of a particular class is created per ClassLoader. The scope of the Spring singleton is best described as per container and per bean.

## Proposal

I think we can actually tweak our system a little without introducing additional concepts on "factories" or "presets" in the following way:

* **allow arbitrary strings as Object Names in the system** (configured in Objects.yaml)
  * this way, we could do something like `PackageKey:VirtualObjectName` as a convention.
* On the @Flow\Inject annotation, add a new parameter `objectName`, so we don't need to mis-use the `@var` annotation for this.

Full example:

```yaml
# Objects.yaml

'My.Package:VariantA':
  scope: singleton
  className: My\Package\BaseClass

'My.Package:VariantB':
  scope: singleton
  className: My\Package\BaseClass
```

```php
/**
 * @Flow\Inject(objectName="My.Package:VariantA")
 * @var My\Package\BaseClass
 * NOTE: The VAR annotation above is basically ignored by object management
 */
protected $variantA;

/**
 * @Flow\Inject(objectName="My.Package:VariantA")
 * @var My\Package\BaseClass
 * NOTE: The VAR annotation above is basically ignored by object management
 */
protected $variantA;

/**
 * @Flow\Inject(objectName="My.Package:VariantB")
 * @var My\Package\BaseClass
 * NOTE: The VAR annotation above is basically ignored by object management
 */
protected $variantB;

/**
 * @Flow\Inject
 * @var My\Package\BaseClass
 */
protected $baseClass;

// At this point, $variantA !== $variantB !== $baseClass; all of them being singletons however.
```

## Further Thoughts

* We could add an option to Objects.yaml preventing direct instanciation of objects, so one could disable the injection of `BaseClass` in the example above, making the code more fool-proof.
* At $someLaterPoint, we could make the preset configurable from the outside somehow, e.g. through Objects.yaml.

I'm curious about your thoughts :)

All the best,
Sebastian

**Comment by kitsunet** [comment]
So what Spring does and what you suggest is pretty much what Basti already implemented in #674 

For me Spring is no longer a good guideline. Especially the fact that we add more magic to the thing not less. Also I still fear the maintainability of this additional complexity. That said I am still against this solution.

**Comment by bwaidelich** [comment]
@skurfuerst Thanks for your feedback! What you suggest is in sync with the `"objectName" Approach` of the issue description, right?

> So what Spring does and what you suggest is pretty much what Basti already implemented in #674

What #674 implements is the `"presets" Approach` (the differences are described above).
I agree that we must not "blindly" follow Spring or Symphony but it's interesting to see that they saw the same problems with global singletons apparently.

I'll give the "virtual object name" approach a shot. Robert already suggested that, too, and in fact that was the original idea behind object vs class name.

**Comment by bwaidelich** [comment]
> I am still against this solution.

So you think we should go this way: https://github.com/neos/flow-development-collection/issues/671#issuecomment-254438630  or can you elaborate on an alternative?

**Comment by bwaidelich** [comment]
See #676 for the far less intrusive implementation based on "virtual objects" as suggested by @robertlemke & @skurfuerst

**Comment by robertlemke** [comment]
@skurfuerst thanks for the pointer! Since I originally modelled Flow's Object Manager after some core concepts in Spring, it is a meaningful comparison.

@kitsunet I suggest that you give this another thought with some flushed / unopinionated brain, because …

> So what Spring does and what you suggest is pretty much what Basti already implemented in #674

… that's actually not the case, as Basti also pointed out.

I am still in favour of the virtual object name approach (especially the one more concretely proposed by @skurfuerst) because it fits better into what we already have, how it was intended and doesn't tear lots of new wounds in Flow's core.

I definitely like the approach @bwaidelich took in #676.

**Comment by skurfuerst** [comment]
Yep, I also really like it looking at the code :)

**Comment by kitsunet** [comment]
Right, sorry that was a mistype, I meant #676 obviously. I personally still don't like it, but my mindset is currently steering away a bit from some of the concepts we currently have ;)
If you all want it, so be it.

**Comment by albe** [comment]
Isn't #676 pretty much exactly what was intended @kitsunet, just with the difference that it's now called
"(object)name" instead of "preset"?
I mean, the required colon in the name makes it very explicit that this is not a real class, but some virtual configuration of some arbitrary class. I would even say, calling it "objectName" makes it more clear it is about object configuration/Objects.yaml, instead of the unspecific "preset" - though maybe "objectConfiguration" would be even more explicit.

Only drawback I really see left, is that Objects.yaml now does deal with two concepts in the upper level: concrete classes and virtual object configurations
That and `@var` annotation becoming decoupled from actual object gotten (can be solved, so no dealbreaker).

**Comment by kitsunet** [comment]
I guess the point I am wanting to make is that currently we feed only existing classes/interfaces to ObjectManager::get and now we start mixing in "magic" strings.

**Comment by bwaidelich** [comment]
Update: I still think this would be a useful feature and misuse could be avoided if

1. We never use the virtual classes in manual `ObjectManager::get()` calls (we should not manually call this method anyways in "userland" code)
2. We communicate that `@Flow\Inject` annotations should only be used in the "higher level" code.

What I mean with that is: For example in the Cqrs package we should probably completely avoid `@Flow\Inject` or event `inject*()`-methods in favor of constructor injection. But in (Command)Controllers it's a very convenient thing to do..


Anyways, I already spent far more time on this than planned and currently face a deadlock (see #676). So I'll un-assign myself from this ticket for now

**Comment by nezaniel** [comment]
Just a thought, aren't we discussing something like this: https://en.wikipedia.org/wiki/Multiton_pattern
here?

**Comment by bwaidelich** [comment]
> Just a thought, aren't we discussing something like this: https://en.wikipedia.org/wiki/Multiton_pattern
here?

Yes, exactly. Although it could be used for prototypes too, in theory

**Comment by albe** [comment]
Is this something worth reviving for the upcoming LTS?
