### ISSUE TITLE
Missing default values for optional routes

### ISSUE THREAD

**Issue by hhoechtl** [neos/flow-development-collection#683]
If you have an uriPattern with an optional route part and you haven't set a default value it's pretty hard to get a clue on what is wrong with your route not matching without the optional part.

E.g. uriPattern `test/{some}(/{thing})` only matches `test/foo/bar` but not `test/foo` as you would expect. Only if you add a null default value for thing the route is working.
It would be good if an error is thrown if a default value is not defined for an optional part.

**Comment by RafaelKa** [comment]
It is impossible in [Schema](https://github.com/neos/flow-development-collection/blob/ed1cacfd28875a1c2babccbb30b2e150cfbe95d4/TYPO3.Flow/Resources/Private/Schema/Routes.schema.yaml#L8-L15), needs some custom logic.

**Comment by bwaidelich** [comment]
doh, I fixed this right after your report but forgot to create a PR from it. There you go:
https://github.com/neos/flow-development-collection/pull/684

**Comment by bwaidelich** [comment]
@hhoechtl @RafaelKa *ping*
