### ISSUE TITLE
Remove "TYPO3.Welcome" routing from Essentials and into the TYPO3.Welcome package and include from Settings.yaml

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#698]
The default Routes.yaml copied to the root of the Flow installation contains a reference to TYPO3.Welcome

With a composer.json requiring nothing but `"typo3/flow": "~3.3.0"` will cause the flow command to fail, since it can find the TYPO3.Welcome routing.

Suggested solution is to remove it from the Essentials and into the TYPO3.Welcome package and include with Settings.yaml possitioned "first"

**Comment by kitsunet** [comment]
<3

**Comment by sorenmalling** [comment]
There you got @kitsunet  :-)
