### ISSUE TITLE
Escaping Replacement in Fluid is somehow broken

### ISSUE THREAD

**Issue by skurfuerst** [neos/flow-development-collection#730]
The following line works:

```
<script src="{f:uri.resource(path: 'resource://Neos.Neos.Ui/Public/JavaScript/Vendor.js')}"></script>
```

When I add a variable named {baseResourcePath}, containing `resource://Neos.Neos.Ui/`, and use the following line, the system dies:

```
<script src="{f:uri.resource(path: '{baseResourcePath}/Public/JavaScript/Vendor.js')}"></script>
```

Error is: *#1386458851: The specified path "resource://Neos.Neos.UI/http://127.0.0.1:8081/_Resources/Static/Packages/Neos.Neos.Ui/JavaScript/Vendor.js" does not point to a public resource.*

Now, the quiz question: Why do we somehow "double replace" the URL?

Here's a full example exhibiting the behavior:

```
<title>Neos CMS</title>
        {baseResourcePath}
        {baseResourcePath}/
        {baseResourcePath}/Publi
        {baseResourcePath}/Public

# STARTING HERE; THE ERROR WILL APPEAR
        {baseResourcePath}/Public/
        {baseResourcePath}/Public/JavaScript/Vendor.js
```

**Comment by skurfuerst** [comment]
@johannessteu I think this might be a critical issue which we should fix before next major release  - maybe @kitsunet has a theory why it happens.

**Comment by kitsunet** [comment]
This is the behavior since ever, see eg. Fluid in 3.3:
´\TYPO3\Fluid\Core\Parser\Interceptor\Resource` The patterns matches basically every path that contains "Public".

So if we want to change that behavior IMHO that's only possible in master, even if it's somewhat broken. I am open for suggestions as we need some anchor to find paths that the interceptor should apply to.

**Comment by bwaidelich** [comment]
> The patterns matches basically every path that contains "Public".

Well, the pattern is actually a little more strict:
```php
const PATTERN_SPLIT_AT_RESOURCE_URIS = '!
		(
			(?:[^"\'(\s]+/      # URL part: A string with no quotes, no opening parentheses and no whitespace
			)*                  # a URL consists of multiple URL parts
			Public/             # the string "Public/"
			[\w._ /]+           # followed by any number of [\w._ /]
		)
		!ux';
```
(see [Resource interceptor](https://github.com/neos/fluid/blob/master/Classes/TYPO3/Fluid/Core/Parser/Interceptor/Resource.php#L111))

But is it really less strict now, @skurfuerst?

In general I'd say: If you use a custom variable to specify the base path you don't need to use the resource VH any more, do you?

**Comment by kitsunet** [comment]
No, I assume this was never tried before, the pattern shouldn't be any different.

**Comment by skurfuerst** [comment]
OK, fine with me; the error was there before as well. and it is really an edge case.
