### ISSUE TITLE
Package freezing is broken

### ISSUE THREAD

**Issue by dfeyer** [neos/flow-development-collection#743]
Currently `ReflectionService::freezePackageReflection()` is broken because is call `Package::getNamespace()` ... and this method does not exist any more.

We should adapt the code to use `Package::getNamespaces()`

**Comment by dfeyer** [comment]
Regarding the package manager removal from the backend I think about it a bit more. What about to make our package manager (PackageManagerInterface) read only ? Maybe we can keep the activate/desactivate, that can be useful some times, but the rest is "broken" duplication of composer. What do you think ?

**Comment by kitsunet** [comment]
https://github.com/neos/flow-development-collection/pull/851
