### ISSUE TITLE
TYPO3Fluid: Document changed behavior of `AbstractConditionViewHelper`

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#746]
### Description

In TYPO3Fluid the behavior of the  `AbstractConditionViewHelper` has been changed and it's hardcoded to evaluate a boolean argument `condition` by default.
In order to implement a custom condition VH one has to override the static `evaluateCondition` function.

### Steps to Reproduce

1. Create a simple custom ViewHelper, e.g.:

```php
class MyViewHelper extends AbstractConditionViewHelper
{
  public function render()
  {
    return $this->renderThenChild();
  }
}
```

2. Put it in a template

```html
{namespace x:My\Package\ViewHelpers}
<x:my>
  <f:then>THEN</f:then>
  <f:else>ELSE</f:else>
</x:my>
```

#### Expected behavior

```
THEN
```

#### Actual behavior

```
ELSE
```

(only renders "THEN" correctly on the first hit, before the template is compiled)

### Affected Versions

Flow 4.0  (using TYPO3Fluid).

**Comment by bwaidelich** [comment]
Was this closed automatically?? This is not fixed by #784

**Comment by robertlemke** [comment]
@bwaidelich Sorry, my bad. So this still needs to be fixed and there's no pull request for it yet, right? Is it a blocker for the 4.0 release?

**Comment by bwaidelich** [comment]
@robertlemke This is just about *documenting* the changed behavior. I already added it to the release todos, but IMO we should keep the ticket open just in case

**Comment by kdambekalns** [comment]
So, that new behaviour is this, right?

> In order to implement a custom condition VH one has to override the static evaluateCondition function.

**Comment by kitsunet** [comment]
I would *try* to document some changes and best practices aobut fluid anyway, but so far I couldn't bring myself to it.
All in all render is not really best practice anymore and render with arguments even less.

**Comment by bwaidelich** [comment]
> All in all render is not really best practice anymore and render with arguments even less.
I'm quite sad about that. I built many custom condition VHs. They improved usability/readability a lot and they only make sense with custom arguments really.
A way to make this less what-the-fucky for developers might be:
Make `evaluateCondition` *abstract* in the [AbstractConditionViewHelper](https://github.com/TYPO3/Fluid/blob/master/src/Core/ViewHelper/AbstractConditionViewHelper.php) and implement it in the [IfViewHelper](https://github.com/TYPO3/Fluid/blob/master/src/ViewHelpers/IfViewHelper.php).

Then you'd get some nice exception about the missing implementation rather than a silently broken behavior

**Comment by kdambekalns** [comment]
@kitsunet and @bwaidelich – nice to have you discuss this, but the **behaviour already changed**, so we need to document that change. Right?

**Comment by bwaidelich** [comment]
> nice to have you discuss this, but the behaviour already changed, so we need to document that change. Right?

I guess so. With #855 this was added to the inline documentation of the ViewHelper but IMO this has to be part of the Release / Upgrade notes - But it seems [RTD](http://neos.readthedocs.io/en/stable/Appendixes/ReleaseNotes/index.html) is still broken..

**Comment by kdambekalns** [comment]
What makes you think it's broken, @bwaidelich? Release notes simply do not exist in rST so far…

**Comment by bwaidelich** [comment]
Ah, I see that the RTD [issue has been fixed](https://github.com/rtfd/readthedocs.org/issues/2623) in the meantime. So we're missing release and change logs for both, Flow 4.0 and Neos 3.0?!

**Comment by kdambekalns** [comment]
Well, so it seems.

Flow 3.3, 4.0 (https://github.com/neos/flow-development-collection/tree/4.0/Neos.Flow/Documentation/TheDefinitiveGuide/PartV/ReleaseNotes) as well as Neos 3.0 (https://github.com/neos/neos-development-collection/tree/3.0/Neos.Neos/Documentation/Appendixes/ReleaseNotes)
