### ISSUE TITLE
Documentation wrongly says that Flow only supports PSR-0 autoloading

### ISSUE THREAD

**Issue by markwatney2016** [neos/flow-development-collection#751]
### Description

Documentation about autoloading is out of date.

> Currently Flow only supports PSR-0 autoloading and will only use the first entry given in the manifest.
...
Other autoloading ways (classmap generation and files) are currently not supported by Flow.

### Steps to Reproduce

http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/PackageManagement.html#using-3rd-party-packages

**Comment by albe** [comment]
Anyone with autoloading insights out to fix up this documentation section? @kitsunet @kdambekalns ? I'm not even sure the thing about "only use the first entry" is correct any more

**Comment by kdambekalns** [comment]
Considering https://github.com/neos/flow-development-collection/blob/8f13a0dfc143e851a0e596e37e8d3f8e44e21276/Neos.Flow/Classes/Core/ClassLoader.php#L28-L46 this is no longer true, indeed…

**Comment by kitsunet** [comment]
I can try to fix it
