### ISSUE TITLE
"Edit on Github" Link in documentation leads to 404 page

### ISSUE THREAD

**Issue by markwatney2016** [neos/flow-development-collection#752]
### Description

"Edit on Github" Link in documentation leads to 404 page

### Steps to Reproduce

http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/PackageManagement.html#using-3rd-party-packages

**Comment by kitsunet** [comment]
This is a known issue with readthedocs and how this link is generated, if you switch to a defined version branch (eg. 4.1) http://flowframework.readthedocs.io/en/4.1/TheDefinitiveGuide/PartIII/PackageManagement.html then the link to github works correctly. Just the default "stable" produces a wrong link :(
