### ISSUE TITLE
Resource clean with Neos breaks

### ISSUE THREAD

**Issue by kitsunet** [neos/flow-development-collection#797]
Neos 2.3

The `resource:clean` command uses AssetUsageStrategies, of which one is delivered with Neos to check for usage in Node properties. Unfortunately that expects a user (and it's workspace to exist) which isn't the case on command line. It should behave gracefully and fall back to live for example.

**Comment by kitsunet** [comment]
Another issue with resource:clean and Neos https://github.com/neos/neos-development-collection/issues/865

**Comment by sorenmalling** [comment]
@kitsunet Do you know if this issue is still existing with currenct versions? 

If yes, can you elaborate on what Flow specific issue is present here?

**Comment by mhsdesign** [comment]
Will continue the conversation in https://github.com/neos/neos-development-collection/issues/865
