### ISSUE TITLE
Replace "distribution" front controllers

### ISSUE THREAD

**Issue by kitsunet** [neos/flow-development-collection#800]
`flow` / `flow.bat` / `index.php` all contain references to TYPO3.Flow and are not replaced during the update, we need to find a way to fix this for existing installations.

Solution idea: We could check the file content for all three classes for the existence of "TYPO3" and if it exists either str_replace the parts OR replace the full file (might be breaking if it was customized). This can easily happen in the composer installer scripts in which we also copy those files if they don't exist.

**Comment by kitsunet** [comment]
See https://gist.github.com/kitsunet/73e369acc069a9151f4019d3774cccd3

**Comment by kitsunet** [comment]
Now https://github.com/neos/distribution-upgrades

**Comment by robertlemke** [comment]
This works fine, despite the `index.php` which still contains a PSR-0 path leading to the Bootstrap after migration.

**Comment by robertlemke** [comment]
Fixed now.
