### ISSUE TITLE
TypeConverterCommandController fails with casting

### ISSUE THREAD

**Issue by kaystrobach** [neos/flow-development-collection#828]
In Flow 3.2 and 3.3 the `typeconverter:list` has a bug.

```
    public function listCommand()
    {
        …
                foreach ($priorityAndInstance as $priority => $instance) {
                    # --> following lines get_class will fail on strings, so easy fix with condition
                    if (is_object($instance)) {
                        $this->outputFormatted('%3s: %s', [$priority, get_class($instance)], 8);
                    } else {
                        $this->outputFormatted('%3s: %s', [$priority, (string)$instance], 8);
                    }
        …
```

**Comment by kdambekalns** [comment]
@kaystrobach When does this happen? Why is `$instance` not an actual instance?

**Comment by kdambekalns** [comment]
As per https://github.com/neos/flow-development-collection/blob/3.0/TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMapper.php#L72-L84 there must be an instance… same in 3.1

Ok, in 3.2 (and 3.3) we have https://github.com/neos/flow-development-collection/blob/3.2/TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMapper.php#L389-L403 and there https://github.com/neos/flow-development-collection/blob/3.2/TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMapper.php#L399 is plain wrong. 😨 

In 4.0 the list command is very different but also deals with classnames coming back (see https://github.com/neos/flow-development-collection/blob/4.0/Neos.Flow/Classes/Command/TypeConverterCommandController.php#L55), even though the comments in `PropertyMapper` still claim instances: https://github.com/neos/flow-development-collection/blob/4.0/Neos.Flow/Classes/Property/PropertyMapper.php#L418

So, what is right, what is wrong? Shouldn't there still be instances?

Ah! `getTypeConverters()` is used _only_ in the list command… _sigh_

**Comment by kaystrobach** [comment]
Commandline with the command above

**Comment by kitsunet** [comment]
Instances are lazily created since (have to find that PR) therefore it can be a string OR an instance.

**Comment by kdambekalns** [comment]
No, according to the code in `PropertyMapper` it is always a classname since 3.2…

**Comment by kitsunet** [comment]
Right, my mistake, I thought the instances were cached in the same array as well...
