### ISSUE TITLE
Raise doctrine/dbal requirement to 2.6 (once released)

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#833]
### Description

As a support to the Neos CR work and to remove custom implementation of json column support, the requirement of doctrine/dbal could be raised to 2.6 (https://github.com/doctrine/dbal/pull/2266) which currently implement support for the the json field introduced in mysql 5.7.8.

### Affected Versions

Flow: dev-master (upcoming 4.0)

**Comment by kitsunet** [comment]
4.0 is already branched, and dev-master will become the versoin afterwards. This requirements raise is to late for 4.0.

**Comment by albe** [comment]
But nothing speaks generally against doing this in 4.x, right?

**Comment by kdambekalns** [comment]
See

- https://github.com/neos/flow-development-collection/pull/1272
- https://github.com/neos/neos-development-collection/pull/1993

**Comment by albe** [comment]
Can be closed I guess.
