### ISSUE TITLE
Removing a cache entry leaves lock file behind

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#858]
### Description

When a cache entry is written (in a file-based cache backend), a lock file is created. When such a cache entry is removed again, the lock file is not removed and left behind.

In case of caches that potentially generate a lot of entries over time (e.g. session cache), this can lead to exhaustion of available inodes.

### Steps to Reproduce

1. Create sessions in a Flow setup
2. Garbage collect sessions

#### Expected behavior

For the removed sessions the lock files corresponding to the session cache entries should be removed.

#### Actual behavior

The lock files are left in place.

### Affected Versions

Flow: 3.3.x and probably all other versions using the same locking mechanism.

**Comment by kdambekalns** [comment]
@TheLalaMan

**Comment by kdambekalns** [comment]
When removing a cache entry, the `Lock` is acquired, the cache entry removed and the `release()´  is called on the lock. So, if `Lock` had a `remove()` method… the lock file could be removed.

But, given our history with locking, I fear that not having a lock file might again lead to race conditions when a cache entry is needed again… OTOH, most cache entries that are explicitly `remove()`d probably don't fall into that category…

Opinions?

**Comment by kitsunet** [comment]
Hard to say, could work, but technically might lead to race conditions on cache "rewrites" eg. cache flush / request events.

**Comment by kdambekalns** [comment]
Well, if a cache is empty and to be warmed, that is the same as now (no lock file exists). Plus, as said, if done only on `remove` it should be "even safer".

We could even start with this in `SimpleFilebackend::remove()`:

````
            $lock = new Lock($pathAndFilename);
            unlink($pathAndFilename);
            $lock->release();
            // now remove lock file as well
            if ($lock->getLockStrategy() instanceof \TYPO3\Flow\Utility\Lock\FlockLockStrategy) {
                unlink($lock->getLockStrategy()->getLockFileName());
            }
````

**Comment by albe** [comment]
It's exactly what was long discussed and finally solved by https://github.com/neos/flow-development-collection/pull/417 for 4.0

The issue with the remove of the lock file is, that it's not guaranteed to succeed and if it does, it creates a race condition (file being removed while another process holds a lock on it, which *is* possible on *NIX).
You can pretty much follow all the discussion leading to the solution above in the cross-referenced issues.

Best bet would be to down-merge the solution to 3.x (which was originally my intention to have in 3.3)

**Comment by kdambekalns** [comment]
Great… thanks for the pointer.

**Comment by albe** [comment]
Is this really still an issue for 4.x or is it now just about to down-merge the solution to 3.x?

**Comment by kitsunet** [comment]
Not an issue for 4.x anymore and no down merge pls

**Comment by kdambekalns** [comment]
Why no down merge? Because opening up a can of worms?

**Comment by kitsunet** [comment]
I'd say so, also we never downmerged? 

https://github.com/neos/flow-development-collection/pull/417

The first thing to mention here is that the order of information in file caches is changed by this. IMHO nothing to deliver in a bugfix release... So 👎 for downmerge

**Comment by kitsunet** [comment]
Closing for now...
