### ISSUE TITLE
ClassLoader not respecting FLOW_PATH_TEMPORARY_BASE

### ISSUE THREAD

**Issue by ddoehring** [neos/flow-development-collection#866]
### Description

Proxy class cannot be found if you have an existing code cache and changed FLOW_PATH_TEMPORARY_BASE.

### Steps to Reproduce

1. You have an existing warm code cache
2. You modify the ENV variable FLOW_PATH_TEMPORARY_BASE
3. You add some new classes (e.g. ViewHelper)
4. Classes don't get loaded via proxy => dependency injection broken

#### Expected behavior

New classes compile new proxies and are therefore loaded via AvailableProxies from the new FLOW_PATH_TEMPORARY_BASE.

#### Actual behavior

The Classloader loads the AvailableProxies from the FLOW_PATH_DATA, which didn't change.

### Affected Versions

Flow:  probably all

**Comment by kitsunet** [comment]
Is this Development or Production context or both?

**Comment by hhoechtl** [comment]
We had the issue in the Development context
