### ISSUE TITLE
Flow Default Routes never included in basic flow installation

### ISSUE THREAD

**Issue by kitsunet** [neos/flow-development-collection#868]
We removed the default Routes.yaml but also don't include routes via Settings so that a Flow installation is without routes, breaking existing documentation and tutorials.

**Comment by bwaidelich** [comment]
FYI: The default `Routes.yaml` has been removed with #790 in order to promote Settings-based routes.
The `Settings.yaml.example` has been adjusted accordingly so new installations should work out of the box.
Do you have an idea on how to improve the situation for upgrades (apart from still missing upgrade instructions)?

**Comment by kitsunet** [comment]
I remember we even discussed this, I think I just forgot. For some reason we decided against adding this setting to the default Flow Settings.yaml, right?

We at least need to adjust documentation and tutorials so that people that rely on those fallback rules know what to do.

**Comment by bwaidelich** [comment]
>  For some reason we decided against adding this setting to the default Flow Settings.yaml, right?

Yes, we decided to do that for the [Neos Routes](https://github.com/neos/neos-development-collection/pull/1343) though.

> We at least need to adjust documentation and tutorials

Fresh installations should be fine (if they copy the example Settings file). But, yes, it could be mentioned explicitly. And we urgently need upgrade instructions for Neos 3.0/Flow 4.0..

**Comment by sorenmalling** [comment]
As this is merged in https://github.com/neos/flow-development-collection/pull/1748 I suggest that this issue could/should be closed as solved
