### ISSUE TITLE
Add release notes for 3.3 and 4.0 to documentation

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#869]
As noticed in #746

**Comment by albe** [comment]
Is this still an issue?

http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartV/ReleaseNotes/400.html
http://neos.readthedocs.io/en/stable/Appendixes/ReleaseNotes/300.html

**Comment by kdambekalns** [comment]
Obviously it is, did you look at those documents? ;)

Those are rather stubs I added at some point, and they'd need some content (can be reused from the website)…

**Comment by albe** [comment]
Argh, you got me there! Maybe it works with others too? :D

**Comment by albe** [comment]
Ok, I added some release notes for 4.0.0 and release notes for 3.3.0 seem to be already existing though:

http://flowframework.readthedocs.io/en/3.3/TheDefinitiveGuide/PartV/ReleaseNotes/330.html

**Comment by albe** [comment]
So can this be closed?
