### ISSUE TITLE
Actual Doctrine exceptions swallowed leading to difficult debug situations

### ISSUE THREAD

**Issue by aertmann** [neos/flow-development-collection#870]
### Description

When Doctrine throws an exception it is caught in a reconnect attempt solution hiding the actual issue leading to difficult to understand situations.

### Steps to Reproduce

1. Alter a database table resulting in a mapping error.
2. Connect to Doctrine somehow

#### Expected behavior

Actual Doctrine mapping error exception being shown.

#### Actual behavior

Other exception being thrown by Doctrine due to the entity manager being closed (side-effect).

### Affected Versions

3.0 to 4.0

### Information

This is the change that introduced the issue https://github.com/neos/flow-development-collection/commit/93b458812493f23c89d6ef8815acbe4d57b53256

Since https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php#L168 catches all exceptions, not just database connection failed exceptions (if they exist?) and tries to connect again it happens. Instead of catching all, it should catch a specific exception or at the very least check if the exception has anything to do with database connectivity issues. If not it should throw it.

The actual exception does actually gets logged, but if you're debugging and looking at the exception print it's not obvious that there might be other information available in the log, thus leading users on wild goose hunts.

**Comment by aertmann** [comment]
Maybe one of you have some thoughts on the topic? @kdambekalns, @brgmn, @bwaidelich

**Comment by bwaidelich** [comment]
The original exception is logged, but I see that this can lead to hard-to-debug situations! I wonder why we ended up catching all generic Flow Exceptions there.. In the [corresponding ticket](https://jira.neos.io/browse/FLOW-207) it was suggested to only catch `DBALException` - and even that could probably be limited to some more specific exceptions that only occur if the connection to the DB server was lost..

**Comment by albe** [comment]
Definitely makes sense, also had a report on slack about this catching lately
https://neos-project.slack.com/archives/C04V4C6B0/p1490356718574239

Makes total sense to restrict this catching at least to DBAL Exceptions. Anyone up for taking this on?

**Comment by sorenmalling** [comment]
@albe @bwaidelich @aertmann From what I read today (3 years later - a lot may have changed) we do not catch a Flow exception (nor a doctrine exception) inside PersistenceManager::persistAll https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php#L87

Is this still relevant? 

I believe to this day, not have seen the "connect is closed" exception when having Doctrine exceptions (database mapping) being thrown.

Can this issue be considered solved or do I overlook a trace of exceptions here, that leads to the not-so-good developer and debug experience?

**Comment by sorenmalling** [comment]
Btw, the PersistanceMAnager at the time of writing might have been around this state
https://github.com/neos/flow-development-collection/blob/48da88f2d1e42bbb5b7abdea1bb20b4c97385723/Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php

where a exception is thrown and a "simplified" log message being logged

**Comment by albe** [comment]
Yes, I think this can be closed, since we now explicitly try to prevent a closed entity manager through the ping and don't catch/rethrow any doctrine exceptions during `flush()`
