### ISSUE TITLE
Account::isActive returns false when expirationDate is set

### ISSUE THREAD

**Issue by maltemuth** [neos/flow-development-collection#873]
### Description

The Security\Account::isActive should return true if expirationDate is set in the past, but doesn't.

### Steps to Reproduce

Set the expiration date one minute into the future.
```
$account->setExpirationDate( (new \DateTime())->add(new \DateInterval("PT1M") );
```

#### Expected behavior

```
$account->isActive() // true, since it's not expired yet
```

#### Actual behavior

```
$account->isActive() // false - either $this->now is null when Injection didn't happen, or a Proxy (since it's lazy-injected); in either case the > check return false
```

### Affected Versions

Flow: 4.0.1, 3.2

**Comment by kdambekalns** [comment]
Fixed with #875
