### ISSUE TITLE
Http\Request does not take port into concern, when used in UriBuilder

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#874]
### Description

Running in exmaple a docker container, where the a port numer is exposed in the url (ex. `http://localhost:83123`) the port numer is not taken into concern, when setting the initial uri.

The hostname is collected in the `build` method call here:
https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/Routing/UriBuilder.php#L355

The uri is putted together here:
https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Http/Request.php#L111

### Steps to Reproduce

1. Start a docker container running flow and have a url with exposed port number
2. Create a url to any given controller/action

#### Expected behavior

Expected url: http://localhost:83123/route-path

#### Actual behavior

Created url: http://localhost/route-path

### Affected Versions

Neos: master

Flow: master

**Comment by kitsunet** [comment]
this is not exactly something you can fix in neos IMHO. Docker is exposed to the outside with that port, internally runs in port 80 though. `HTTP_HOST` will contain `localhost` (maybe `localhost:80`). You either need to create a setup with a proxy that sets correct proxy headers (or make docker do that) or you configure a baseUri in Flow settings (which includes the port).
