### ISSUE TITLE
Using Google_Client v2 causes class not found error

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#876]
### Description

Using the google/apiclient library in v2.1.2 we got class not found when doing `new \Google_Client`. Since it was all doing the same as in another project we looked for differences - being the library having moved from 1.1.7 to 2.1.2. That comes with a change in `composer.json`, specifically the `autoload` section:

- 1.1.7: https://github.com/google/google-api-php-client/blob/1.1.7/composer.json#L15-L19
- 2.1.2: https://github.com/google/google-api-php-client/blob/v2.1.2/composer.json#L28-L35

This was done in https://github.com/google/google-api-php-client/commit/ec32df17354142f5a4762af18426c0175cebf58d and while the use of `Google_` as PSR-0 prefix looks weird, it **is** a valid namespace prefix according to the Composer docs.

Reason: our own autoloader doesn't care at all about the underscore thing. The `ClassLoaderTest` tests that mention underscores are either broken or test the wrong or to little things.

Note: It works fine when using the optimized autoloader (`composer dump-autoload -o` fixes the error). This is because in that case the full list of all classes is contained in the classmap composer generates, including `Google_Client` (and related ones).

### Steps to Reproduce

1. Install `google/apiclient`
2. Make sure you are not using the optimized autoloader
3. Do `new \Google_Client()` in e.g. a command controller

#### Expected behavior

A happy instance being created.

#### Actual behavior

Class Google_Client cannot be found, PHP dies. Not happy.

### Affected Versions

Flow: at least 3.x

**Comment by kdambekalns** [comment]
Ever so slightly related to #654…

**Comment by kdambekalns** [comment]
@kitsunet might have some insight here?

**Comment by kdambekalns** [comment]
Oh, and thanks to @Inchie for bringing this up…

**Comment by kitsunet** [comment]
if it's according to standards then the composer class loader should load it just fine and as that is used since 3.2 for most things it should not be our class loader, but I guess I need to see it myself.

**Comment by kitsunet** [comment]
Works fine for me in a 3.3...

**Comment by kitsunet** [comment]
Pre 3.2 this might be broken, but I'd say `won't fix`.

**Comment by kdambekalns** [comment]
@Inchie - which version are you using currently?

**Comment by Inchie** [comment]
I use 3.0.10. I am going to update flow soon.
