### ISSUE TITLE
Feature Proposal: Extend repository pattern to fetch single columns in addition to whole model objects.

### ISSUE THREAD

**Issue by jdoubleu** [neos/flow-development-collection#877]
When using the repository pattern I came across some situations where I just needed specific fields rather than whole data sets. For example: The id's of a Domain Model.

The only way to get them is to fetch alle models or create a custom query (which is not an option). It's very a pain if you have to fetch alle data, this consumes cpu time, memory and then you are only using a small set of this.

Though you can add such functionality in your own repository I would propose to add it to the defaults (Generic) repository [`__call`](https://github.com/neos/flow/blob/master/Classes/Persistence/Repository.php#L214) function.

Yet this magic method accepts:
- findBy<PropertyName>
- findOneBy<PropertyName>
- countBy<PropertyName>

If there were some syntax like:
- find<ColumnName>By<PropertyName>
- findOne<ColumnName>By<PropertyName>

that would be helpful in many ways. This would then return an array (of datatypes of the columns datatype) carrying the values rather than a Model.

One more thought was to return a lazy loaded Model which has the searched values set and others will be fetched when they are needed.

For the Database Layer (Doctrine) this is already possible through Doctrine can select specific columns of a database table.

**Comment by albe** [comment]
TBH I'm not so sure this is something that Flow should support out of the box, because Flows focus lies on DDD and modelling. This does in no way mean that the use case is not there, it certainly is, but IMHO that is something that can easily be dealt with specific queries inside your applications Repository (or even an abstract base repository if you need the same query for multiple Aggregates) instead of through a generic method.

I'd like to hear some others' opinion first before deciding though

**Comment by jdoubleu** [comment]
Okay, thanks for the repsonse.

Yet I'm implementing it in a base repository, each time, so I thought this is something the framework should do and, as you mentioned, others profit too. 

Indeed it doesn't fit in the DDD approach.
Using proxy models with lazy loaded properties wouldn't be either the solution, would it?

**Comment by bwaidelich** [comment]
I second @albe's opinion. If you only need a subset of the columns either create a more specific (read) model or use `DQL`/`SQL` directly

**Comment by kitsunet** [comment]
Yep, I think read model is the right way to do this.

**Comment by albe** [comment]
Closing this for now. If you feel like there is still something to discuss, feel free to reopen @jdoubleu
