### ISSUE TITLE
Empty privilege target remove previously defined targets

### ISSUE THREAD

**Issue by DanielSiepmann** [neos/flow-development-collection#890]
### Description

It's not possible to make any web request or cli request without receiving the following issue, once another package "empties" the "privelege target":

```
privilege target "Neos.Media:Thumbnail", referenced in role configuration "Neos.Flow:Everybody" is not defined!

  Type: Neos\Flow\Security\Exception
  Code: 1395869320
  File: Packages/Framework/Neos.Flow/Classes/Security/Policy/PolicyService.php
  Line: 123

Open Data/Logs/Exceptions/201703151019335b094d.txt for a full stack trace.
```

### Steps to Reproduce

1. Install a fresh flow installation using `composer create-project --keep-vcs neos/flow-base-distribution`
2. Require 'neos/media' by running: `composer require neos/media`
3. Require or create another package configuring "privelege targets" the following: 
```yaml

privilegeTargets:

  Neos\Flow\Security\Authorization\Privilege\Method\MethodPrivilege: {  }
```
4. Call `./flow help`

#### Expected behavior

Caches are generated and I can use the Framework as usual. Make web requests and call `./flow help`.

#### Actual behavior

The error, as reported above, is shown on CLI and Web Response.

The second package will remove the prviousley defined privilege targets.

### Affected Versions

Neos: -

Flow: 4.0.2, dev-master 98c5a1a

**Comment by DanielSiepmann** [comment]
Or is it intended to allow the "deletion" of previously defined targets?

**Comment by kitsunet** [comment]
Yes, that is intentional from all I know. Currently would close as "won't fix".

**Comment by shizonic** [comment]
I just encounter the same issue. Is there any progress in fixing it?

**Comment by svparijs** [comment]
Got the same error... any idea's?
