### ISSUE TITLE
AjaxWidgetConfiguration is not used in controller

### ISSUE THREAD

**Issue by DanielSiepmann** [neos/flow-development-collection#896]
### Description

If you modify Widget configuration for ajax widgets inside of ``getAjaxWidgetConfiguration`` it's not used inside of the controller. Instead the non ajax widget configuration is used.

### Steps to Reproduce

1. Build a WidgetViewHelper
2. Configure ViewHelper to use Ajax
3. Extend ``getAjaxWidgetConfiguration`` and modify the returned configuration

#### Expected behavior

The returned configuration is accessable inside of the controller in ``$this->widgetConfiguration``.

#### Actual behavior

The configuration returned by ``getNonAjaxWidgetConfiguration`` is provided instead.

### Research / bug report

The bug is introduced through https://github.com/neos/flow-development-collection/blob/4.0.2/Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetViewHelper.php#L131 where the ``NonAjaxWidgetConfiguration`` is always set, even for ajax widgets. Afterwards https://github.com/neos/flow-development-collection/blob/4.0.2/Neos.FluidAdaptor/Classes/Core/Widget/WidgetContext.php#L127 is called by https://github.com/neos/flow-development-collection/blob/4.0.2/Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetController.php#L53 which will first check whether ``nonAjaxWidgetConfiguration`` exists, which is always the case, and return that instead of the ``ajaxWidgetConfiguration``.

The easiest possible solution would be to invert the condition / check in https://github.com/neos/flow-development-collection/blob/4.0.2/Neos.FluidAdaptor/Classes/Core/Widget/WidgetContext.php#L127 to return the ajax config if it's not null.

### Affected Versions

Flow: 4.0.2, master

**Comment by fcool** [comment]
The behaviour is correct. Everything behaves as it should be.

What really is confusing, that, if a widget-ViewHelper no ChildNodes (say: empty tag), it does not get the viewHelperNodes and the crucial ViewHelperVariableContainer set in its RoodNode.

I'm not sure if this is an issue or a real cool Fluid feature...
