### ISSUE TITLE
Fizzle cannot filter by nested object property

### ISSUE THREAD

**Issue by kitsunet** [neos/flow-development-collection#899]
### Description

By looking at descriptions and grammer a fizzle filter should support filtering by nested object properties but that doesn't work in the way the parser works currently.

### Steps to Reproduce

Given I have an array of (Media) Asset objects $assets and I want to filter them via FlowQuery/Fizzle by fileExtension (path: `resource.fileExtension`), I would try the following expression:

```
$flowQuery = new FlowQuery($assets);
$flowQuery->filter('[resource.fileExtension = pdf]');
```

This will throw an error because Fizzle cannot parse the property path containing `.`, also alternatives like `resource/fileExtension` won't work.

#### Expected behavior

The FlowQuery context contains an array of assets only with "pdf" file extension.

#### Actual behavior

A Fizzle parser error is thrown.

### Affected Versions

all

**Comment by kitsunet** [comment]
@hlubek Can you confirm this is a bug and not intended missing behavior? I think the fix is rather easy (to allow `.` in the filter parser)...

**Comment by aertmann** [comment]
Would be surprised if it was intentional, rather not thought of. In any case makes sense to support.

**Comment by joachimmathes** [comment]
Got some introduction by @kitsunet and give it a try now. :)

**Comment by joachimmathes** [comment]
Made a pull request: https://github.com/neos/flow-development-collection/pull/924
