### ISSUE TITLE
Wrong type definition in RadioViewHelper for "value" argument

### ISSUE THREAD

**Issue by p34ch** [neos/flow-development-collection#930]
In the`RadioViewHelper` of the FluidAdaptor package the `value` attribute is defined with type `string`. I think the correct type should be `mixed` since it's `mixed` in the`CheckboxViewHelper` and objects/entities are handled correctly.

The `value` argument is overridden here: https://github.com/neos/flow-development-collection/blob/930e627d09367e944410397b9853b15c448e35ef/Neos.FluidAdaptor/Classes/ViewHelpers/Form/RadioViewHelper.php#L64

**Comment by kitsunet** [comment]
Fixed for next version.
