### ISSUE TITLE
Custom configuration types break the compilation process

### ISSUE THREAD

**Issue by KaiLehmann** [neos/flow-development-collection#934]
### Description

Registering a custom configuration type produces a PHP undefined index error and breaks the compilation process.

This can be fixed in \Neos\Flow\Configuration\ ConfigurationManager:: loadConfiguration() in line 459 by replacing
`if ($this->configurations[$configurationType] !== []) {`
with
`if (isset($this->configurations[$configurationType])) {`

I tried to do a pull request, but my GIT knowledge is too bad and it somehow didn't work ...

### Steps to Reproduce

1. Register a custom configuration type like so:
```
class Package extends \Neos\Flow\Package\Package {
	public function boot(\Neos\Flow\Core\Bootstrap $bootstrap) {
		$dispatcher = $bootstrap->getSignalSlotDispatcher();
		$dispatcher->connect(\Neos\Flow\Configuration\ConfigurationManager::class, 'configurationManagerReady',
			function (\Neos\Flow\Configuration\ConfigurationManager $configurationManager) {
				$configurationManager->registerConfigurationType(
					'MyCustomConfiguration',
					\Neos\Flow\Configuration\ConfigurationManager::CONFIGURATION_PROCESSING_TYPE_SETTINGS
				);
			}
		);
	}
}
```
2. Flush all caches
3. CLI: ./flow or load any controller

#### Expected behavior

The custom configuration type is registered.

#### Actual behavior

```
Notice: Undefined index: MyCustomConfiguration in /xyz/Packages/Framework/Neos.Flow/Classes/Configuration/ConfigurationManager.php line 459

Type: Neos\Flow\Error\Exception
Code: 1
File: Packages/Framework/Neos.Flow/Classes/Error/ErrorHandler.php
Line: 81

Open Data/Logs/Exceptions/20170408101204dfb1f2.txt for a full stack trace.

Exception Code	1355480641
Exception Type	Neos\Flow\Core\Booting\Exception\SubProcessException
Log Reference	2017040810120348dee0
Thrown in File	Packages/Framework/Neos.Flow/Classes/Core/Booting/Scripts.php
Line	632
```

### Affected Versions

Flow: 4.*

### More information

This is a little difficult to debug since it happens during compilation. The following happens during compilation after all caches have been flushed:

1. CacheManager::flushConfigurationCachesByChangedFiles() calls $this->configurationManager->refreshConfiguration();
2. ConfigurationManager::refreshConfiguration() calls $this->saveConfigurationCache();
3. ConfigurationManager::saveConfigurationCache() calls $this->loadConfiguration($configurationType, $this->packages); for all $this->configurationTypes
4. ConfigurationManager::loadConfiguration() checks if any configuration exists for this configuration type with `if ($this->configurations[$configurationType] !== []) {`. This fails because the index "MyCustomConfiguration" is not present at this time.

This was handled differently in Flow 3.* where ConfigurationManager::saveConfigurationCache() was not called when caches were flushed, so this bug was not there. There is currently no unit test for this as far as I can see.

**Comment by kitsunet** [comment]
Sounds correct, will have a look at that. Thanks for reporting.

**Comment by bwaidelich** [comment]
Makes sense, thanks for your bug report!
@kitsunet I assigned the ticket to you to avoid cookie licking. Feel free to re-assign it to me, then I'll have a look
