### ISSUE TITLE
 Catch errors while publishing invalid resources

### ISSUE THREAD

**Issue by kitsunet** [neos/flow-development-collection#958]
Jira issue originally created by user @robertlemke:

Steps:
- one or more resources which are registered in the database don't have a matching file in Data/Persistent/Resources
- run ./flow resource:publish
- depending on the publishing target, the command will fail at least with an uncaught exception when the target tries to publish the broken resource

The targets should rather collect information about problems (maybe like the validation errors) and output a list of broken resources but continue.

 Jira-URL: https://jira.neos.io/browse/NEOS-743

Moved from https://github.com/neos/neos-development-collection/issues/1033

**Comment by sorenmalling** [comment]
Hi @kitsunet 

Today, if I delete a file from Data/Persistent/Resources and run `./flow resource:publish` I get the following exception in return along with my "success message"

```
➜  website git:(master) ✗ ./flow resource:publish
Publishing resources of collection "static"
Publishing resources of collection "persistent"

The resources were published, but a few inconsistencies were detected. You can check and probably fix the integrity of the resource registry by using the resource:clean command.
Error: Could not publish resource codefort-371x100.png with SHA1 hash f02404dc46cfbd43bcde17745a6604edc664c394 of collection persistent because there seems to be no corresponding data in the storage.
```

I guess this is what you aimed for, when originally creating this issue?

If yes, will you confirm and close this ticket?

**Comment by kitsunet** [comment]
Pretty sure that was a problem of a specific target which I forgot by now. If I find this again I will reopen it.
