### ISSUE TITLE
Migrationstatus command broken

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#976]
### Description

Running `./flow doctrine:migrationstatus --show-migrations` results in a PHP error
```
Notice: Undefined variable: configuration in Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Persistence_Doctrine_Service.php line 285
```
The reason is most probably a little regression introduced with #857

### Steps to Reproduce

Run the `doctrine:migrationstatus` command with `--show-migrations` flag

#### Expected behavior

A list of migrations with their status

#### Actual behavior

The PHP notice mentioned above

### Affected Versions

Flow: dev-master (after d6dba06286bc02a57ff37ea26211837a586a31ea)

**Comment by tvt** [comment]
Shouldn't this fix also be in the neos/flow 4.1 branch?
