### ISSUE TITLE
Querying a property of an embedded value object will fail

### ISSUE THREAD

**Issue by Torsten85** [neos/flow-development-collection#989]
### Description

It is not possible to query a nested field of an embedded value object like this:
`$query->matching( $query->equals('valueObject.property', 'value')`.

### Steps to Reproduce

1. Create an Entity (`@Flow\Entity`)
2. Create a Embedded Value Object (`@Flow\ValueObject(embedded=true)`)
3. Create a relation ship between Entity and ValueObject
4. Query for a value object property

#### Expected behavior

The query should return a non-empty QueryResult

#### Actual behavior

Currently the doctrine Query implementation assumes that every nested property belongs to a relation and by that (left) joins that entity. 
I think somewhere here https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Persistence/Doctrine/Query.php#L658 should be a check if the property belongs to a value object, and if so the join should be skipped.

**Comment by Torsten85** [comment]
@albe

**Comment by albe** [comment]
Thanks for filing the issue. I think we need to somehow find a solution for this, but it is far from trivial to solve. The main issue is, that we somehow need knowledge about the reflected entity hierarchy **inside the Query object**.

Maybe we need to reevaluate the whole concept of the Query model or at least the `getPropertyNameWithAlias` internal.

@kdambekalns @bwaidelich @kitsunet Anyone of you guys have an idea how to approach this? Can we maybe delegate this to the QueryBuilder?

**Comment by MarkusRodler** [comment]
I stumbled over this bug, too. I wanted to order by the value object and it fails. As a workaround I tried to add the required field also in the Entity with another name mapping to the same database field but that also fails. 
@Torsten85 Do u maybe found a workaround for this?
@albe Are there any updates or progress on this topic?

**Comment by albe** [comment]
@MarkusRodler unfortunately not. My focus is currently on the typehinting move and general focus on the upcoming 3.2/4.2 release. I'll try to push the issue again after the release.

**Comment by Torsten85** [comment]
@MarkusRodler the only "easy" workaround for this is DQL.

**Comment by MarkusRodler** [comment]
Thanks for the quick reply's.
@albe the typehinting move sounds interesting for me. I think that I found another bug yesterday with void return type declaration. I have to verify it first and check afterwards if a issue on this topic exists. But my question is: Can u tell me what exactly u r focussing on the typehinting move?

**Comment by albe** [comment]
I have an meta issue open for that: https://github.com/neos/flow-development-collection/issues/1023 it references all PRs that deal with adding typehints, so if you find something around the topic, feel free to comment there (or create a new issue and reference it there)

**Comment by MarkusRodler** [comment]
I made an issue for the void return-type error: #1065

**Comment by MarkusRodler** [comment]
@Torsten85 thanks for the hint with an own dql query. It was not that trivial to figure out how to use it and I have no idea if I am using it the right way, but I can confirm that it works with dql. :)
